### ISSUE TITLE
Hello World example doesn't build in iOS 8.1

### ISSUE THREAD

**Issue by RobBrennan** [swisspol/GCDWebServer#101]
I've followed the instructions in the README for adding the GCDWebServer to an empty Xcode project, but it will not build in iOS 8.1:

AppDelegate.m
# import "AppDelegate.h"
# import "GCDWebServer.h"
# import "GCDWebServerDataResponse.h"

@interface AppDelegate (){
    GCDWebServer *_webServer;
}

@end

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
  // Override point for customization after application launch.
  
  // Create our web server
  _webServer = [[GCDWebServer alloc] init];
  
  // Add a handler to respond to GET requests on any URL
  [_webServer addDefaultHandlerForMethod:@"GET"
                            requestClass:[GCDWebServerRequest class]
                            processBlock:^GCDWebServerResponse _(GCDWebServerRequest_ request) {
  
  ```
                            return [GCDWebServerDataResponse responseWithHTML:@"<html><body><p>Hello World</p></body></html>"];
  
                        }];
  ```
  
  // Start our server
  [_webServer startWithPort:8080 bonjourName:nil];
  NSLog(@"Visit %@ in your web browser", _webServer.serverURL);
  
  return YES;
  }

Output log when attempting build in Xcode:
Build target iOSServer

Ld DerivedData/iOSServer/Build/Products/Debug-iphoneos/iOSServer.app/iOSServer normal arm64
    cd "/Users/rob/Documents/General UI/iOSServer"
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.1.sdk -L/Users/rob/Documents/General\ UI/iOSServer/DerivedData/iOSServer/Build/Products/Debug-iphoneos -F/Users/rob/Documents/General\ UI/iOSServer/DerivedData/iOSServer/Build/Products/Debug-iphoneos -filelist /Users/rob/Documents/General\ UI/iOSServer/DerivedData/iOSServer/Build/Intermediates/iOSServer.build/Debug-iphoneos/iOSServer.build/Objects-normal/arm64/iOSServer.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -fobjc-arc -fobjc-link-runtime -miphoneos-version-min=8.1 -Xlinker -dependency_info -Xlinker /Users/rob/Documents/General\ UI/iOSServer/DerivedData/iOSServer/Build/Intermediates/iOSServer.build/Debug-iphoneos/iOSServer.build/Objects-normal/arm64/iOSServer_dependency_info.dat -o /Users/rob/Documents/General\ UI/iOSServer/DerivedData/iOSServer/Build/Products/Debug-iphoneos/iOSServer.app/iOSServer

Undefined symbols for architecture arm64:
  "_inflateEnd", referenced from:
      -[GCDWebServerGZipDecoder close:] in GCDWebServerRequest.o
  "_inflate", referenced from:
      -[GCDWebServerGZipDecoder writeData:error:] in GCDWebServerRequest.o
  "_deflate", referenced from:
      -[GCDWebServerGZipEncoder readData:] in GCDWebServerResponse.o
  "_deflateEnd", referenced from:
      -[GCDWebServerGZipEncoder open:] in GCDWebServerResponse.o
      -[GCDWebServerGZipEncoder close] in GCDWebServerResponse.o
      -[GCDWebServerGZipDecoder open:] in GCDWebServerRequest.o
  "_inflateInit2_", referenced from:
      -[GCDWebServerGZipDecoder open:] in GCDWebServerRequest.o
  "_deflateInit2_", referenced from:
      -[GCDWebServerGZipEncoder open:] in GCDWebServerResponse.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by matejkramny** [comment]
Hi Maintainers, I would find it very useful to have the 'libz' mentioned in the readme.

Thanks!
