### ISSUE TITLE
Use as proxy to remote web site for caching?

### ISSUE THREAD

**Issue by bradparks** [swisspol/GCDWebServer#108]
Hey! Do you know if it'd be reasonable/feasible to use this as proxy to cache remote web site assets?

So for example, say in my app I have 10 embedded webviews that actually load a remote website.

To force it to cache remote static assets locally, i proxy all the requests through a GCDWebServer instance, and store files in a local disk cache.

Then when the next webview loads them, they're loaded quickly since they're in the local cache....

Has anyone tried this? Thanks!

**Comment by EgoAleSum** [comment]
@swisspol do you have any examples of using GCDWebServer as a proxy? I'm looking at that too as a way to circumvent CORS...

**Comment by swisspol** [comment]
I don't have examples, but you should be able to use an async handler and just convert the `GCDWebServerRequest` to an `NSURLRequest` and when its results has been received, forward it using a `GCDWebServerDataResponse` (don't forget to copy the headers).

**Comment by EgoAleSum** [comment]
Ok it worked :) Remember to edit the "Host" header too!

**Comment by EgoAleSum** [comment]
Ok it worked :) Remember to edit the "Host" header too!
Thanks for the response

**Comment by bradparks** [comment]
@EgoAleSum - why don't you post your sample to Github somewhere, and then someone else could get it if they need it ? I personally don't need it now, but it may be useful to others ;-)

**Comment by EgoAleSum** [comment]
@bradparks 
Sadly I can't, because the company owns the code. I can ask my boss, but at the end it's just getting some properties from the server's request and putting them into AFNetworking :)

**Comment by bradparks** [comment]
as.... you... wish!

**Comment by suniljakhar** [comment]
@EgoAleSum  
Could you please explain me in details, how you do this. I m also looking for similar problem.

**Comment by lin-hun** [comment]
@suniljakhar me either,and how?

**Comment by guhan123** [comment]
@EgoAleSum : Did you use the approach suggested by @swisspol to cache the responses using GCDWebserver as proxy? Did you convert the GCDWebServerRequest to an NSURLRequest and when its results had been received, forward it using a GCDWebServerDataResponse?
How can you convert a post GCDWebserver request to NSURLRequest?  The GCDWebServerRequest does not have request body right?
