### ISSUE TITLE
Referring local files in HTML file

### ISSUE THREAD

**Issue by nishabe** [swisspol/GCDWebServer#117]
I am trying to run the GCDWebserver with a local HTML file. There is a script files that I am referring in this HTML file.

As of now I have given the remote URL path in the html file.
eg: <script src="http://d3js.org/d3.v3.min.jss"></script>   

How can give local path of this script file in the HTML string?
I have tried 
1) script src="/d3.v3.min.js"></script> and
2) script src="/Users/XXX/Library/Developer/CoreSimulator/Devices/40D2F2A5-342E-4468-A17B-415113BEBDF1/data/Containers/Bundle/Application/75F6C525-3063-41C2-B876-68CA4020BEC7/YYY.app/d3.v3.min.js"></script>.
Unfortunately both of them are not working.
Do you have a suggestion?

**Comment by bgoncal** [comment]
When I do that my web view tries to download the index.html instead of rendering it. I tried in safari (macOS) and every time I point to index.html it gets downloaded

**Comment by ufogxl** [comment]
> When I do that my web view tries to download the index.html instead of rendering it. I tried in safari (macOS) and every time I point to index.html it gets downloaded

+1
