### ISSUE TITLE
GCDWebServer change image served after web server start

### ISSUE THREAD

**Issue by jungchris** [swisspol/GCDWebServer#120]
How does one change the NSData served after the web server has been started?  

Specifically using the GCDWebServer library in an Objective-C project to serve images (and videos) using the return GCDWebServerDataResponse in addDefaultHandlerForMethod.  I would like to arbitrarily change the NSData referenced in 'responseWithData' and the contentType such as @"image/jpeg" after the server has been started without stopping and restarting the service.  I've noted that removing the handler while the server is running is not the proper way.

Here's part of the code used prior to the web server start request (This highlights where I want to arbitrarily change mediaData and contentType):

  return [GCDWebServerDataResponse responseWithData:mediaData contentType:contentType];

**Comment by swisspol** [comment]
You just need to create a new response and return it from within the handler block.

**Comment by swisspol** [comment]
I mean, from within the block, grab the image data, make a new response with it and return it. Don't cache the response outside the block or the server will always return the same one.

**Comment by jungchris** [comment]
Perfect, that's simple enough.  I thought that block was executed on startup only.  Thank you for this excellent library!

**Comment by hardikthakkar54** [comment]
@swisspol  - can you please elaborate more.
I have same issue -  below is my code - I need different image for same request

`let pngdata = imgSong.pngData()
                    let response = GCDWebServerDataResponse(data: pngdata!, contentType: "png")
                    response.cacheControlMaxAge = 0
                    completionBlock(response)`
