### ISSUE TITLE
Add thumb to index.html

### ISSUE THREAD

**Issue by IgorMD** [swisspol/GCDWebServer#121]
Hello,
I'm using WebServerUploader on Iphone.It works great, i can upload,delete,move,dowlnoad.
I added images in index.html for thumbnail images before files title. In my ios app sandbox i have images and thumbnails for every image.
The question is: How to get correctly path to this thumb because i'm trying to do something like this 
<*img width="100" height="100"src="{%=o.path%}/*> and I see that this is a wrong path because it contains only filename. Or i need to use addHandlerForMethod....... for every thumb?
I hope there is a way to make all my thumbs be accessible in local like:"192.444.1.43/imgthumb.jpg
Also I hope that you understand what i'm trying to ask.
Thanks.

**Comment by swisspol** [comment]
WebServerUploader does not generate thumbnails automatically for images. If you need this functionality you would need to modify the source code for it.
