### ISSUE TITLE
Static analyzer warnings

### ISSUE THREAD

**Issue by paulofierro** [swisspol/GCDWebServer#122]
I noticed that https://github.com/swisspol/GCDWebServer/commit/c4310fcdf48aed353d529ec4272e9e0fb5cce997 on Jan 6 fixes the static analyzer warnings.

However the podspec hasn't been updated since December 2, 2014. Could you please bump the version to 3.2.2? 

I'm not sure if I should fork the project and update the Podspec and submit a pull request — if that's the _correct_ process I'm happy to do it :)

In the meantime I'm using the following in my `Podfile`:

```
pod 'GCDWebServer', :git => 'git@github.com:swisspol/GCDWebServer.git'
```

Thanks!

**Comment by swisspol** [comment]
Done!

**Comment by paulofierro** [comment]
Woo! Thanks :+1:
