### ISSUE TITLE
Converting a GCDWebServerRequest into a NSURLRequest

### ISSUE THREAD

**Issue by alxppp** [swisspol/GCDWebServer#124]
Hi,

first, thanks for building this solid library!

Can you help me converting a GCDWebServerRequest into a NSURLRequest? Should be pretty simple in theory.

```objc
GCDWebServerRequest request; // This is the incoming request that should be converted to a NSURLRequest

NSMutableURLRequest *remoteRequest = [[NSMutableURLRequest alloc] init];
[remoteRequest setURL:[NSURL URLWithString:request.path relativeToURL:@"<some other host>"]];
[remoteRequest setHTTPMethod:request.method];
for (NSString *header in request.headers)
    [remoteRequest setValue:[request.headers valueForKey:header] forHTTPHeaderField:header];
[remoteRequest setHTTPBody:<body of the request>];
```

The first lines are working fine, but I'm stuck with the last one. How do I get the raw body of the request?

Any help is greatly appreciated.

Thanks,
Alex

**Comment by swisspol** [comment]
You need to use a subclass of `GCDWebServerRequest` that will "record" the incoming body to memory or on disk: https://github.com/swisspol/GCDWebServer/tree/master/GCDWebServer/Requests.

See the README file starting at https://github.com/swisspol/GCDWebServer#using-gcdwebserver.
