### ISSUE TITLE
GCDWebServer 2.5 to 3.2.2 version problem

### ISSUE THREAD

**Issue by aybarsyalcin** [swisspol/GCDWebServer#125]
Hi,
Firstly, thank you for writing this project. this project is the best HTTP web server for iOS.

I used version 2.5. I want to increase new version. When I start project on new version, "GWS_DCHECK(_options == nil);" this here stop project. What do I need? Please help me!

 server = [[GCDWebServer alloc] init];
 [server addGETHandlerForBasePath:@"/" directoryPath:self.CONSTANT_FOLDER_PATH indexFilename:nil cacheAge:0 allowRangeRequests:YES];
 [server startWithPort:self.CONSTANT_PORT bonjourName:@"test"];

 [server addHandlerForMethod:@"GET"
                      pathRegex:@"/*"
                   requestClass:[GCDWebServerRequest class]
                   processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {

**there is a my codes.
***
***
***

}];

**Comment by swisspol** [comment]
Some of the APIs have changed, look for warnings in your code: you might be calling an old API that doesn't exist anymore and GCDWebServer doesn't get initialized properly.

**Comment by aybarsyalcin** [comment]
Hi, I solve this problem.
"startWithPort" function is must be added after "addGETHandlerForBasePath" function.

This code is working:
```
server = [[GCDWebServer alloc] init];

[server addGETHandlerForBasePath:@"/" directoryPath:self.CONSTANT_FOLDER_PATH indexFilename:nil cacheAge:0 allowRangeRequests:YES];
[server addHandlerForMethod:@"GET"
pathRegex:@"/"
requestClass:[GCDWebServerRequest class]
processBlock:^GCDWebServerResponse *(GCDWebServerRequest request) {

**there is a my codes.

}];

[server startWithPort:self.CONSTANT_PORT bonjourName:@"test"];
```
