### ISSUE TITLE
Mutiple async download with webUploader

### ISSUE THREAD

**Issue by IgorMD** [swisspol/GCDWebServer#126]
Hello to everyone.
I faced a problem. I'm using GCDWebUploader and i try to to download files async. I iterate throw all my checkboxed files and call the function download the file but it download only last file :(.
Can you please help me ?

	$('input[type=checkbox]').each(function () {
			if (this.checked) {
								   var path = $(this).val()
								   setTimeout(function() {
											  window.location = "download?path=" + encodeURIComponent(path);
											  },0);
		   
					}
			});

**Comment by swisspol** [comment]
It looks like you are trying to customize the HTML / JavaScript of GCDWebUploader. This is not something I can provide support for unfortunately.

Try using the debugger and put breakpoints in `GCDWebUploader.m` to double-check what is sent by the webpage, then check your JavaScript code.
