### ISSUE TITLE
Query parameters ignored after the first one

### ISSUE THREAD

**Issue by tifroz** [swisspol/GCDWebServer#127]
I can't seem to get more than a single query parameter value out of any incoming request. Here is the code to reproduce:

```
[_webServer addDefaultHandlerForMethod:@"GET"
                            requestClass:[GCDWebServerRequest class]
                            processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {
                              ;
                              NSLog(@"URL=%@, query=%@", request.URL, request.query) ;
                              
                              return [GCDWebServerDataResponse responseWithHTML:@"<html><body><p>Hello World</p></body></html>"];
                              
                            }];
```
...now send a GET request with multiple query parameters
`curl http://10.0.1.7:8080/blah?param1=foo&param2=bar`

...and the NSLog statement will output this: 
```
[DEBUG] Connection on socket 10 processing request "GET /blah" with 92 bytes body
2015-01-24 23:47:59.967 GCDWebServer[7467:121512] URL=/blah?param1=foo -- http://10.0.1.7:8080/, query={
    param1 = foo;
}
``` 
param2 has gone missing from the URL *and* from the query dictionary!

Happy to look into a PR, especially if you can provide some initial guidance.

**Comment by swisspol** [comment]
Can you trace what is happening in `GCDWebServerParseURLEncodedForm()`?

**Comment by tifroz** [comment]
The queryString argument passed to  `GCDWebServerParseURLEncodedForm(queryString)`  is already missing the 2nd parameter (See GCDWebServerConnection's _readRequestHeaders() line 542)

In other words the problem seems to be happening upstream of `GCDWebServerParseURLEncodedForm()`.

Errr...I scanned some of the code in `GCDWebServerConnection` & saw a lot of low-level stuff I am not at all familiar with. It may not be such a great idea for me to offer to write a PR after all ...

**Comment by swisspol** [comment]
I just checked with your own code in the test mac app of the project and it works fine:
```
$ curl "http://localhost:8080/?foo=1&bar=2" ; echo ""
```
```
2015-01-25 10:00:05.913 GCDWebServer[87190:26875323] URL=/?foo=1&bar=2 -- http://localhost:8080/, query={
    bar = 2;
    foo = 1;
}
```

You're most likely not sending the right request with curl - which would be confirmed by the fact the query string arriving in `GCDWebServerParseURLEncodedForm()` doesn't have all the parameters either.

**Comment by tifroz** [comment]
Just tested the same. You are right I was missing quotes around the curl URL: my mistake & apologies for the trouble!
