### ISSUE TITLE
Ambiguous use of 'addDefaultHandlerForMethod'

### ISSUE THREAD

**Issue by tim-9red7** [swisspol/GCDWebServer#128]
Getting an ambiguous use of 'addDefaultHanderForMethod' error using the default Swift code in the read me.

**Comment by tim-9red7** [comment]
Switch the code from:
```
webServer.addDefaultHandlerForMethod("GET", requestClass: GCDWebServerRequest.self) { request in
            return GCDWebServerDataResponse(HTML:"<html><body><p>Hello World</p></body></html>")
        }
```

to this and it works:
```
webServer.addDefaultHandlerForMethod("GET", requestClass: GCDWebServerRequest.self, processBlock: {request in
            return GCDWebServerDataResponse(HTML:"<html><body><p>Hello World</p></body></html>")
        })
```

Is this ambiguity coming from the compiler not know which version on the method to call? Thanks for adding the async version by the way.

**Comment by swisspol** [comment]
Maybe, I don't know as I'm not familiar with Swift. Check out the compiler log it should provide more information.

In any case, I'll update the README with your change. Thanks!
