### ISSUE TITLE
Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/GCDWebServer#130]
Hello. 

I am receiving a build error when when including project via cocoapods beta 2 (for Swift)
Is GCDWebServer compatible with arm64?

Undefined symbols for architecture arm64:
  "_XLMinLogLevel", referenced from:

...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by swisspol** [comment]
GCDWebServer definitely supports arm64. Looks like you have https://github.com/swisspol/XLFacility in your project as well, so make sure XLFacility is fully included in the current target.

**Comment by nickvelloff** [comment]
Thanks. I’m just having real trouble with the Cocoapods beta with dependencies. It was working properly (GCDWebServer and XLFacility) until I added Alamofire and now there are all kinds of random errors. 

Thank you for all your work on this. Extremely helpful.

**Comment by nickvelloff** [comment]
If you happen to see anything here that stands out as obvious I would be in great debt:

Ld /Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Products/Debug-iphonesimulator/Pods/GCDWebServer.framework/GCDWebServer normal x86_64
    cd /Users/nick/Documents/repos/iOS/interaction/Share1/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=8.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.1.sdk -L/Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Products/Debug-iphonesimulator/Pods -F/Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Products/Debug-iphonesimulator/Pods -filelist /Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-GCDWebServer.build/Objects-normal/x86_64/GCDWebServer.LinkFileList -install_name @rpath/GCDWebServer.framework/GCDWebServer -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -lz -framework CFNetwork -framework MobileCoreServices -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=8.0 -framework CFNetwork -framework Foundation -framework MobileCoreServices -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Intermediates/Pods.build/Debug-iphonesimulator/Pods-GCDWebServer.build/Objects-normal/x86_64/GCDWebServer_dependency_info.dat -o /Users/nick/Library/Developer/Xcode/DerivedData/The_Grid-hjeirebggrzxxlelivxfwhkmehug/Build/Products/Debug-iphonesimulator/Pods/GCDWebServer.framework/GCDWebServer

Undefined symbols for architecture x86_64:
  "_XLMinLogLevel", referenced from:
      -[GCDWebServer dealloc] in GCDWebServer.o
      -[GCDWebServer _startBackgroundTask] in GCDWebServer.o
      ___36-[GCDWebServer _startBackgroundTask]_block_invoke in GCDWebServer.o
      -[GCDWebServer _didConnect] in GCDWebServer.o
      ___36-[GCDWebServer willStartConnection:]_block_invoke in GCDWebServer.o
      -[GCDWebServer _endBackgroundTask] in GCDWebServer.o
      -[GCDWebServer _didDisconnect] in GCDWebServer.o
      ...
  "_XLSharedFacility", referenced from:
      -[GCDWebServer dealloc] in GCDWebServer.o
      -[GCDWebServer _startBackgroundTask] in GCDWebServer.o
      ___36-[GCDWebServer _startBackgroundTask]_block_invoke in GCDWebServer.o
      -[GCDWebServer _didConnect] in GCDWebServer.o
      ___36-[GCDWebServer willStartConnection:]_block_invoke in GCDWebServer.o
      -[GCDWebServer _endBackgroundTask] in GCDWebServer.o
      -[GCDWebServer _didDisconnect] in GCDWebServer.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by swisspol** [comment]
Sorry I'm not really familiar with CocoaPods. In my experience, it's not a reliable package manager and its use is often a net negative (you spend more times working around its bug than beneficing from it). I would recommend just adding the third-party source code directly to your Xcode project. Good luck!

**Comment by nickvelloff** [comment]
Thanks. Back to submodules. Appreciate the response.
