### ISSUE TITLE
Crash when open the http URL on the main thread 

### ISSUE THREAD

**Issue by cloud-hot** [swisspol/GCDWebServer#131]
It seems that GCDWebServer can only run on the main thread, and if i run UIApplication.sharedApplication().openURL it will crash. Is there any solution for this issue? Thanks!

**Comment by swisspol** [comment]
GCDWebServer can be used on any thread. Be sure to read through the README to understand how to use it.

`openURL` is not an API from GCDWebServer so you must be having a different problem in your app.

**Comment by cloud-hot** [comment]
Hi swisspol, 

I init the GCDWebServer at the 

```Swift
        let webServer = GCDWebServer()
        
        webServer.addHandlerForMethod("GET", path: "/start", requestClass: GCDWebServerRequest.self, processBlock: {request in
            return GCDWebServerDataResponse(HTML:"<HTML><HEAD><title>Profile Install</title>"
               + "</HEAD><script> "
               + "function load() { window.location.href='http://localhost:8000/load/'; } "
               + "var int=self.setInterval(function(){load()},400); "
               + "</script><BODY></BODY></HTML>")
        })

        webServer.startWithPort(8000, bonjourName: nil)
```

And on one view controller using 

```Swift
UIApplication.sharedApplication().openURL(NSURL(string: "http://localhost:8000")!)
```

And once i run this iOS app the GCDWebServer will hang up  GWS_DCHECK(_options == nil) on this function:
```objc
- (void)dealloc {
  GWS_DCHECK(_connected == NO);
  GWS_DCHECK(_activeConnections == 0);
  GWS_DCHECK(_options == nil);  // The server can never be dealloc'ed while running because of the retain-cycle with the dispatch source
  GWS_DCHECK(_disconnectTimer == NULL);  // The server can never be dealloc'ed while the disconnect timer is pending because of the retain-cycle
  
#if !OS_OBJECT_USE_OBJC_RETAIN_RELEASE
  dispatch_release(_sourceGroup);
  dispatch_release(_syncQueue);
#endif
}
```

**Comment by swisspol** [comment]
I see. You need to retain the `GCDWebServer` instance after creating it or it won't live past the application-did-finish-launching function. Typically one would use an instance variable on the application delegate class.

Also opening the URL on the same device is unlikely to work correctly since the app is going to go in the background and be "frozen" by iOS: see the README.

**Comment by cloud-hot** [comment]
Thanks Swisspol, after retain the GCDWebServer instance the crash is disappeared. 

But i still did not get it working, i think the background running for GCDWebServer is the root cause for my problem. My objective is to download the mobile profile which should open the same device URL to complete. Like this link (http://stackoverflow.com/questions/2338035/installing-a-configuration-profile-on-iphone-programmatically/21014275#21014275), the CocoaHTTPServer should work for this problem. So i am wondering whether you will add this feature later or how to solve it for me using GCDWebServer?

**Comment by cloud-hot** [comment]
Hi Swisspol,

I mean that not using the GCDWebServer always under background which will be 'frozen' by iOS finally. just make it alive for a while and keep it still running under background to receive some request

**Comment by swisspol** [comment]
Try setting `GCDWebServerOption_AutomaticallySuspendInBackground` to `NO`:
- https://github.com/swisspol/GCDWebServer#gcdwebserver--background-mode-for-ios-apps
- https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.h#L181

**Comment by swisspol** [comment]
Note that this will only prevent GCDWebServer from automatically suspending itself, but your app will still be frozen by iOS unless you create a background task.

**Comment by cloud-hot** [comment]
Thanks Swisspol for your quickly response!

And i will try to set the GCDWebServerOption_AutomaticallySuspendInBackground to NO, your README is wonderful forgiving me not reading it before.

Do you mean that except i set the GCDWebServerOption_AutomaticallySuspendInBackground  to NO, i still need to create a background task at the same time? (My goal is just under background task about 1min and then my app will return to normal foreground)

**Comment by swisspol** [comment]
> Do you mean that except i set the GCDWebServerOption_AutomaticallySuspendInBackground to NO, i still need to create a background task at the same time?

Yes.

**Comment by cloud-hot** [comment]
Hi Swisspol,

I saw in the README:

```
If the app is still in the background when the last HTTP connection is closed, GCDWebServer will suspend itself and stop accepting new connections as if you had called -stop (this behavior can be disabled with the GCDWebServerOption_AutomaticallySuspendInBackground option)
```

This means if i set the GCDWebServerOption_AutomaticallySuspendInBackground to NO, the GCDWebServer background task will still keep running even the HTTP connection is closed. Does this mean even i do not create a extra background task it will still not be frozen by iOS (unless the 10min time is over)?

**Comment by swisspol** [comment]
GCDWebServer only creates a background task while processing an HTTP request to prevent the app being frozen before GCDWebServer has sent the response the client. GCDWebServer won't keep the app alive for you. You need your own background task for that.
