### ISSUE TITLE
Xcode 6.1.1 compile warning

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/GCDWebServer#132]
GDCTelnetConnection.m
Lines 164, 167

![screenshot 2015-02-03 15 41 18](https://cloud.githubusercontent.com/assets/885369/6033545/2298c096-abbb-11e4-9aad-a5ff4e26ee7e.png)

Thanks!

**Comment by nickvelloff** [comment]
Replacing with nil resolved the error btw.

**Comment by swisspol** [comment]
Ah good catch. Can you right click on the warning in the issue navigator and show the corresponding log entry: I wonder what warning setting triggers this?

**Comment by swisspol** [comment]
https://github.com/swisspol/GCDTelnetServer/commit/9a127bdf35308f6c2dc768b95cdf0d73a0810d24

**Comment by swisspol** [comment]
Because this "issue" is in a subproject, it will picked up next time I upgrade XLFacility to the latest GCDTelnetServer version.

**Comment by nickvelloff** [comment]
I think this is what you want:

/Users/nick/Documents/repos/iOS/interaction/Share1/Pods/XLFacility/GCDTelnetServer/GCDTelnetServer/GCDTelnetConnection.m:164:12: Initialization of pointer of type 'NSString *' to null from a constant boolean expression

Thanks!

**Comment by swisspol** [comment]
![image](https://cloud.githubusercontent.com/assets/627915/6045207/3e8ac97e-ac4d-11e4-8b07-45989c083d5c.png)

This is actually what I'm looking for: you can see the warning name like `-Wunused-variable` here.

**Comment by nickvelloff** [comment]
Ah ha. ok attaching!
![screen shot 2015-02-18 at 4 27 28 pm](https://cloud.githubusercontent.com/assets/885369/6260956/1ee4bd66-b78b-11e4-9c59-fcfbd07c710d.png)

**Comment by nickvelloff** [comment]
Sorry it took so long to respond I actually completely missed your comment.

**Comment by swisspol** [comment]
No problem, thanks for the update

**Comment by nickvelloff** [comment]
Hi! Was this issue resolved?

**Comment by swisspol** [comment]
Should be now at version 1.5.6.

**Comment by nickvelloff** [comment]
Thank you it worked!
