### ISSUE TITLE
Is it possible to run GCDWebUploader in background for long running tasks?

### ISSUE THREAD

**Issue by Vikramjeet-Singh** [swisspol/GCDWebServer#133]
Hi

I am using GCDWebUploader and my app implements VOIP so it runs in background for long period of time. I was wondering if there is a way for GCDWebUploader to run in the background mode for those long running processes. I tried setting the     
   
     _suspendInBackground = [_GetOption(_options, GCDWebServerOption_AutomaticallySuspendInBackground, @NO) boolValue];

It works fine for 180 seconds and after that it throws following error:

    [ERROR] Bonjour registration error -72000 (domain 10)

And at this time, even if the app is brought in foreground, GCDWebUploader/Server does not work.

Any idea if its possible for me to do what I am trying to do? If yes, then I would really appreciate some guidance/help as to how to achieve that.

Thanks
Vik

**Comment by swisspol** [comment]
GCDWebServer doesn't "run in the background", it just runs. All it does it is trying to prevent the app from being frozen while an HTTP request is being served and try to auto-restart if the app was frozen and then unfrozen - see README.

If you disable `GCDWebServerOption_AutomaticallySuspendInBackground` then GCDWebServer will never auto-stop when the app goes in the background and the last request has been served, which is likely what you want. However if the app is still frozen by the OS later on, all bets are off. You will have to restart the server manually.

GCDWebServer is just a fancy wrapper around a TCP listening socket, so as long as the OS doesn't kill the socket, you'll be fine. I don't know how Bonjour behaves for VOIP apps in background, it might not work, if so just disable it.

You could also try leaving `GCDWebServerOption_AutomaticallySuspendInBackground` enabled but setting `GCDWebServerOption_ConnectedStateCoalescingInterval` to a very high value.
