### ISSUE TITLE
url access picture fil with local web server 

### ISSUE THREAD

**Issue by aitbelarbi** [swisspol/GCDWebServer#135]
My app using GCDWebServer I get a photo from my iPhone album by using AssetsLibrary and I store them in NSDocumentDirectory. I just want to get access Url to this photo to show them in a web page.

There is my code :

[_webServer addHandlerForMethod:@"POST"
                              path:@"/"
                      requestClass:[GCDWebServerURLEncodedFormRequest class]
                      processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {

                          ALAsset *asset = [self.arrayPictures objectAtIndex:0];
                          ALAssetRepresentation *rep = [asset defaultRepresentation];
                          CGImageRef iref = [rep fullResolutionImage];
                          UIImage *thumbnail = [UIImage imageWithCGImage:iref];
                          NSString* path ;
                          if (thumbnail != nil)
                          {
                              NSArray *paths = NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES);
                              NSString *documentsDirectory = [paths objectAtIndex:0];
                               path =  [[NSString alloc] initWithString:[documentsDirectory stringByAppendingPathComponent:@"test.png"]];
                              NSData* data = UIImagePNGRepresentation(thumbnail);
                              [data writeToFile:path atomically:YES];
                          }

                          NSURL *url = [NSURL fileURLWithPath:path];
                          NSString* html = [NSString stringWithFormat:@"<html><body><img src=\"%@\" width=\"400\" height=\"500\"/></body></html>", url];
                          return [GCDWebServerDataResponse responseWithHTML:html];

                      }];

**Comment by swisspol** [comment]
You are using a `POST` and a `GCDWebServerURLEncodedFormRequest` class: are you sure this is what you want? I suggest you go through the README and `main.m` from the Mac test app in the project to understand how to use GCDWebServer.

**Comment by KevinMac123** [comment]
Hey have you got any solution?

**Comment by Bigscaltest** [comment]
Hey have you got any solution?

I have same issue while displaying image in web.

I have saved image in document directory.

**Comment by rangav** [comment]
Hi

Its a very late reply, I think you should return image url as below

{serverurl}/image_url.jpg not path to documents folder.

exam serverurl is http://192.168.0.1

and you should start your server from the documents folder. Hope you got it

**Comment by zhangxueyang** [comment]
https://stackoverflow.com/questions/31382070/convert-ios-photo-album-path-url-same-like-as-document-directory-file-path/31778726#31778726
No sandbox is read directly.
See this still don't know how to do it?
