### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by thebnich** [swisspol/GCDWebServer#136]
Have you considered adding support for Carthage (<a href="https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework">documentation here</a>)?

**Comment by swisspol** [comment]
No, I wasn't aware of this system. Good to see some competition for Cocoa Pods as it leaves a lot of room to be desired.

I don't have plans to add support for Carthage though as it seems still early looking at the number of stars, and it's one of those things that requires on-going maintenance I can only assume.
