### ISSUE TITLE
webServerDidCompleteBonjourRegistration callback fails when reactivating Wifi - solved

### ISSUE THREAD

**Issue by lucaji** [swisspol/GCDWebServer#137]
Hi, when I switch off and back on the wifi connection (especially on iPhone - this issue did not occur on iPad, afaik) on the first run of my app, this callback fails to get called.

I raised the timeout (initially to 1.0seconds) up to 5.0 seconds on the _NetServiceRegisterCallback

```objectivec
static void _NetServiceRegisterCallBack(CFNetServiceRef service, CFStreamError* error, void* info) {
  GWS_DCHECK([NSThread isMainThread]);
  @autoreleasepool {
    if (error->error) {
      GWS_LOG_ERROR(@"Bonjour registration error %i (domain %i)", (int)error->error, (int)error->domain);
    } else {
      GCDWebServer* server = (__bridge GCDWebServer*)info;
      GWS_LOG_VERBOSE(@"Bonjour registration complete for %@", [server class]);
      CFNetServiceResolveWithTimeout(server->_resolutionService, 5.0, NULL);
    }
  }
}
```

This solved my issue. Thank you, man your GcdWebserver works like charm!
Cheers, Luca

**Comment by swisspol** [comment]
If you leave the timeout set to 1.0, is `_NetServiceResolveCallBack()` called at all? This is what eventually calls `-webServerDidCompleteBonjourRegistration:`. And if so, you should see an error in the log if resolution has failed. Please provide this.

**Comment by lucaji** [comment]
just double checked now to confirm that _NetServiceResolveCallBack() does NOT get called if timeout is 1.0 sec on iPhone 5c iOS 8.1.3. But it DOES get called on an iPad Mini3.

**Comment by swisspol** [comment]
This is very puzzling. I'll keep this around until other people report an issue, so we have a better idea of the proper fix.

**Comment by swisspol** [comment]
I'm going to close this issue. Nobody else ever reported this issue and I've never observed it myself and I don't want to do a fix for something that might not actually be truly a GCDWebServer problem or by using a random delay value.
