### ISSUE TITLE
can GCDWebserver process/receive HTTP requests while in background mode?

### ISSUE THREAD

**Issue by Vikramjeet-Singh** [swisspol/GCDWebServer#138]
Hi

My app is using VoIP and it makes sure that GCDWebServer is running in background mode as I did set the 

    AutomaticallySuspendInBackgroundMode = "No". 

I'm also checking GCDWebserver's "isRunning" property to make sure server is running. Now what I'm interested in knowing if a client sends the HTTP request to the server when it's in background mode (and running), then can it process the request or it has to be in the foreground to do that?

Thanks
Vik

**Comment by swisspol** [comment]
It makes no difference to GCDWebServer: as long as the app is running, it's running as well. However GCDWebServer can only process HTTP requests if it receives them, and this requires its listening TCP socket to be "working", which iOS controls when the app goes in background, not GCDWebServer.

I have no idea what iOS does when a VOIP app goes in background for non-VOIP listening sockets. If iOS still closes them, then GCDWebServer won't work. Sorry, I can't help much more, you'll just have to test all this and if needed track inside GCDWebServer source code if the HTTP requests are received.
