### ISSUE TITLE
Base url null

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/GCDWebServer#140]
Hello again!

Any idea why all of a sudden my base url is null when starting things up?
00:00:00.186 [DEBUG    ]> Did open IPv4 listening socket 9
00:00:00.186 [DEBUG    ]> Did open IPv6 listening socket 10
00:00:00.187 [INFO     ]> GCDWebServer started on port 8080 and reachable at (null)

I do get and can access the Bonjour address:
00:00:01.311 [VERBOSE  ]> Bonjour registration complete for GCDWebServer
00:00:01.445 [INFO     ]> GCDWebServer now reachable at http://Nicholass-MacBook-Pro.local:8080/

This is how I fire it up:
```swift
self.webServer?.addGETHandlerForBasePath("/", directoryPath: dist, indexFilename: nil, cacheAge: 3600, allowRangeRequests: true)
        webServer?.start()
        AppModel.sharedInstance.baseServerURL = self.webServer?.serverURL
```
Thanks for any help.

**Comment by nickvelloff** [comment]
Maybe it is the network I'm on currently? Should I explicitly set the local ip (would this even work)?

**Comment by swisspol** [comment]
This would mean your device doesn't have an internet connection so it had
no IP address. You can trace it in the debugger to understand exactly what
is happening during the server start.

**Comment by nickvelloff** [comment]
I see. Because I'm serving a local bundle I would still like it to serve what it can. I'm having the Web view gracefully handle the lack of connection. 
How would I still connect?

**Comment by nickvelloff** [comment]
In other words is there a local address that can be used if there is no connection?

**Comment by swisspol** [comment]
If you connect locally, always use http://localhost:8080 as it's guaranteed
to work.

**Comment by nickvelloff** [comment]
Excellent thanks.
