### ISSUE TITLE
Upload Directory

### ISSUE THREAD

**Issue by toto263** [swisspol/GCDWebServer#141]
I will appreciate if "Upload Directory" button exist for GCDWebUploader.
When choosing a folder by pressing Upload Directory button, all files in the folder and sub-folders is uploaded.
It would be better if uploading folder by drag&drop is also supported.
Thank you for reading.

**Comment by swisspol** [comment]
Thanks for the suggestion! I wondered about it myself, but it's unfortunately not easy to do, so I'm not sure I'll ever get to it.
