### ISSUE TITLE
Add support for bonjour TXT Record

### ISSUE THREAD

**Issue by lucaji** [swisspol/GCDWebServer#142]
In my project I added a snippet in the main code to support TXT Record change:

    -(void)updateServerTXTRecordWithNSDictionary:(NSDictionary*)txtDict
    {
         BOOL result = CFNetServiceSetTXTData(_registrationService, CFNetServiceCreateTXTDataWithDictionary(kCFAllocatorDefault, (__bridge CFDictionaryRef)txtDict));
        if (result)
            (...)
     }

I thought be useful to share it because I made some research and found outdated resources about TXT records.

**Comment by swisspol** [comment]
Thanks for sharing. It's a very edge case though so I won't add this to the GCDWebServer project, sorry.
