### ISSUE TITLE
Crash when entering background mode (Swift app)

### ISSUE THREAD

**Issue by julien-c** [swisspol/GCDWebServer#143]
Hi,

My Swift app crashes when tapping the Home button. (`Xcode 6.1.1`)

Here's the crash report:

![screenshot 2015-02-26 a 18 13 28](https://cloud.githubusercontent.com/assets/326577/6397199/721e21a8-bde3-11e4-8788-a7d3a856ef4f.png)

My app is just doing:

```swift
func setupServer() {
        let webRoot = NSBundle.mainBundle().resourcePath?.stringByAppendingPathComponent("www")
        let webServer = GCDWebServer()
        GCDWebServer.setLogLevel(5)
        webServer.addGETHandlerForBasePath("/", directoryPath: webRoot, indexFilename: "index.html", cacheAge: 0, allowRangeRequests: true)
        webServer.startWithPort(self.port, bonjourName: nil)
    }
```

Any idea what's happening?

**Comment by swisspol** [comment]
You're not keeping the GCDWebServer instance around.

**Comment by julien-c** [comment]
You're right. Thanks!

**Comment by karnakar** [comment]
@swisspol 

I'm facing the same issue, what do you mean by keeping the instance around
