### ISSUE TITLE
Call -webServerDidStop: delegate method immediately when app goes in background

### ISSUE THREAD

**Issue by swisspol** [swisspol/GCDWebServer#144]
Right now the app can be frozen and the call will happen on wake up.

**Comment by chenjohney** [comment]
I just fixed it.just set option "GCDWebServerOption_AutomaticallySuspendInBackground" to "NO".like this:
NSMutableDictionary* options = [NSMutableDictionary dictionary];
    [options setObject:[NSNumber numberWithInteger:80] forKey:GCDWebServerOption_Port];
    [options setValue:@"" forKey:GCDWebServerOption_BonjourName];
    [options setValue:@NO forKey:GCDWebServerOption_AutomaticallySuspendInBackground];
    [_webServer startWithOptions:options error:NULL];

As api said,the GCDWebServerOption_AutomaticallySuspendInBackground set to YES default,so you can custom to set it by call startWithOption.Wish can help.

**Comment by Maqix** [comment]
Hi, @swisspol , as you can see there are an issue with the Ionic WKWebView that seems to be related with this issue, what are your thoughts?
