### ISSUE TITLE
How can I direct access?

### ISSUE THREAD

**Issue by yuchin067** [swisspol/GCDWebServer#145]
I want to try direct link video or music file to play on browser.
I known the GCDWebServer provider handle about "list","download","upload","move","delete","create" operating.
I try download to link.(ex. http://x.x.x.x/download?path=/mymusic.mp3).
It will download the file directly like its function name.
How can I direct to link?
Thank you.

**Comment by swisspol** [comment]
`GCDWebUploader` is not intended to be hacked around like this. So you either need to modify its source code or just use a plain `GCDWebServer` with a static web site like this:
https://github.com/swisspol/GCDWebServer#serving-a-static-website

**Comment by yuchin067** [comment]
Thank you for your reply.
I used http server is run in iPhone and I change to use GCDWebServer, but I can't find the function like:
- (BOOL)runWithPort:(NSUInteger)port

In the GCDWebServer.m, I find the function:
- (BOOL)runWithPort:(NSUInteger)port bonjourName:(NSString*)name 
The code is seem not to be used in iOS, isn't it?(#if !TARGET_OS_IPHONE)
Thank you.

**Comment by swisspol** [comment]
Use `-startWithPort:...`. Be sure to read the entire README file before starting to use GCDWebServer:
https://github.com/swisspol/GCDWebServer#hello-world

**Comment by yuchin067** [comment]
I got it and I can run in static website now.
Thank you very much for help.
