### ISSUE TITLE
Uploading music file from the device library

### ISSUE THREAD

**Issue by Sifoon** [swisspol/GCDWebServer#146]
Re hello Pol
like i said i want to upload music file from the iPhone library and i used MPMediaPickerController
and the delegate method didPickMediaItem that returns MPMediaItemCollection were we can find 
all the information of the picked music item ( title , album ... even the URL of the item) but the problem 
i can not find the Path for this item so i can not use the method of  GCDWebDavServer 
    _davServer = [[GCDWebDAVServer alloc]  initWithUploadDirectory:  .....  Path ..l];
i'm asking if there is a methed like 
    _davServer = [[GCDWebDAVServer alloc] initWithData : ...];
or     _davServer = [[GCDWebDAVServer alloc]  initWithURL : ...];
od somthing like that .
thanks a lot 
Good continuation

**Comment by swisspol** [comment]
There's no such method: `GCDWebDAVServer` requires the use of a target folder. You would need to use a regular `GCDWebServer` instance with handlers to download the files.

**Comment by Sifoon** [comment]
i already tried to use the regular GCDWebServer 
and i found a solution to upload a track of 10second but when i trie to upload a hole 
music item with 3min in the debug console i found broken pipe socket ...
and there is nothing in the browser so i think that the size of the music file can not be uploaded 
have you any idea to fixe that 
that's the method i tried after converting the music item to NSDATA: 
  _webServer = [[GCDWebServer alloc] init];
                    
                     //Add a handler to respond to GET requests on any URL
                     [_webServer addDefaultHandlerForMethod:@"GET"
                                              requestClass:[GCDWebServerRequest class]
                                processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {
                                                            return [GCDWebServerDataResponse responseWithData:_MusicConvertedToData 
contentType:@"audio/wav" ];
                                               }];
              
                    
                    
                    
                     // Start server on port 8082
                    [_webServer startWithPort:8082 bonjourName:nil];
                  NSLog(@"Visit %@ in your web browser", _webServer.serverURL);


With that function i already uploaded a music file of 10 sec

**Comment by swisspol** [comment]
On iOS, GCDWebServer handles files up to 2 GB (or maybe 4 GB I don't remember) with no problems. Maybe you're not keeping the server around or you're putting the app in the background and it's getting frozen by iOS... Check the log of your app in Xcode: GCDWebServer logs almost everything that is happening.

**Comment by Sifoon** [comment]
thanks for your help 
i did it
