### ISSUE TITLE
Why use GWS_DCHECK(_options == nil) when adding a handler?

### ISSUE THREAD

**Issue by davidchiles** [swisspol/GCDWebServer#147]
Is the purpose of [this check](https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.m#L351) to ensure that a handler cannot be added once the server is started?

While testing this works:

```obj-c
self.server = [[GCDWebServer alloc] init];
[self.server startWithOptions:nil error:&error];

//some time goes by
[self.server addHandlerForMethod:@"GET" path:@"/" requestClass:[GCDWebServerRequest class] processBlock:^GCDWebServerResponse *(GCDWebServerRequest *request) {
        return [[GCDWebServerResponse alloc] initWithStatusCode:200];
    }];
```

but this fails:

```obj-c
self.server = [[GCDWebServer alloc] init];
[self.server startWithOptions:@{GCDWebServerOption_Port:9090} error:&error];

//some time goes by
[self.server addHandlerForMethod:@"GET" path:@"/" requestClass:[GCDWebServerRequest class] processBlock:^GCDWebServerResponse *(GCDWebServerRequest *request) {
        return [[GCDWebServerResponse alloc] initWithStatusCode:200];
    }];
```

It seems strange that adding options changes whether you can add a handler once the server is running.

**Comment by swisspol** [comment]
`_options` being non-NULL is simply a proxy for the server being in running-like state (which doesn't mean truly running - see iOS background mode in README).

**Comment by davidchiles** [comment]
But if you start a server with `nil` options it's not really a proxy, right? Are you supposed to add handlers after the server is running?

**Comment by swisspol** [comment]
You can't start with nil options. Adding handlers while the server is running is not supported either.
