### ISSUE TITLE
Does GCDWebServer support the webserver server its own APP

### ISSUE THREAD

**Issue by cloud-hot** [swisspol/GCDWebServer#149]
Hi swisspol,

My APP requirement is that:
1. In my APP i need to install a WIFI profile which should be only through safari (apple limited this method), so my method is that using the GCDWebServer to setup a local webserver which is used to host the WIFI profile, when the APP want to install a WIFI profile it will use this API
``` Swift
UIApplication.sharedApplication().openURL
```
to open URL: http://localhost/profile which is hosted by GCDWebServer.

As you know when the APP open this URL the APP will go to background, and i have also setup a background task to prevent the APP be frozen and make GCDWebServer not automatically frozen with setting GCDWebServerOption_AutomaticallySuspendInBackground to NO. Now i have test that the GCDWebServer works well under background (through Mac safari access the URL). But when i test it within APP it will not work well, after click the URL it will present the safari and then it will return back to APP quickly. 

So i am wondering whether GCDWebServer support hosting its own APP?

Thanks!

**Comment by swisspol** [comment]
Sorry, I have no idea what you mean. GCDWebServer is just a web server. You've verified the web server is still working while the iOS app is in background, so from this point, everything else is the responsibility of your app and iOS. This is orthogonal from what GCDWebServer can or cannot do.

**Comment by cloud-hot** [comment]
Hi Swisspol,

I verified the web server working while the iOS app is in background under the situation of APP <-> PC, but i am wondering whether the web server also working well under APP-A <-> APP-A,  although i am not sure whether there is a difference between those two situation

**Comment by swisspol** [comment]
Check the log of GCDWebServer it will tell you exactly what it's doing. You can also use the debugger to put breakpoints inside GCDWebServer and figure out what exactly is happening.
