### ISSUE TITLE
Bind to localhost

### ISSUE THREAD

**Issue by i386** [swisspol/GCDWebServer#15]
Is there any way I can bind to 127.0.0.1 only?

Loving GCDWebserver so far!

**Comment by daisylassie** [comment]
great enhancement, thanks

**Comment by hjalmarsn** [comment]
How exactly would i start a server only accessible through localhost?
_webServer.startWithOptions(["BindToLocalhost":true], error: &error)?
And then connect with "webviewSurvey.loadRequest(NSURLRequest(URL: NSURL(string: "localhost")!))"? I can't get that to work

**Comment by onderweg** [comment]
This worked for me in Swift:

```Swift
let webServer = GCDWebServer() // Note: needs libz.dylib
        
webServer.startWithOptions([
    "Port": port,
    "BindToLocalhost": true 
    ] as NSDictionary, error: nil);
```

**Comment by hjalmarsn** [comment]
Thanks @onderweg! How did you get it to connect then? set the url to "localhost" or 127.0.0.1?
Thanks again for the quick reply.

**Comment by onderweg** [comment]
Both `localhost` and `127.0.0.1` work for me.
