### ISSUE TITLE
GCDWebServerConnection: IPv6, IPv4

### ISSUE THREAD

**Issue by alex-v1981** [swisspol/GCDWebServer#153]
I implemented class GCDWebServerConnection and method
- (BOOL)open;

I got IPv6 request (property usingIPv6 = YES). But I want get information about IPv4 of this request.
How to do it in this case?

**Comment by swisspol** [comment]
If the connection is IPv6, then you can't get information about IPv4. The connection can only be IPv4 or IPv6, it can't be both. Try connecting to GCDWebServer using an IPv4 connection (you can force IPv4 by using an IPv4 address when connecting to the server e.g. `192.168.1.15` instead of `my-server.local`).

**Comment by alex-v1981** [comment]
There is a strange situation. I connect to the webDAV server (GCDWebDAVServer) via Bonjour address: http://ipad-alex-v.local/
I send two identical request (PROPFIND) to the server and the server creates two GCDWebServerConnection with IPv6 and IPv4.
Why do they have different addresses?

**Comment by swisspol** [comment]
I have no idea, sorry.

**Comment by alex-v1981** [comment]
I found a solution to this problem. I need to prevent a server listening IPv6 socket. Let the server listens only IPv4 socket. I tried disabling the IPv6 socket in the method:
- (BOOL)_start:(NSError**)error
of class GCDWebServer.

In this case, I have come only IPv4 requests (no IPv6).

Could you add to the GCDWebServer class option to disable listen IPv6 socket?

**Comment by swisspol** [comment]
You should really write code that works for both IPv4 and IPv6. The fact that GCDWebServer supports IPv6 is not a "bug" :) You can always file a new issue asking for an option to enable / disable IPv4 and IPv6 and I may have a look later.
