### ISSUE TITLE
Weird value in remote address string

### ISSUE THREAD

**Issue by matthewcheok** [swisspol/GCDWebServer#156]
When printing the remoteAddressString to console I get weird unicode values such as ":Ä;o" and "†{ò:p{ò". Any idea what's wrong?

**Comment by swisspol** [comment]
No and I never heard of such a problem. Try tracing the code in the debugger.

**Comment by swisspol** [comment]
Did you figure out what the problem was?

**Comment by matthewcheok** [comment]
It looks like an intermittent problem depending on the wifi network connected to. I'll continue to monitor this. Thanks
