### ISSUE TITLE
GCDWebDAVServer: PROPFIND request (Depth: 1)

### ISSUE THREAD

**Issue by alex-v1981** [swisspol/GCDWebServer#157]
When I send the PROPFIND request to the GCDWebDAVServer server with the HTTP header "Depth: 1" and the path to an empty folder, then I get an empty result. Other webDAV servers give information about this empty folder in this case. Whether it is possible to fix something?

**Comment by swisspol** [comment]
See https://github.com/swisspol/GCDWebServer/blob/master/GCDWebDAVServer/GCDWebDAVServer.m#L108

The WebDAV does not define what `GET` on a collection should return so returning nothing is completely fine:
http://webdav.org/specs/rfc4918.html#rfc.section.9.4
