### ISSUE TITLE
GWS_DCHECK check not passed

### ISSUE THREAD

**Issue by anatoliyv** [swisspol/GCDWebServer#158]
Hello

I need to download mp4 videos from media server and simultaneously put this data to local cache folder and send to local video player. All works fine when mp4 files are small but when it’s large I can not wait and should send data to player by small peaces.

I developed something like a proxy where in **addDefaultHandlerForMethod(“GET” …. asyncProcessBlock ….)** I send request to my media server using NSURLConnection and using delegate methods get NSData. I storing completionBlock locally and call it every time I get some NSData from NSURLConnectionDelegate with **GCDWebServerDataResponse()**

But server asserts on this GWS_DCHECK in my solution on second piece of data (first works fine).

```
- (void)_finishProcessingRequest:(GCDWebServerResponse*)response {
  GWS_DCHECK(_responseMessage == NULL);
```

May be you can describe me what I’m doing wrong and where I should look?

Thanks in advice!

**Comment by swisspol** [comment]
Make sure your async handler is written correctly: check the README and the docs in the headers for handlers.
