### ISSUE TITLE
Create form from Swift

### ISSUE THREAD

**Issue by tim-9red7** [swisspol/GCDWebServer#162]
Wondering if anyone has gotten form processing working from Swift. Taking a cue from the form on the README it says to return the following...
```
 return [GCDWebServerDataResponse responseWithHTML:html];
```
So I thought I could simply use the following from Swift...
```
return GCDWebServerDataResponse(HTML: html)
```
This is causing an "Missing argument for parameter 'contentType' in call" error. Ideas?

**Comment by swisspol** [comment]
It definitely works in ObjC as can be seen in GCDWebServer code itself:
https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.m#L925

Did you try using `[GCDWebServerDataResponse -initWithHTML:]` instead? Are you sure you are including the required headers i.e. `GCDWebServerDataResponse.h`?

I don't really know Swift so I can't comment - you might be better of asking on StackOverflow.

**Comment by tim-9red7** [comment]
Will do. Felt bad asking here, but thanks for the cue. Thanks for the hard work on the project.
