### ISSUE TITLE
RTMP Support

### ISSUE THREAD

**Issue by loretoparisi** [swisspol/GCDWebServer#163]
Any plan to support RTMP?

**Comment by swisspol** [comment]
No, that would not be part of GCDWebServer's "mission".

**Comment by floriangbh** [comment]
Hello @loretoparisi , did you find a solution to create RTMP server localy for iOS ?

**Comment by loretoparisi** [comment]
@floriangbh see here https://github.com/jgh-/VideoCore-Inactive/issues/131
