### ISSUE TITLE
Support for Web Sockets

### ISSUE THREAD

**Issue by joeljfischer** [swisspol/GCDWebServer#164]
I would love to see an [implementation of RFC 6455](https://tools.ietf.org/html/rfc6455) as an ability to open web sockets from a served web page. Do you have any thoughts on why that may or may not be possible?

**Comment by swisspol** [comment]
I haven't really thought about it, but you can review the README and its architecture section along with the RFC to see if it can be "hacked" together. GCDWebServer does support streaming data in a response, and up to a point streaming data in a request.

**Comment by swisspol** [comment]
I have no plans at this time to add support for Web Sockets in GCDWebServer.

**Comment by arminsal1** [comment]
@joeljfischer Did you find any solution for what you're trying to do?
