### ISSUE TITLE
Bind to localhost only, but serverURL shows my IP

### ISSUE THREAD

**Issue by EgoAleSum** [swisspol/GCDWebServer#165]
I'm starting a web server with the option `GCDWebServerOption_BindToLocalhost` set to `@YES`.

When I do:

    NSLog(@"Started HTTP Server: %@ ", self.webServer.serverURL);

however, the address I see is `http://172.18.0.95:8181/` (that's my IP in the LAN). GCDWebServer's logs show my IP too, instead of localhost.

Please note that, despite seeing the wrong address in the `serverURL` property, the app behaves as expected, and it does not accept any connection that is not from localhost (that is: `http://localhost:8181/` works and `http://172.18.0.95:8181/` doesn't)

**Comment by swisspol** [comment]
That's expected behavior right now, -serverURL just calls `GCDWebServerGetPrimaryIPAddress()`.

**Comment by EgoAleSum** [comment]
I understand. However, if I'm binding to localhost, I'd expect to receive from serverURL an address I can directly use in my app.

To be clear: it's not a big deal. I can just create a NSString with `http://localhost:` and append the port number... But it'd be nice to receive an address from the library that can directly be used.

**Comment by swisspol** [comment]
Fixed in 0a9d3105fc1c6e2f4492114bbb8b12686a5397c7
