### ISSUE TITLE
Support for updating TXT record

### ISSUE THREAD

**Issue by tomodyne** [swisspol/GCDWebServer#167]
Are there any plans to add a method to update the txt record of NSNetService such that Bonjour can notify clients about server changes? I'm asking for something similar as implemented in CocoaHTTPServer.

**Comment by swisspol** [comment]
This sounds similar to #142. There are no plans to add such a feature. What you can do is not use the built-in Bonjour support for GCDWebServer but instead use your own where you would have full control. Or can always modify the source of course.
