### ISSUE TITLE
Safest way to ensure server responds only to local (localhost) requests

### ISSUE THREAD

**Issue by nickvelloff** [swisspol/GCDWebServer#168]
Hello again.
Getting close to all submission and I want to ensure only local requests will get responded to. Is there a safe way to achieve this?

Thanks!

**Comment by swisspol** [comment]
There's an option for that in the header :)

**Comment by nickvelloff** [comment]
Indeed there is. GCDWebServerOption_BindToLocalhost. Thanks. Check out thegrid.io and let me know if you are interested in a very early beta invite.

**Comment by swisspol** [comment]
Looks pretty interesting and ambitious - sure feel free to share an invite to pol (_) mac.com.

PS: You might wanna try out my latest app too :) http://gitup.co
