### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by matejkramny** [swisspol/GCDWebServer#173]
1. https://github.com/swisspol/GCDWebServer#serving-a-static-website is inaccurate. There is no method `runWithPort:`
2. Mention `libz` requirement

Thanks

**Comment by swisspol** [comment]
Thanks for the feedback, I tweaked the README. Note that `-runWithPort:bonjourName:` exists but for OS X only (on iOS it wouldn't make sense), you have to use `-startWithPort:bonjourName:` instead.

**Comment by matejkramny** [comment]
oh right.

Thanks for clarifying
