### ISSUE TITLE
Request not processed when app goes into background (AutomaticallySuspendInBackground option is set to NO)

### ISSUE THREAD

**Issue by BhuvaneshShan** [swisspol/GCDWebServer#176]
I am creating an app that needs to accept incoming http requests even if the app is in the background. In iOS Simulator, 200 OK response is sent when the app is sent to background by pressing Home button. But in iPhones, even when AutomaticallySuspendInBackground option is set to NO, the GCDWebServer doesn't respond when requests are sent while the app is in background. 
I use  the following code.

    var webServer : GCDWebServer?

    func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
       
        webServer = GCDWebServer()
        //Handler to process GET requests
        webServer!.addDefaultHandlerForMethod(Constants.Labels.get, requestClass: GCDWebServerRequest.self, processBlock: {request in
            let req :String = String(stringInterpolationSegment: request)
            if req.hasPrefix(Constants.Api.isAlive){
                println("isalive received")
            }
            return GCDWebServerResponse(statusCode: 200)
        })
        
        var option = ["AutomaticallySuspendInBackground":"NO","Port":8060,"BonjourName":"BPSMobileServer"]
        var err : NSError?
        if webServer!.startWithOptions(option as [NSObject : AnyObject], error: &err){
            println("Server Started in port \(webServer!.port)")
        }else{
            println("Failed to start server")
        }
        
        println("Visit \(webServer!.serverURL) in your web browser")
        return true
    }

**Comment by swisspol** [comment]
This cannot be done in a reliable way as iOS doesn't allow that (except for VOIP apps but only for voice, not a random web server).

See https://github.com/swisspol/GCDWebServer#gcdwebserver--background-mode-for-ios-apps and https://developer.apple.com/library/ios/technotes/tn2277/_index.html.

Also see #133.

**Comment by BhuvaneshShan** [comment]
Thanks for the quick response! :)
