### ISSUE TITLE
support for cross domain requests

### ISSUE THREAD

**Issue by iurimatias** [swisspol/GCDWebServer#177]
Is there a way to allow cross domain requests? I have attempted response.setValue("*", forAdditionalHeader: "Access-Control-Allow-Origin") with no success, it seems the error is immediately sent

**Comment by swisspol** [comment]
Cross-domain requests are unrelated to the HTTP server itself: it's all about the setting the headers correctly and implementing the correct verbs (I don't think `GET` is enough, you need another one too). You'll have to read the spec on them and make sure your handlers and headers are correct, then use the Chrome web inspector to look at HTTP requests coming from the browser and see which ones are not working.
