### ISSUE TITLE
GCDWebServer.m dealloc throws SIGABRT

### ISSUE THREAD

**Issue by DaniilHarik** [swisspol/GCDWebServer#178]
Hello,

I'm using latest Xcode 6.3.1 and iOS 8.3 and I'm starting my server like this (in the AppDelegate) :         

        let webServer = GCDWebServer();
        webServer.addGETHandlerForBasePath("/", directoryPath:NSBundle.mainBundle().resourcePath! + "/www/", indexFilename: "index.html", cacheAge: 3600, allowRangeRequests: true);
        webServer.startWithPort(8080, bonjourName: "test");

When ever my app goes to background, I'm getting signal SIGABRT in GCDWebServer.m (void)dealloc at the following row: 

        GWS_DCHECK(_options == nil);

Is this an issue or I'm just missing some parameters when I start the server?

Thank You!

**Comment by DaniilHarik** [comment]
Problem caused by me not calling stop function on on app deactivation or termination.

**Comment by swisspol** [comment]
Sorry, I had missed that issue. The problem here is that you need to keep the GCDWebServer instance around, you can't assign it to a local variable, otherwise it will get released when getting out of scope.

**Comment by DaniilHarik** [comment]
No problem, thank you for your response
