### ISSUE TITLE
Warnings: No previous prototype for function; Missing field 'error' initializer;

### ISSUE THREAD

**Issue by nishabe** [swisspol/GCDWebServer#180]
Hello Team,
When I add the 'GCDWebServer' to an existing project I see the below two warnings.

GCDWebServer/Core/GCDWebServerFunctions.m
GCDWebServer/Core/GCDWebServerFunctions.m:51:6: No previous prototype for function 'GCDWebServerInitializeFunctions'

GCDWebServer/Core/GCDWebServer.m
GCDWebServer/Core/GCDWebServer.m:571:37: Missing field 'error' initializer

What may be the reason?

**Comment by swisspol** [comment]
Are you using CGDWebServer from a Swift project or an Obj-C project? What's your compiler setting? GNU99, C99?

These 2 errors are quite strange:
- GCDWebServerFunctions.m includes GCDWebServerPrivate.h which declares `GCDWebServerInitializeFunctions()`
- `CFStreamError` is a struct which can be initialized to 0 with simply `{0}`, there should be no need for `{0,0}`

I'm guessing something is going on with your Xcode build settings...

**Comment by swisspol** [comment]
No response, so I guess it was a fluke. Closing!
