### ISSUE TITLE
Show Progress in iOS device.

### ISSUE THREAD

**Issue by vivekCZ** [swisspol/GCDWebServer#181]
I want to show the receiving progress of file? Can anyone tell me?

**Comment by swisspol** [comment]
See #174 and #71. In a nutshell, use the `GCDWebServerOption_ConnectionClass` option to have GCDWebServer use a custom connection class, then override in your custom GCDWebServerConnection subclass the methods `- (void)processRequest:(GCDWebServerRequest*)request completion:(GCDWebServerCompletionBlock)completion` to get the body length from the `GCDWebServerRequest`, and `- (void)didReadBytes:(const void*)bytes length:(NSUInteger)length` to count the received bytes.

**Comment by zhenian** [comment]
```- (void)didReadBytes:(const void*)bytes length:(NSUInteger)length``` 

how to relate ```GCDWebServerConnection``` to special file in ```GCDWebServerMultiPartFormRequest``` when upload multiple files at one time?
