### ISSUE TITLE
iOS9 : Handling NSAppTransportSecurity

### ISSUE THREAD

**Issue by benbahrenburg** [swisspol/GCDWebServer#184]
Hello,
Sorry if this question is covered or documented differently.  Is there any guidance on how to handle NSAppTransportSecurity in iOS9?

At the moment it appears Apple doesn't allow localhost to be added to the exception list, requiring NSAllowsArbitraryLoads be set to true
~~~
	<key>NSAppTransportSecurity</key>
	<dict>
		<key>NSAllowsArbitraryLoads</key>
		<true/>
	</dict>	
~~~

Is there anyway to set the domain name GCDWebServer replies to, i.e. example.com ? This would allow for a domain exception to be added only for GCDWebServer and not all http urls being accessed.

This might help reduce issues in the AppStore review process.

More information on ATS available [here](http://ste.vn/2015/06/10/configuring-app-transport-security-ios-9-osx-10-11/)

**Comment by swisspol** [comment]
I'm not sure I understand what you are trying to do. NSAppTransportSecurity appears to be for apps retrieving http contents not serving it.

Is it because your app is connecting to its own GCDWebServer instance? Surely Apple will handle the localhost - if it's not already the case, be sure to file a radar / bug report.

**Comment by benbahrenburg** [comment]
@swisspol correct, when the WKWebView connects to http://localhost:1234 it generates a NSAppTransportSecurity error (show below)

App Transport Security has blocked a cleartext HTTP (http://) resource load since it is insecure. Temporary exceptions can be configured via your app's Info.plist file.

There is already two radars on this, so hopefully this isn't just a misconfiguration on my side.  Since Apple sometimes takes a full version to update ( think WKWebView local file access), I figured I'd raise this localhost restrictions and see if there was any thought on how to limit exposure without opening everything up.

**Comment by benbahrenburg** [comment]
After more digging, it seems additional keys need to be set.  Not sure if anyone else needs the same, but the below configuration in my Info.plist is working.  There is an existing radar open on localhost issues, but the below seems to resolve the issue for beta 2.

~~~
	<key>NSAppTransportSecurity</key>
	<dict>
	    <key>NSExceptionDomains</key>
	    <dict>
	        <key>localhost</key>
	        <dict>
	        	<key>NSTemporaryExceptionAllowsInsecureHTTPSLoads</key>
	            <false/>        	
	            <key>NSIncludesSubdomains</key>
	            <true/>
	            <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
	            <true/>
	            <key>NSTemporaryExceptionMinimumTLSVersion</key>
	            <string>1.0</string>
	            <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
	            <false/>
	        </dict>
	    </dict>
	</dict>	
~~~

**Comment by faxioman** [comment]
Unfortunately this solution doesn't work with the stable release of iOS9.

**Comment by raysefo** [comment]
Hello,

I am using this one but still getting the error below.

Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection.

Here is my sample plist:
<key>NSAppTransportSecurity</key>
    <dict>
      <key>NSExceptionDomains</key>
      <dict>
        <key>http://10.126.110.90</key>
        <dict>
          <key>NSTemporaryExceptionAllowsInsecureHTTPSLoads</key>
          <false/>
          <key>NSIncludesSubdomains</key>
          <true/>
          <key>NSTemporaryExceptionAllowsInsecureHTTPLoads</key>
          <true/>
          <key>NSTemporaryExceptionMinimumTLSVersion</key>
          <string>1.0</string>
          <key>NSTemporaryExceptionRequiresForwardSecrecy</key>
          <false/>
        </dict>
      </dict>
    </dict>
