### ISSUE TITLE
JSON response

### ISSUE THREAD

**Issue by lfaoro** [swisspol/GCDWebServer#185]
Would it be possible using this Framework to listen on a specific port for a GET request and send a JSON response?

i.e.:

GET http://hostRunningApp/api/agent

response:
{"menu": {
  "id": "file",
  "value": "File",
  "popup": {
    "menuitem": [
      {"value": "New", "onclick": "CreateNewDoc()"},
      {"value": "Open", "onclick": "OpenDoc()"},
      {"value": "Close", "onclick": "CloseDoc()"}
    ]
  }
}}

**Comment by swisspol** [comment]
Yes.

**Comment by lfaoro** [comment]
Thank you
