### ISSUE TITLE
How to make a new GET or POST request to server

### ISSUE THREAD

**Issue by KevinMac123** [swisspol/GCDWebServer#188]
i have to make new get request to server where i can place handler for get or post method?

**Comment by paulofierro** [comment]
@KevinMac123: check out the [Hello World example in the README.](https://github.com/swisspol/GCDWebServer#hello-world)

Hopefully that should answer the question.

**Comment by KevinMac123** [comment]
@paulofierro  thanks for ans. can you suggest me how i create link if i want so show directory image in browser. eg. download link work same like i have to create for picture that i have to show in browser.

**Comment by paulofierro** [comment]
Sorry, I don't understand the question. Do you want to show the directory listing?

Not sure what you mean by the download link or how it works.

**Comment by KevinMac123** [comment]
In demo they already provided listing and download button to download that file i dont know how that file is downloaded in browser. and moreover in my directory i have image and that image i have to show in browser now what can i do?

**Comment by swisspol** [comment]
@KevinMac123 It's unclear what exactly what you are trying to achieve. GCDWebServer will not show an image browser for you. You have to implement "handlers" to return the HTML page to display.

Check out https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m for several examples of handlers.

**Comment by KevinMac123** [comment]
ok but if i have an image in my document folder and i want to show that image in browser than for that image which link i have to use in html src tag? @swisspol

**Comment by swisspol** [comment]
The README explains in details how to use GCDWebServer but it's rather a low-level technology. If you're beginning with iOS development or are not familiar with networking, HTTP, HTML, etc... you will have a very hard time using GCDWebServer and it's unlikely people will be able to help you.

**Comment by KevinMac123** [comment]
ok @swisspol  thanks for you time.
