### ISSUE TITLE
Conditionally support multipart form requests

### ISSUE THREAD

**Issue by edwardaux** [swisspol/GCDWebServer#189]
I have a slightly oddball question... I am writing a Mac app that uses GCDWebServer to accept incoming HTTP requests and return mock responses.  At the moment, I use something like the following (in Swift):

	self.web.addDefaultHandlerForMethod("POST", requestClass: GCDWebServerDataRequest.self) { gcdRequest in
		return self.handleGCDRequest(.POST, gcdRequest as! GCDWebServerDataRequest)
	}

This successfully catches all incoming POST requests and sends them through to my handler, which is great! However, I now want to support multipart requests... the above code does indeed funnel them through to my handler, but I don't have access to any of the multipart data.  If I change the `requestClass` parameter to `GCDWebServerMultiPartFormRequest` it will successfully send through multipart requests to my handler, but it chokes on normal POST requests with a message saying _Failed starting to parse multipart form data_.

Is there a way I can either:
* Funnel multipart POSTs to one handler, and normal ones to another handler?
* Have GCDWebServer try to parse as `GCDWebServerMultiPartFormRequest` and failback to `GCDWebServerDataRequest` if it needs to
* Something else?

Note that, generally speaking, my app doesn't need to know or care what the incoming URL paths are, so I don't think using the `addHandlerForMethod` functions with a path won't help - but I could be wrong.

Thanks a lot.
Craig

**Comment by swisspol** [comment]
Try implementing your own match handler on top of the process handler, then you can return dynamically a given `GCDWebServerRequest` subclass. See README for details.

**Comment by edwardaux** [comment]
Thanks for the pointer - that was exactly what I needed. While my case is probably a bit unusual, I thought I'd loop back to add some info on what I ended up doing in case anyone else needs something similar.

The code below catches all incoming URLs (regardless of the method or path), and tries to instantiate the most appropriate GCDWebServer request object based on the inbound content type. 

	self.web.addHandlerWithMatchBlock({ (requestMethod, requestURL, requestHeaders, urlPath, urlQuery) -> GCDWebServerRequest! in
		if let contentType = requestHeaders["Content-Type"] as? String {
			if contentType == "application/x-www-form-urlencoded" {
				return GCDWebServerURLEncodedFormRequest(method: requestMethod, url: requestURL, headers: requestHeaders, path: urlPath, query: urlQuery)
			}
			else if contentType == "multipart/form-data" {
				return GCDWebServerMultiPartFormRequest(method: requestMethod, url: requestURL, headers: requestHeaders, path: urlPath, query: urlQuery)
			}
		}
		return GCDWebServerDataRequest(method: requestMethod, url: requestURL, headers: requestHeaders, path: urlPath, query: urlQuery)
	}, processBlock: { gcdRequest in
		// 
		// my handler code goes in here
		//
	})

Thanks again for a great library.
