### ISSUE TITLE
NSFastEnumerationMutationHandler exception thrown in GCDWebServerConnection

### ISSUE THREAD

**Issue by dredenba** [swisspol/GCDWebServer#192]
Our usage is occasionally triggering a crash when an exception is thrown during a ```NSFastEnumerationMutationHandler``` on line 544 in ```GCDWebServerConnection.m```

```
        for (_handler in _server.handlers) {
```

I'm not sure how this list of handlers is managed but it seems like a bug because I would not expect common usage of making requests to be responsible for marshalling items in this array.

Is there something I am missing? Or a convention I should be using to avoid this kind of problem?

**Comment by dredenba** [comment]
hmm looking like I might be misusing the api although it was not clear from the docs.

I was investigating some other odd behavior with the GCDWebServer and ran across this old issue #147 which indicates ```Adding handlers while the server is running is not supported either.``` I believe I was adding in handlers while the server was running (just before I needed the mapping) and it seemed to be okay. but when I switched to another non-default port this ```GWS_DCHECK``` check was failing and was confused why the port number change would cause this.

**Comment by swisspol** [comment]
Yes that would be the reason. If you build GCDWebServer in Debug mode, it will assert if you try to edit handlers while the server is running.
