### ISSUE TITLE
GCDWebServer aborts when a server fails to start, rather than emitting an error

### ISSUE THREAD

**Issue by matt-curtis** [swisspol/GCDWebServer#194]
Why was this design choice made? It makes it very difficult to debug failed server instantiations. Is there any fix/workaround for this - detecting a failed server start?

**Comment by swisspol** [comment]
It should only abort if there is a programmer error.

Are you running in Debug or Release mode?

On what line is it aborting?

**Comment by matt-curtis** [comment]
I'm running in debug mode, I supposed that could be it.

GWS_DNOT_REACHED is what is called, I think. I'm going to experiment more and get back to you

**Comment by swisspol** [comment]
GCDWebServer only calls `GWS_DNOT_REACHED()` to indicate programmer errors, so make sure you are using it as indicated by the README and the docs in the headers.
