### ISSUE TITLE
GCDWebDAVServer error 405

### ISSUE THREAD

**Issue by michealc** [swisspol/GCDWebServer#195]
Implemented GCDWebDAVServer from README and get error 405 method not implemented. Tried a number of clients.

                _davServer = [[GCDWebDAVServer alloc] initWithUploadDirectory:documentsPath];
                [_davServer start];
                NSLog(@"Visit %@ in your WebDAV client", _davServer.serverURL);

**Comment by swisspol** [comment]
What's the log of your WebDAV client? What's the log on the GCDWebServer side?

I just tried with Transmit and Cyberduck on OS X (using the Mac tool from the GCDWebServer Xcode project) and things are working fine:
```
HEAD / HTTP/1.1
Host: localhost:8080
Connection: Keep-Alive
User-Agent: Cyberduck/4.5.2 (Mac OS X/10.10.4) (x86_64)
HTTP/1.1 200 OK
Cache-Control: no-cache
Connection: Close
Server: GCDWebDAVServer
Date: Wed, 05 Aug 2015 17:33:36 GMT
PROPFIND / HTTP/1.1
Depth: 1
Content-Type: text/xml; charset=utf-8
Content-Length: 99
Host: localhost:8080
Connection: Keep-Alive
User-Agent: Cyberduck/4.5.2 (Mac OS X/10.10.4) (x86_64)
HTTP/1.1 207 Multi-Status
Cache-Control: no-cache
Content-Length: 4087
Content-Type: application/xml; charset="utf-8"
Connection: Close
Server: GCDWebDAVServer
Date: Wed, 05 Aug 2015 17:33:36 GMT
```

**Comment by swisspol** [comment]
Closing due to no follow-up response.
