### ISSUE TITLE
WebServer freezes app when it returns from background

### ISSUE THREAD

**Issue by fernandodev** [swisspol/GCDWebServer#197]
There are any way to avoid this issue?

To recover state, it takes 5 ~ 7 seconds to resume

**Comment by swisspol** [comment]
GCDWebServer does not freeze your app in any way. You must have something else unrelated going on.

**Comment by khush004** [comment]
@fernandodev Did you got any solution?

**Comment by fernandodev** [comment]
@khush004 hi! it was in 2015 :/ sorry i can't help, i barely remember the issue. 

Back to the time, I believe it was a race condition on the webserver.
