### ISSUE TITLE
How can I disable logging ?

### ISSUE THREAD

**Issue by mackoj** [swisspol/GCDWebServer#20]
How can I hide these ?
<code>
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
[DEBUG] Connection sent 32768 bytes on socket 15
</code>

**Comment by markhorgan** [comment]
Is there a way to turn off logging just for GCDWebServer? I use CocoaLumberjack for my own app's logging so changing DEBUG or LOG_LEVEL_DEF would affect it.

**Comment by swisspol** [comment]
See headers for logging constants and how to set the default level.

**Comment by maximkrouk** [comment]
Is there a way to disable logging in swift code, by kvc or something? Didn't get anything of GCDWebServerPrivate.h... Maybe it worth making that API public?

UPD: Found this https://stackoverflow.com/questions/38101065/how-to-set-gcdwebserveroption-automaticallysuspendinbackground-to-no, probably should work

```swift
GCDWebServer.setLogLevel(<#value#>)
```
