### ISSUE TITLE
Protocol callback for webUploader 

### ISSUE THREAD

**Issue by morganbigot** [swisspol/GCDWebServer#200]
Hi,

Would it be possible to have a  callback 
- (void)webUploader:(GCDWebUploader*)uploader didEnterFolderAtPath:(NSString*)path;
to be aware in iOS side when the user change folder in Web side.

Regards,
Morgan

**Comment by swisspol** [comment]
This wouldn't work in practice as GCDWebUploader doesn't track users: it is stateless. The only thing it can know is that someone has asked to list the content of a given directory. But if you have 2 users using the same server at the same time, it doesn't know which one is requesting the listing.

You can subclass `GCDWebServer` and override `- (GCDWebServerResponse*)listDirectory:(GCDWebServerRequest*)request` to know when this happens (see implementation in `GCDWebUploader.m` for details).

**Comment by morganbigot** [comment]
Thank you very much, that's what i needed.
regards,
Morgan

2015-08-13 18:25 GMT+02:00 Pierre-Olivier Latour <notifications@github.com>:

> This wouldn't work in practice as GCDWebUploader doesn't track users: it
> is stateless. The only thing it can know is that someone has asked to list
> the content of a given directory. But if you have 2 users using the same
> server at the same time, it doesn't know which one is requesting the
> listing.
>
> You can subclass GCDWebServer and override -
> (GCDWebServerResponse*)listDirectory:(GCDWebServerRequest*)request to
> know when this happens (see implementation in GCDWebUploader.m for
> details).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swisspol/GCDWebServer/issues/200#issuecomment-130750521>
> .
>



-- 
*Morgan BIGOT*
CO-CEO  SeeMeCab
phone: +33 2 23 25 61 98
mobile: +33 6 60 24 41 07
http://www.seemecab.com


<http://www.seemecab.com>
