### ISSUE TITLE
Which response to use for NSURLConnectionDataDelegate downloaded data

### ISSUE THREAD

**Issue by gongz** [swisspol/GCDWebServer#201]
Hi Swisspol,

I'm using GCDWebServer as a proxy that download mp4 from web and return to ios player. 
Because these type of files are usually big, I want to return partial data. I searched all the issues related to broken pipes and tried GCDResponse classes for File, Stream and Data responses. However, all end up with broken pipes and abort() from XLFacility.

Which response class do you think is the right one for this? Below is my code inside download delegate:
```
- (void)connection:(NSURLConnection *)connection didReceiveData:(NSData *)data{
    XLOG_DEBUG(@"Delegate callback connection didReceiveData");
    
 //GCDWebServerDataResponse* GCDResponse = [GCDWebServerDataResponse //responseWithData:data contentType:[self.urlResponse MIMEType]];

    GCDWebServerStreamedResponse *streamedResponse = [GCDWebServerStreamedResponse responseWithContentType:[[self urlResponse] MIMEType] streamBlock:^NSData *(NSError** error) {
      
        return data;
        
    }];


    self.completionBlock(streamedResponse);
   // self.completionBlock(GCDResponse);
}
```
Thanks.

**Comment by swisspol** [comment]
GCDWebServer doesn't randomly `abort()`: this means there's a programmer error somewhere. What is happening exactly?

**Comment by gongz** [comment]
On main thread, the trace is like:

    self.completionBlock(streamedResponse);  ->  

  - (void)_startProcessingRequest {
        [self _finishProcessingRequest:processResponse]; ->

 -(void)_finishProcessingRequest:(GCDWebServerResponse*)response {
    GWS_DCHECK(_responseMessage == NULL); ->

  - (void)logMessageWithTag:(NSString*)tag level:(XLLogLevel)level format:(NSString*)format, ... {
      [self _logMessage:message withTag:tag level:level callstack:nil];->

  - (void)_logMessage:(NSString*)message withTag:(NSString*)tag level:(XLLogLevel)level callstack:(NSArray*)callstack {
  if ((level >= kXLLogLevel_Abort) && XLIsDebuggerAttached()) {
    abort();-> ends here
  }

Log says:
00:00:05.756 [DEBUG    ]> Delegate callback connection didReceiveResponse
00:00:05.756 [DEBUG    ]> file size of data is 7071379
00:00:05.756 [DEBUG    ]> MIME type of data is video/mp4
00:00:05.756 [DEBUG    ]> Delegate callback connection didReceiveData streamedResponse
00:00:05.757 [DEBUG    ]> Connection sent 175 bytes on socket 12
00:00:05.757 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.757 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.759 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.760 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.760 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.761 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.761 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.761 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.762 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.762 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.763 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.763 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.763 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.764 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.764 [DEBUG    ]> Delegate callback connection didReceiveData streamedResponse
00:00:05.766 [DEBUG    ]> Connection sent 2454 bytes on socket 12
00:00:05.766 [DEBUG    ]> Connection sent 2454 bytes on socket 12

ends at abort.

**Comment by swisspol** [comment]
Looks like you are not using the GCDWebServer API properly. See the README and https://github.com/swisspol/GCDWebServer/blob/master/Mac/main.m for some examples.

You probably want to use `GCDWebServerStreamedResponse` with the `GCDWebServerAsyncStreamBlock` variant to bridge the asynchronous delegate with the asynchronous GCDWebServer.

**Comment by gongz** [comment]
Hi Swisspol,

Thanks for your response. I finally figured out.

We added Range header to the request going out and response back to the player.

The streamedResponse sends small bytes and stops with a broken pipe in this case. 
The response type works for me is GCDWebServerDataResponse. I use it to give response to player when the chunk of the mp4 is downloaded.
