### ISSUE TITLE
Is that possible to run GCDWebServer in sort of background mode in Cocoa apps?

### ISSUE THREAD

**Issue by mrahmiao** [swisspol/GCDWebServer#202]
I am developing an Cocoa app. And I am wondering if I can use GCDWebServer to redirect REST API calls from browser extensions to my app.

If I launched a web server directly in `applicationDidFinishedLaunching:`, my app can only acts as an web server while other functionalities blocked by the web server.

**Comment by swisspol** [comment]
It's not possible to run an iOS app continuously in the background - See README for details.

For a web server to be continuously available in the background, you could try using a VOIP socket, but Apple is unlikely to let that pass App Store review.

**Comment by mrahmiao** [comment]
@swisspol What I mean is in an OS X app, not in an iOS app. The documentation says that `runWithPort:` **must** be used from the main thread only, but I wonder if it can be ran in a private queue.

**Comment by swisspol** [comment]
Ah. In this case, just don't use `-runWithPort:`. It's a simple wrapper around the run loop: https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.m#L769. Just call `-startWithOptions:error:`.

GCDWebServer can be used from any thread (although delegate callbacks always run on the main thread).

See README for details.
