### ISSUE TITLE
When used in Xcode7 beta 6 a lot of warnings pop up

### ISSUE THREAD

**Issue by rhinoid** [swisspol/GCDWebServer#208]
Most of the warnings are of the type: Block implicitly retains 'self'; explicitly mention 'self' to indicate this is intended behavior

**Comment by swisspol** [comment]
I'm not getting any warnings when building the official GCDWebServer Xcode project under Xcode 7 beta 6.

If you add the source code directly to your project, you might have to disable some warnings. See the build setting "Other Warning Flags" in the GCDWebServer Xcode project.
