### ISSUE TITLE
How to configure NAT traversal in GCDWebServer

### ISSUE THREAD

**Issue by KevinMac123** [swisspol/GCDWebServer#209]
After some research i found DNSServiceNATPortMappingCreate function included in bonjour libraries. So, how can i use that in GCDWebServer? Please suggest me how to configure NAT from an app.

**Comment by swisspol** [comment]
This is beyond the scope of GCDWEbServer and not something I can help with, sorry.

**Comment by KevinMac123** [comment]
ok. NAT possible in iOS?  @swisspol
