### ISSUE TITLE
Carthage build broken with 3.2.6

### ISSUE THREAD

**Issue by 0xpablo** [swisspol/GCDWebServer#212]
I think the `3.2.6` release broke building GCDWebServer with Carthage. If I set the `3.2.5` version in my Cartfile, GCDWebServer builds correctly.

This is the error:
```
*** Fetching GCDWebServer
*** Checking out GCDWebServer at "3.2.6"

Dependency "GCDWebServer" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/swisspol/GCDWebServer/issues/new
```

This happens using Xcode 7 GM (I haven't tested in previous versions of Xcode)

**Comment by swisspol** [comment]
I don't use Carthage so i don't know why it would not work anymore considering the shared schemes are still around.

Can someone have a look and send a PR?

**Comment by 0xpablo** [comment]
I think I got it. I'll try to send a PR :)

**Comment by 0xpablo** [comment]
I submitted PR #213. I will close the issue.

Thank you for your time!
