### ISSUE TITLE
Optionally disable debug aborts conditions

### ISSUE THREAD

**Issue by matt-curtis** [swisspol/GCDWebServer#217]
There are times when GCDWebServer will halt and abort on non-breaking errors. Being able to toggle a flag somewhere would be ideal, rather than just going off of the DEBUG flag.

**Comment by swisspol** [comment]
Abort should only be called on programmer errors. What specific case are you hitting?

**Comment by matt-curtis** [comment]
For example - whenever I stop the server, ` GWS_DNOT_REACHED` is hit because (?) `_options` is not defined.

**Comment by swisspol** [comment]
That's because you are not retaining the server most likely or calling stop more than once.

**Comment by matt-curtis** [comment]
Ah, you're right; I can't believe I missed that.

Do you have any suggestions as to why I experience very long upload times with multipart form data (files)?

**Comment by swisspol** [comment]
Check the Xcode log, GCDWebServer logs a lot if `DEBUG` is defined. Apart from that, I'd say check your WiFi network :smile:

**Comment by matt-curtis** [comment]
Examining the logs, I get lots of `[DEBUG] Connection received .... bytes on socket 21`. Transfer seems slow, and  prone to hangs in between chunks. In total it took about a minute and a half, give or take. This was on a single 4 MB file. I don't think my wifi is the issue, as far as I can tell, other requests to/from GCDWebServer are lighting-fast.

**Comment by matt-curtis** [comment]
Could how I make the multipart-data request be an issue? I'm using XMLHttpRequest+form data to make the POST request.

**Comment by swisspol** [comment]
I can't really help with that, sorry, there are too many things that go wrong outside of GCDWebServer.

I'd recommend using the Chrome web inspector to understand what's happening to the requests. Good luck!

**Comment by matt-curtis** [comment]
just so you know, I'm experiencing this with bare-bones `<forms />` & `<input type="file" />` as well.

**Comment by matt-curtis** [comment]
What does it mean if I receive aborts in `performOpen`? Only happens when i send several POST requests one after another.

**Comment by matt-curtis** [comment]
If you could provide any pointers I'd appreciate it. Here's the code I'm using to create the server and process multipart POST requests. It aborts in `performOpen:` if there is an existing pending request, I'm assuming because something isn't getting closed. I'm just not able to identify the fault in my code that is causing this.

```objc
__weak typeof(self) ws = self;

_webServer = [GCDWebServer new];

[_webServer
	addDefaultHandlerForMethod:@"GET" requestClass:[GCDWebServerRequest class]
	processBlock:^GCDWebServerResponse* (GCDWebServerRequest *request){
		if(![ws shouldRespondToRequest:request]) return ws.notFoundResponse;
		
		GCDWebServerResponse *response = [ws responseForHTTPGetRequest:request];
		
		response.gzipContentEncodingEnabled = true; // compress all responses
		
		[response setValue:@"*" forAdditionalHeader:@"Access-Control-Allow-Origin"];
		
		return response;
	}];

[_webServer
	addDefaultHandlerForMethod:@"POST" requestClass:[GCDWebServerMultiPartFormRequest class]
	processBlock:^GCDWebServerResponse* (GCDWebServerRequest *request){
		if(![ws shouldRespondToRequest:request]) return ws.notFoundResponse;
		
		GCDWebServerResponse *response = [ws responseForHTTPPostRequest:request];
		
		response.gzipContentEncodingEnabled = true; // compress all responses
		
		[response setValue:@"*" forAdditionalHeader:@"Access-Control-Allow-Origin"];
		
		return response;
	}];

[_webServer startWithPort:kWebServerPort bonjourName:nil];

//	responseForHTTPPostRequest:

NSString *identifier = [request firstArgumentForControlName:kAPIKey_Ids].string;

NSLog(@"%@", identifier);

return _emptyJSONResonse;
```
