### ISSUE TITLE
Sending additional POST requests while existing POST requests haven't finished causes crash

### ISSUE THREAD

**Issue by matt-curtis** [swisspol/GCDWebServer#220]
Issue is exactly as describe in title - if I fire off several POST requests at the same time, as long as other requests are still pending `GCDWebServer` will abort in `performOpen:`.

Here's what my handler looks like:

```objective-c
[_webServer
	addDefaultHandlerForMethod:@"POST" requestClass:[GCDWebServerMultiPartFormRequest class]
	processBlock:^GCDWebServerResponse* (GCDWebServerRequest *request){
		NSDictionary *reasonablyLargeDictionary = @{ ... };
		GCDWebServerResponse *response = [GCDWebServerDataResponse responseWithJSONObject:reasonablyLargeDictionary];
		
		response.gzipContentEncodingEnabled = true;
		
		[response setValue:@"*" forAdditionalHeader:@"Access-Control-Allow-Origin"];
		
		return response;
	}];
```

**Comment by swisspol** [comment]
What's the stack trace?

**Comment by matt-curtis** [comment]
Attached.

![gcdwebserverresponse_m](https://cloud.githubusercontent.com/assets/1414704/10103783/9dd196da-636b-11e5-93d1-ec16c5b45519.png)

**Comment by swisspol** [comment]
Your stack is missing the symbols, so one can't know why abort() is called, and what the API error is.

I'm suspecting you are reusing responses instead of creating new ones.

**Comment by matt-curtis** [comment]
That's exactly right, are you a wizard? :smile: 

So it's a no-no to reuse responses?

**Comment by swisspol** [comment]
I think you can reuse responses that don't have a body IIRC. Anyway, the abort() makes it clear if you were to break on that line in the source.
