### ISSUE TITLE
POST request with enctype='application/x-www-form-urlencoded' crashes app when parsing multipart/form-data requests

### ISSUE THREAD

**Issue by ReimuYome** [swisspol/GCDWebServer#225]
As far as I know, the ````requestClass```` argument has to be specified as  ````GCDWebServerRequest.class```` in order to parse multipart/form-data requests.

But if someone deliberately send a ````POST```` request with ````enctype='application/x-www-form-urlencoded'```` encoding type to the handler, the framework chooses to crash the whole app. As the ````abort()```` function is called at line 173 in ````GCDWebServerMultiPartFormRequest.m````.

That is to say, if I establish a handler like this:
````
[server addHandlerForMethod:@"POST"
                           path:@"/evilapi"
                   requestClass:GCDWebServerRequest.class
              asyncProcessBlock:
     ^(GCDWebServerRequest *req, GCDWebServerCompletionBlock completionBlock) {
    }];
````

and someone deliberately submit a form like this:
````
<form method="POST" action="<!-- path to server -->/evilapi" 
			enctype="application/x-www-form-urlencoded">
    <input type="hidden" name="somename" value="somevalue" />
    <button type="submit">Submit This Form</button>
</form>
````

The whole app will crash.

In my opinion, it is better to kill the thread handling the request or actively return a ````500```` status code to browser, rather than calling ````abort()```` directly.

**Comment by swisspol** [comment]
This will happen in Debug builds only, otherwise an error will be returned,
