### ISSUE TITLE
Deprecated methods in iOS 9

### ISSUE THREAD

**Issue by adib** [swisspol/GCDWebServer#231]
These are now deprecated in iOS 9

 - `stringByAddingPercentEscapesUsingEncoding`
 - `CFURLCreateStringByAddingPercentEscapes`
 - `CFURLCreateStringByReplacingPercentEscapesUsingEncoding`

GCDWebServer.m:917:37: 'stringByAddingPercentEscapesUsingEncoding:' is deprecated: first deprecated in iOS 9.0 - Use -stringByAddingPercentEncodingWithAllowedCharacters: instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent since each URL component or subcomponent has different rules for what characters are valid.

GCDWebServerFunctions.m:185:28: 'CFURLCreateStringByAddingPercentEscapes' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByAddingPercentEncodingWithAllowedCharacters:] instead, which always uses the recommended UTF-8 encoding, and which encodes for a specific URL component or subcomponent (since each URL component or subcomponent has different rules for what characters are valid).

GCDWebServerFunctions.m:189:28: 'CFURLCreateStringByReplacingPercentEscapesUsingEncoding' is deprecated: first deprecated in iOS 9.0 - Use [NSString stringByRemovingPercentEncoding] or CFURLCreateStringByReplacingPercentEscapes() instead, which always uses the recommended UTF-8 encoding.

**Comment by adib** [comment]
I noticed that you've suppressed deprecations in cad428ca6f632c16ecb6d34f87a307d5e1cf37df. What's the long-term plan for this? Shouldn't these be replaced with the recommended API calls instead?

**Comment by swisspol** [comment]
The replacement APIs don't offer the same level of functionality as the old APIs, so I don't plan on switching to them until there's no choice.
