### ISSUE TITLE
Fix Info.plist files to avoid iTunes Connect ITMS errors during app submission

### ISSUE THREAD

**Issue by rbaulin** [swisspol/GCDWebServer#233]
Info.plist shipped within bundle causes errors during app submission (please see [this SO question](http://stackoverflow.com/questions/33271789/various-itms-errors-when-trying-to-submit-archive-to-app-store/33356508#33356508))
Please add `CFBundleVersion` and `CFBundleShortVersionString` keys or remove the Info.plist entirely (why is that even required here?).

<img width="325" alt="screen shot 2015-10-27 at 00 36 29" src="https://cloud.githubusercontent.com/assets/679174/10743975/956a66a8-7c47-11e5-9483-d2c5dffa9f1b.png">

Thanks for amazing library!

**Comment by swisspol** [comment]
ea973735c1baea5a08f7b8aef273222ef9bedf9a should fix the problem unless the internal bundle `GCDWebUploader.bundle` is also affected.
