### ISSUE TITLE
Cannot use the pod as a pod dependency on tvOS

### ISSUE THREAD

**Issue by beeloo42** [swisspol/GCDWebServer#240]
Can you please tag the 3.3 version or something ?
So that I can create a pod with a spec.dependency 'GCDWebServer', '~> 3.3'

If I use the 3.2.7 version I cannot embed it into a tvOS project...

**Comment by jhoughjr** [comment]
I was able to integrate it using :git => "the git clone url"
However I'm now having issues with the bridging header setup :/

**Comment by swisspol** [comment]
I just released 3.3!

**Comment by beeloo42** [comment]
Cheers pol ! Merry Christmas :)
