### ISSUE TITLE
Feature Request - shouldShowCreateFolder

### ISSUE THREAD

**Issue by ConfusedVorlon** [swisspol/GCDWebServer#241]
firstly -thanks for a great project.

it would be great to be able to completely disable the 'Create Folder' button in the Web Uploader.

I'm currently subclassing and forbidding folder creation - but it would be a better user experience if the button didn't exist and they didn't get 'forbidden' messages.

**Comment by ChristianVirtual** [comment]
Copy that. Plus also for the "move" button. Right now I solved it by copy the bundle file and remove the two elements from the index.html. A bit rude/crude but works.

Else a phantastic project.

**Comment by swisspol** [comment]
Seems reasonable, if something sends a PR, I'll take a look :smile:
