### ISSUE TITLE
GCDWebServer not recovering properly after the app has been suspended and resumed.

### ISSUE THREAD

**Issue by Allan121** [swisspol/GCDWebServer#243]
We are currently using the GCDWebServer as part of our music app as a means to serve track data back to the player. As such, the app and the server need to continue operating whilst the app is in the background, which it does while audio is playing. Unfortunately, if the audio is paused while the app is in the background, and the app is consequently suspended by the OS, something happens with the server that it doesn't seem to be able to recover from, even once the app is resumed. 

The odd part is that the server thinks it's running fine after the app is resumed, and the port remains the same, but it won't respond to any requests.

I know that it can't run in the background without something else keeping the app active, but I find it odd that it can't seem to recover from the app being suspended.

I have tried adding the delegate method ```webServerDidStop:```, but it doesn't seem to get called at all.

**Comment by swisspol** [comment]
See the README for information about using GCDWebServer in the background and the restrictions iOS enforces. This is definitely supported and works out of the box. In the case of an audio app which might not get suspended at all, you might have to disable `GCDWebServerOption_AutomaticallySuspendInBackground`.
