### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by igor9silva** [swisspol/GCDWebServer#245]
Since Swift is now open-source and has an official Linux port, would be great to be able to write APIs (which mostly run on RHEL or Debian-like distros) in the same language we write our apps.

I'd like to contribute to that enhancement.

**Comment by adib** [comment]
Objective-C is has been open-source and has Linux ports. Personally I'd prefer waiting for Swift to be backwards-compatible before starting to write serious apps on it. Otherwise every new version of Xcode entails fixing compilation errors on Swift sources.

**Comment by igor9silva** [comment]
I have to agree @adib.

**Comment by swisspol** [comment]
GCDWebServer is written in Obj-C not Swift and there are no plans to port it to Swift at this time, sorry.
