### ISSUE TITLE
Crash on GCDWebServerGetMimeTypeForExtension

### ISSUE THREAD

**Issue by typcn** [swisspol/GCDWebServer#247]
Stack trace:
```
Thread : Crashed: com.apple.root.default-qos
0  libobjc.A.dylib                0x7fff92fb90dd objc_msgSend + 29
1  libobjc.A.dylib                0x7fff92fd9786 objc_object::sidetable_release_slow((anonymous namespace)::SideTable*, bool) + 162
2  libobjc.A.dylib                0x7fff92fd985a objc_object::sidetable_release(bool) + 170
3  GCDWebServers                  0x104572373 GCDWebServerGetMimeTypeForExtension + 106
4  GCDWebServers                  0x1045656cf -[GCDWebServerFileResponse initWithFile:byteRange:isAttachment:] + 889
5  GCDWebServers                  0x10456516f +[GCDWebServerFileResponse responseWithFile:] + 75
6  GCDWebServers                  0x10456ff94 __110-[GCDWebServer(GETHandlers) addGETHandlerForBasePath:directoryPath:indexFilename:cacheAge:allowRangeRequests:]_block_invoke458 + 711
7  GCDWebServers                  0x10456bce1 __54-[GCDWebServer addHandlerWithMatchBlock:processBlock:]_block_invoke + 62
```

Sry for I can't reproduce it , because It's uploaded from user .
But I think it's caused by some special mime type.

https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServerFunctions.m#L162

**Comment by swisspol** [comment]
It must have been a fluke: this API doesn't do anything fancy.

**Comment by abraxascorner** [comment]
I have the same exceptions. I attached stack from Crashlytics
[info.sportklub_issue_6_crash_c34051a3fecc4143bbbc331c173976cd_b401a0c9459c4effb92e593b8cebf89e_0_v1.txt](https://github.com/swisspol/GCDWebServer/files/844158/info.sportklub_issue_6_crash_c34051a3fecc4143bbbc331c173976cd_b401a0c9459c4effb92e593b8cebf89e_0_v1.txt)

**Comment by swisspol** [comment]
Do you have any way to reproduce or any more context?

**Comment by typcn** [comment]
I guess it's caused by system api, user may installed some software that registered malformed mime type.
(not sure, I'm busy and don't have time to debug the system comp with 20+ calls)

I have tried change the code, add null pointer checks , add data format checks . not working...  
so I changed it to hardcoded mime table and no longer concerned about this.

**Comment by abraxascorner** [comment]
Ok, thank you for your help.
