### ISSUE TITLE
Can you increase the edit page?

### ISSUE THREAD

**Issue by hydyy** [swisspol/GCDWebServer#253]
可以嵌入一个文本编辑器，如果是文本文件，直接点击进入修改。这样就不用每次下载修改再上传了
You can embed a text editor, if it is a text file, just click to enter the changes. So do not modify each download and then upload the

**Comment by swisspol** [comment]
What do you mean exactly? If you are talking about GCDWebUploader, you can modify the CSS in the bundle.
