### ISSUE TITLE
Add support for HTTP range requests

### ISSUE THREAD

**Issue by swisspol** [swisspol/GCDWebServer#27]
See #26 for an example use

**Comment by ephemer** [comment]
@swisspol @mmilnePSG I am trying to serve .mp4s via GCDWebServer with the command

    [_webServer addGETHandlerForBasePath:@"/"
                           directoryPath:directoryPath
                           indexFilename:nil
                                cacheAge:0
                      allowRangeRequests:YES];

And I am getting a message about a broken pipe in the Xcode console:
`[ERROR] Error while writing to socket 28: Broken pipe (32)`

It doesn't matter which mp4 I try, none of them work. I'm using a WKWebView on iOS 8 (on the 'new'/first retina iPad). Is there something I'm missing, some other configuration step?

**Comment by ephemer** [comment]
@swisspol I've updated to the latest release of GCDWebServer and I'm now getting a slightly different error when trying to access mp4s via the server:
`[ERROR] Error while writing to socket 23: Protocol wrong type for socket (41)`
