### ISSUE TITLE
iOS10.1.1 Hello World test failed

### ISSUE THREAD

**Issue by fighterLS** [swisspol/GCDWebServer#280]
```
#import "GCDWebServer.h"
#import "GCDWebServerDataResponse.h"

@interface AppDelegate : NSObject <UIApplicationDelegate> {
  GCDWebServer* _webServer;
}
@end

@implementation AppDelegate

- (BOOL)application:(UIApplication*)application didFinishLaunchingWithOptions:(NSDictionary*)launchOptions {

  // Create server
  _webServer = [[GCDWebServer alloc] init];

  // Add a handler to respond to GET requests on any URL
  [_webServer addDefaultHandlerForMethod:@"GET"
                            requestClass:[GCDWebServerRequest class]
                            processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {

    return [GCDWebServerDataResponse responseWithHTML:@"<html><body><p>Hello World</p></body></html>"];

  }];

  // Start server on port 8080
  [_webServer startWithPort:8080 bonjourName:nil];
  NSLog(@"Visit %@ in your web browser", _webServer.serverURL);

  return YES;
}

@end
```
 When I put the`_webServer.serverURL` in my web browser,it failed to load under the ios10.  Test successfully under the ios8. Do you have any suggestion to fix it?

**Comment by swisspol** [comment]
Anything relevant in the log of GCDWebServer? Maybe a setting in your Info.plist is wrong? GCDWebServer certainly works on 10.x.

**Comment by fighterLS** [comment]
@swisspol Hi,Thanks,I have package the test project. Test environment is under the same wifi. Test Mobile is iphone5s. In iOS 10.x , webserver is no response. How to set in my Info.plist?
[TestWebServer.zip](https://github.com/swisspol/GCDWebServer/files/653629/TestWebServer.zip)

**Comment by swisspol** [comment]
If you run the demo app included in GCDWebServer, does it work?

**Comment by fighterLS** [comment]
@swisspol yeah ! The demo app included in GCDWebServer is work .

**Comment by swisspol** [comment]
Then it's something in your code, please check for difference with demo.

**Comment by fighterLS** [comment]
@swisspol 
OK, I have find the bug. It a little weird.
I just change
`[_webServer startWithPort:8080 bonjourName:nil];`
 to 
`[_webServer startWithPort:8080 bonjourName:@""];`
And ,it works.
