### ISSUE TITLE
Support basic and digest authentication at the same time

### ISSUE THREAD

**Issue by michaelochs** [swisspol/GCDWebServer#285]
Looking at the API it seems that `GCDWebServerOption_AuthenticationMethod` only supports one value. Is there any way to support both, `GCDWebServerAuthenticationMethod_Basic` and `GCDWebServerAuthenticationMethod_DigestAccess` for authentication? If not, is there any preferred way to integrate that / is that a feature that would be worth a PR?

**Comment by swisspol** [comment]
There's no way to do that. It would be something rather unconventional to do though and it's not a PR I would accept, sorry.
