### ISSUE TITLE
Semantic Issue: Use of undeclared identifier 'LOG_ASYNC_ENABLED'

### ISSUE THREAD

**Issue by White-White** [swisspol/GCDWebServer#286]
I am using GCDWebServer/Uploader from Swift 3.0, xCode 8.1.
Following instructions from the homepage, I added this line to my Podfile(using framework): 

pod "GCDWebServer/WebUploader", "~> 3.0"

After pod update, the project couldnt compile and shot this error: 

Semantic Issue: Use of undeclared identifier 'LOG_ASYNC_ENABLED'

It seemed like some code referenced a macro from a private header.

**Comment by karnakar** [comment]
hi swisspol i too got the same issue, any temporary workaround for this?

**Comment by nickplee** [comment]
Changing my Podfile to include a specific version of CocoaLumberjack fixed it for me:
![image](https://cloud.githubusercontent.com/assets/1805969/22947953/cc838e62-f2ca-11e6-9f94-07db48bd15ae.png)

**Comment by appbanana** [comment]
I too got the same issue. I Change my Podfile to include a specific version of CocoaLumberjack, but it doesn't solve. How to solve this problem?

**Comment by softwind0214** [comment]
@appbanana you should run `pod update` :D

**Comment by sanjukhunt** [comment]
pod 'CocoaLumberjack/Swift'
pod "GCDWebServer/WebUploader", "~> 3.3"

I have changed pod file for swift and it's work for me
