### ISSUE TITLE
recommended to replace __unsafe_unretained with __weak

### ISSUE THREAD

**Issue by zhongwuzw** [swisspol/GCDWebServer#294]
The current version does not support `MRC`, so  I think we should replace `__unsafe_unretained` with `__weak`,for instance delegate,  block to avoid circular references(`__unsafe_unretained` is ok in the case of `__unsafe_unretained` always valid), to avoid crash when `__unsafe_unretained` object not set nil before released.

**Comment by swisspol** [comment]
IIRC the reason for `__unsafe_unretained` instead of `weak` is that ARC in some context did not support weak references (but it's pretty old).
