### ISSUE TITLE
How to run server on different ports

### ISSUE THREAD

**Issue by karnakar** [swisspol/GCDWebServer#295]
Hi all,

I'm trying to run server using default handler method on multiple ports but it is crashing at the nil options, my GCDWebServer instance is static.

Server is a class & davServer is an class level instance of type GCDWebServer
`Server.davServer?.addDefaultHandler(forMethod: "GET", request: GCDWebServerDataRequest.classForCoder(), processBlock: { (request) in
})`

Server.davServer?.start(withPort: port, bonjourName: "iOSServer")

**Comment by swisspol** [comment]
A GCDWebServer instance can only run on 1 port. You can have multiple GCDWebServer instances however.

**Comment by karnakar** [comment]
thanks @swisspol
