### ISSUE TITLE
HttpRequest status 0

### ISSUE THREAD

**Issue by zzepos** [swisspol/GCDWebServer#296]
I have the following javascript app that receives data from GCDWebServer that runs on an OSX app.

```
var HttpClient = function() {
	    this.get = function(aUrl, aCallback) {
	        var anHttpRequest = new XMLHttpRequest();
	        anHttpRequest.open( "GET", aUrl, true );   
	        anHttpRequest.onreadystatechange = function() { 
	            if (anHttpRequest.readyState == 4 && anHttpRequest.status == 200) {
	                aCallback(anHttpRequest.responseText);
	                document.write (anHttpRequest.responseText);
	               }
	               else {
	                document.write ("Not Ok: ReadyState=" + anHttpRequest.readyState + " Status= " + anHttpRequest.status);
	               }
	        }      
	        anHttpRequest.send( null );
	    }
	}

	var client = new HttpClient();
	client.get('http://xxx.xxx.x.xx:8080?var=param', function(response) {
		document.write ("Success"); 
	});
```

The Cocoa app runs the following code:

```
[webServer addDefaultHandlerForMethod:@"GET"
                             requestClass:[GCDWebServerRequest class]
                        asyncProcessBlock:^(GCDWebServerRequest* request, GCDWebServerCompletionBlock completionBlock) {
                            
                            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                                GCDWebServerDataResponse* response = [GCDWebServerDataResponse responseWithJSONObject:dict];
                                completionBlock(response);
                            });
```

I always get an anHttpRequest.readyState = 4 and anHttpRequest.status = 0. The anHttpRequest.responseText is empty. 

However, when I open any browser and type http://xxx.xxx.x.xx:8080?var=param I get the correct results. So the server is sending the data properly. 

Here is the log from GCDWebServer
[DEBUG] Did open connection on socket 13
[DEBUG] Did connect
[DEBUG] Connection received 312 bytes on socket 13
[DEBUG] Connection on socket 13 preflighting request "GET /" with 312 bytes body
[DEBUG] Connection on socket 13 processing request "GET /" with 312 bytes body
[DEBUG] Connection sent 175 bytes on socket 13
[DEBUG] Connection sent 107 bytes on socket 13
[DEBUG] Did close connection on socket 13
[VERBOSE] [xxx.xxx.x.xx:8080] xxx.xxx.x.xx:52401 200 "GET /" (312 | 282)
[DEBUG] Did disconnect

Any ideas? 
Thanks in advance.

**Comment by swisspol** [comment]
The fact you get a proper answer when calling GCDWebServer directly in your web browser means that it's likely in a bug in your JavaScript?

**Comment by leo150** [comment]
@zzepos did you figure out what is wrong? I got exactly same issue

**Comment by black1997** [comment]
i use xhr.open('GET', 'http://192.168.0.141:8080/test'),but does't work... the HttpRequest status still 0.
