### ISSUE TITLE
CFURLCopyPath returns nil for / path, which results in GWS_DNOT_REACHED()

### ISSUE THREAD

**Issue by michaelochs** [swisspol/GCDWebServer#297]
I am currently looking at `-[GCDWebServerConnection _readRequestHeaders]` which is handling a WebDAV request. The request I'm getting has the URL `http://192.168.178.133/`. Checking the URL's `path` property returns the correct `/` string, however in line 540 where the `requestPath` is calculated, it uses `CFURLCopyPath()` instead, which returns `nil` for this URL. This then makes the next condition fail: `if (requestMethod && requestURL && requestHeaders && requestPath && requestQuery) {`

Is there a reason why `requestPath` is checked in this condition? It seems to be optional on a URL, so it should probably assume the root path if it is not present.

**Comment by swisspol** [comment]
What OS / version is this observed on?

**Comment by michaelochs** [comment]
I've seen this with iOS 10.2.1 when e.g. making a WebDAV request with ForkLift 3. I assume it's a bug there as it is reporting the path as `//` but the server should be able to handle this as the intention is clear and `-[NSURL path]` does the right thing here.

I have a hot fix in our project that fixes this. I can make a PR out of it if you like:
`NSString* requestPath = requestURL ? (GCDWebServerUnescapeURLString(CFBridgingRelease(CFURLCopyPath((CFURLRef)requestURL))) ?: @"/") : nil;`

**Comment by swisspol** [comment]
You can repro in the Mac test app by doing `curl "http://localhost:8080//"`

**Comment by swisspol** [comment]
CFURL has a very peculiar behavior here:
```
(lldb) po requestURL
// -- http://localhost:8080/

(lldb) po CFURLCopyPath((CFURLRef)requestURL)
 nil
(lldb) po CFURLCopyStrictPath((CFURLRef)requestURL, NULL)
 nil
(lldb) po CFURLCopyFileSystemPath((CFURLRef)requestURL, 0)
 nil
(lldb) po requestURL.path
/
```

**Comment by swisspol** [comment]
More fun:
```
(lldb) po CFURLCopyPath((CFURLRef)[NSURL URLWithString:@"/" relativeToURL:(id)[NSURL URLWithString:@"http://localhost"]])
/

(lldb) po CFURLCopyPath((CFURLRef)[NSURL URLWithString:@"//" relativeToURL:(id)[NSURL URLWithString:@"http://localhost"]])
 nil
(lldb) po CFURLCopyPath((CFURLRef)[NSURL URLWithString:@"///" relativeToURL:(id)[NSURL URLWithString:@"http://localhost"]])
/
```
