### ISSUE TITLE
Query: sending response data from different method / from outside default block

### ISSUE THREAD

**Issue by msanilkumar2020** [swisspol/GCDWebServer#300]
Hi,

Thanks for writing wonderful library.

I have a requirement where i need to send response back to originator from different block

 Detail requirement 
- I receive addDefaultHandlerForMethod when we call local request with port no.
- Inturn i need to call another Api to get the response data, here they have implemented delegates, through delegate i will get response and data that needs to pass it to originator.

Please let me know i can use any of your api to implement this feature.

**Comment by msanilkumar2020** [comment]
@swisspol any suggestion?

**Comment by swisspol** [comment]
If I understand your question correctly, you need:
https://github.com/swisspol/GCDWebServer#asynchronous-http-responses
