### ISSUE TITLE
Feature request: Callback mechanism for a connection close 

### ISSUE THREAD

**Issue by matti777** [swisspol/GCDWebServer#301]
Hello, if a mechanism for this exists already and I too blind to see it, I apologize. 

I would love to be able catch the incoming connection being closed with a callback. I would propose adding a callback block to GCDWebServerRequest that would get called from  within -(BOOL)performClose:(NSError**)error; Currently, it seems the only way to catch this would be to superclass the request class and implement -close, which would IMO be overkill for such a task.

I am building a kind of a relay server for serving streaming audio/video players and they seem to often decide to cut their connections in the middle of data delivery. Currently, this will cause my receiving end stockpile data without a client sink to deliver it to.

**Comment by swisspol** [comment]
For this type of usage, the recommended and official way is to use a custom subclass of `GCDWebServerConnection` and override `-close`.
