### ISSUE TITLE
support CORS

### ISSUE THREAD

**Issue by yingyangios** [swisspol/GCDWebServer#306]
Sorry to troubel you. My project occure a problem "Failed to load resource: Request header field isAllSecret is not allowed by Access-Control-Allow-Headers.". How I set up the GCDWebserver to resolve it ?  Thank you very much

**Comment by swisspol** [comment]
You can set additional headers on the `GCDWebServerResponse` you return:
https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServerResponse.h#L177
