### ISSUE TITLE
Don't crash on non-UTF8 encoded query parameters

### ISSUE THREAD

**Issue by jberkel** [swisspol/GCDWebServer#308]
GCDWebServer assumes that all query values are UTF-8 encoded and crashes if that's not the case:

https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServerFunctions.m#L223

However there's nothing in the RFC (3986) mandating the use of UTF-8; it is only required for the host (reg-name) part of the URL. It merely suggests the use of UTF-8 for *textual* data.

The server should therefore either ignore those values, or decode them to `NSData` to expose the raw data to the client.

**Comment by swisspol** [comment]
It doesn't crash, just aborts() in Debug builds. The values are indeed ignored and warning message is logged.

**Comment by jberkel** [comment]
Well, `abort()` does technically crash the app :) 

I use GCDWebServer for integration testing and therefore use debug builds, so always hit this code path.
