### ISSUE TITLE
Redirect Support for SPA's

### ISSUE THREAD

**Issue by bkawk** [swisspol/GCDWebServer#309]
Single page apps often need all requests rewriting to index.html.

With nginx I'd do somthing like

server {
     listen 8080;
     listen [::] 8080;
     root /root/bundled;
 location / {
      try_files $uri $uri/ /index.html;
 }
}
How do I get the same rewrite effect with GCDWebServer

**Comment by swisspol** [comment]
See "Implementing HTTP Redirects" in README for a possible implementation.
