### ISSUE TITLE
Allow background mode running for mobile device

### ISSUE THREAD

**Issue by rhinoid** [swisspol/GCDWebServer#313]
At the moment the webserver doesn't allow the webserver to run in the background of a mobile app (which makes sense).

However, I'm using the webserver when performing UITests for my app. So in that case, the UITests are run on a separate companion app which controls the actual app. So it appears the app is always in the background, but it's running. So to have the webserver embedded in the UITest app, I need it to start even when in backgrounded mode.

**Comment by swisspol** [comment]
It's an iOS problem, not a webserver problem. See the readme file for information about using gcdwebserver in the background and the relevant option. If you create a background task so your app doesn't get suspended it should work.

**Comment by rhinoid** [comment]
Hi I did read that text. However it doesn't apply. Your code checks if the app is in the background and then doesn't even start the webserver. The UITests app is always running in the background when it is performing UITests on the actual app. So no matter what option I submi, the thing will never start (I checked your code and you specifically check if the app is in the background).

When I remove all checks (in your code) and just start the thing, the webserver will work and keep on functioning as UITests apps are never put to sleep by the OS.

So what would be nice is that if there would be some option to 'disableFancyBackgroundChecking' or something.

I'm sorry if I did miss a special option which would work in my case. But as far as I can see it now the webserver won't work without me patching the code

**Comment by swisspol** [comment]
Just use `GCDWebServerOption_AutomaticallySuspendInBackground` to set `NO`, then you can do whatever you want.

**Comment by yustein** [comment]
Hi @swisspol , 

I've read all the documentation but couldn't find a code example of how to set the ```GCDWebServerOption_AutomaticallySuspendInBackground``` to ```NO```

For example, is there an easy way to include it here: ```[_webServer startWithPort:8080 bonjourName:nil];``` no matter what I tried I've been getting compile errors.

Also it would be nice to learn how to enable this in the ```GCDWebUploader``` mode

Of course all above is true for the elusive ```GCDWebServerOption_ConnectedStateCoalescingInterval``` setting which is related to running in the background.

I do appreciate for all the time you have spent for this great project, thank you! 👍

**Comment by rhinoid** [comment]
I did it like this:
        ```
let options: Dictionary<String, Any> = ["Port" : 8080, "AutomaticallySuspendInBackground" : false]
        try! webServer.start(options: options)
```

**Comment by yustein** [comment]
Thank you @rhinoid I'm guessing that is Swift, I was looking for an Obj-C example.

On another note, how do you include the dependencies in Swift?

**Comment by yustein** [comment]
My current code is like this:
```GCDWebServer* _webServer;
    // Create server
    _webServer = [[GCDWebServer alloc] init];
    
    // Add a handler to respond to GET requests on any URL
  
    [_webServer addGETHandlerForBasePath:@"/" directoryPath:NSHomeDirectory() indexFilename:nil cacheAge:3600 allowRangeRequests:YES];
    [_webServer startWithPort:8080 bonjourName:nil];
```
adding ```GCDWebServerOption_AutomaticallySuspendInBackground``` -> ```false``` to this code should be easy but I can't crack it...

I read the files in the core section of the project and there is supposed to be an option to disable access from outside of the phone which is very important because if there was device monitoring the IP numbers for known ports it might download your content from your phone. Where is that option for example?

**Comment by yustein** [comment]
@rhinoid can you share the patched version without background check if possible? Do you have a fork for this on Github?

**Comment by rhinoid** [comment]
Hi Yustein in the end I didn't need the patch since the solution I pasted worked for me.

I see you call the startWithPort method, but you should call the start method instead and supply an NSDictionary with the keys as seen in my example.

**Comment by yustein** [comment]
Hi @rhinoid how can I do that in Obj-C is the problem, your code is in Swift...

**Comment by yustein** [comment]
I figured it out, how difficult was it to include this as an example on the readme page I wonder...
It's all in the correct parameters, a simple example like below can make many people's lives much easier
```
    NSMutableDictionary* options = [NSMutableDictionary dictionary];
    [options setObject:@8080 forKey:GCDWebServerOption_Port];
    //BindToLocalhost set to YES means HTTP server won't accept any connections outside of your device
    [options setObject:@YES forKey:GCDWebServerOption_BindToLocalhost];
    [options setObject:@"" forKey:GCDWebServerOption_BonjourName];
    //below parameter NO makes sure the server runs until iOS stops it in the background
    [options setObject:@NO forKey:GCDWebServerOption_AutomaticallySuspendInBackground];
    //the parameter 2.0 below is in seconds. It is defined as double so you need to have x.x type of a number as the parameter
    [options setObject:@2.0 forKey:GCDWebServerOption_ConnectedStateCoalescingInterval];
    
    GCDWebServer* _webServer;
    // Create server
    _webServer = [[GCDWebServer alloc] init];
    
    [_webServer addGETHandlerForBasePath:@"/" directoryPath:NSHomeDirectory() indexFilename:nil cacheAge:3600 allowRangeRequests:YES];
    [_webServer startWithOptions:options error:nil];
```
