### ISSUE TITLE
didUploadFileAtPath is called before file is totally written

### ISSUE THREAD

**Issue by jiaohaibin** [swisspol/GCDWebServer#315]
ios start WebDAVServer.
Mac Finder connect to WebDAVServer.
Copy a file from Mac to the iOS device.
it seems didUploadFileAtPath is called before file is totally written to iOS file system.
In didUploadFileAtPath, when I try to create an UIImage with the uploaded file path. 0 bytes is found of the uploaded file.
Please move didUploadFileAtPath after the whole file is totally written to iOS file system.

**Comment by swisspol** [comment]
Put a breakpoint in `- (GCDWebServerResponse*)performPUT:(GCDWebServerFileRequest*)request` and trace what happens. I'm suspecting a zero bytes file is being uploaded.

**Comment by jiaohaibin** [comment]
By reading trace the function of GCDWebServerFileRequest, I found didUploadFileAtPath is called twice, one is before file start to write, another is after the file is totally written. If I ignore the didUploadFileAtPath if filesize is 0, my app will run well.
Thanks for your support. I think we can close this issue.
