### ISSUE TITLE
Target name GCDWebServers breaks switching between CoocaPods and Carthage

### ISSUE THREAD

**Issue by kdawgwilk** [swisspol/GCDWebServer#316]
Due to the way that Carthage and CocoaPods detect and name the modules when they are imported making the schemes plural `GCDWebServers` causes problems like so:

```
#ifdef COCOAPODS
    #import <GCDWebServer/GCDWebServer.h>
    #import <GCDWebServer/GCDWebServerConnection.h>
    #import <GCDWebServer/GCDWebServerDataRequest.h>
    #import <GCDWebServer/GCDWebServerDataResponse.h>
    #import <GCDWebServer/GCDWebServerErrorResponse.h>
    #import <GCDWebServer/GCDWebServerFileRequest.h>
    #import <GCDWebServer/GCDWebServerFileResponse.h>
    #import <GCDWebServer/GCDWebServerFunctions.h>
    #import <GCDWebServer/GCDWebServerHTTPStatusCodes.h>
    #import <GCDWebServer/GCDWebServerMultiPartFormRequest.h>
    #import <GCDWebServer/GCDWebServerStreamedProxyResponse.h>
    #import <GCDWebServer/GCDWebServerStreamedResponse.h>
    #import <GCDWebServer/GCDWebServerURLEncodedFormRequest.h>
#else
    #import <GCDWebServers/GCDWebServer.h>
    #import <GCDWebServers/GCDWebServerConnection.h>
    #import <GCDWebServers/GCDWebServerDataRequest.h>
    #import <GCDWebServers/GCDWebServerDataResponse.h>
    #import <GCDWebServers/GCDWebServerErrorResponse.h>
    #import <GCDWebServers/GCDWebServerFileRequest.h>
    #import <GCDWebServers/GCDWebServerFileResponse.h>
    #import <GCDWebServers/GCDWebServerFunctions.h>
    #import <GCDWebServers/GCDWebServerHTTPStatusCodes.h>
    #import <GCDWebServers/GCDWebServerMultiPartFormRequest.h>
    #import <GCDWebServers/GCDWebServerStreamedProxyResponse.h>
    #import <GCDWebServers/GCDWebServerStreamedResponse.h>
    #import <GCDWebServers/GCDWebServerURLEncodedFormRequest.h>
#endif
```

Carthage imports the module using the plural form and CocoaPods doesn't

**Comment by kdawgwilk** [comment]
Making a change to fix this would break anyones code who was using Carthage previously so I am guessing this change will unlikely to be made

**Comment by swisspol** [comment]
I don't understand what's the practical problem here?

**Comment by kdawgwilk** [comment]
The if check with the imports isn't very practical.  It would be nice if things were consistent and were named the same no matter what depend your manager you use

**Comment by swisspol** [comment]
I don't understand why you have this problem in the first place? What's the exact use case?

**Comment by kdawgwilk** [comment]
We have a library that depends on GCDWebServer that needs to support both CocoaPods and Carthage and we have to change the imports based on what dependency manager is being used with our library

**Comment by swisspol** [comment]
There was a reason at the time why it had to be done like this - I don't remember however. Like you said it's unlikely to be changed. Besides, the problem you have is an edge case.

**Comment by JanC** [comment]
Hi,
fyi, I have the same problem. I work on a library that has a dependency on GCDWebServer. I want to support both Cocoapods and Carthage and I also have to do those `#ifdef` imports of GCDWebServer

**Comment by FredrikSjoberg** [comment]
Hello!

I'll add my name to the list. The naming discrepancy is causing some headache.
