### ISSUE TITLE
need a new release

### ISSUE THREAD

**Issue by jiaohaibin** [swisspol/GCDWebServer#318]
Hi Swisspol,

It seems the latest released version is 3.3.3, which was released on Jul 16, 2016.
Since this release there are many new commits on the main branch.
Could you please prepare a new release with a newer and stable node on main branch? it will help us to get a newer version easier by just use cocoapod.

in GCDWebServer.podspec we can see the following information.
Pod::Spec.new do |s|
  s.name     = 'GCDWebServer'
  s.version  = '3.3.4'

But in https://github.com/swisspol/GCDWebServer/releases, 3.3.3 is the latest release.
Which version is correct?

I have already done pod update, but my local version is still 3.3.3.

Best Regards,
Haibin

**Comment by swisspol** [comment]
Done

**Comment by jiaohaibin** [comment]
Thanks a lot
