### ISSUE TITLE
404 should be returned for non existing URLs

### ISSUE THREAD

**Issue by benjamingr** [swisspol/GCDWebServer#322]
Currently the server returns `405 METHOD NOT ALLOWED` on URLs where a handler for the given method is not allowed.

> The method specified in the Request-Line is not allowed for the resource identified by the Request-URI. The response MUST include an Allow header containing a list of valid methods for the requested resource.

GCDWebServer does not include an "Allow" header in the response.

A more correct and standard behavior would be to return a `404 NOT FOUND` response instead.

This behavior made it hard for me to find a bug in my code.

Thanks for the great library!

**Comment by swisspol** [comment]
Fixed by 6ed51907da045881d3ec19a0e93b0447caddc30d

**Comment by benjamingr** [comment]
Thanks!
