### ISSUE TITLE
Warning when deleting a file in GCDWebUploader

### ISSUE THREAD

**Issue by brendand** [swisspol/GCDWebServer#323]
Is there a way to add a warning so that if the user clicks the trash can button next to an item in the list on the GCDWebUploader interface, they will be presented with a warning to verify they want to delete the item? It's far too easy to accidentally delete an item clicking the trash can button.

**Comment by brendand** [comment]
Answering my own question, this seems to be the thing to do in the index.js file:

```
    $(".button-delete").click(function(event) {
      var path = $(this).parent().parent().data("path");
	  var result = confirm("Are you sure you wish to delete: " + path + "?");
	  if (result) {
		  //Logic to delete the item
		  $.ajax({
			 url: 'delete',
			 type: 'POST',
			 data: {path: path},
			 dataType: 'json'
			 }).fail(function(jqXHR, textStatus, errorThrown) {
					 _showError("Failed deleting \"" + path + "\"", textStatus, errorThrown);
			 }).always(function() {
			   _reload(_path);
		   });
	  }
      
    });
```

**Comment by swisspol** [comment]
Indeed just modify the JavaScript as needed.
