### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by TomasHubelbauer** [swisspol/GCDWebServer#324]
Hello, sorry I am a Swift noob so this is probably not a GCDWebServer specific question, but I don't run into this with any other of my Pods. Is it possible to disable the output messages GCDWebServer produces or gain greater programmatic control over them so I can selectively supress some?

I have a polling call in my application and it just makes the output totally unusable seeing the same log all the time with just a different timestamp.

I suppose I need to undefine `DEBUG` just for this pod somehow?

**Comment by swisspol** [comment]
See setLogLevel method.
