### ISSUE TITLE
Mac OS X App freeze, stuck, unresponsive - Sandboxed

### ISSUE THREAD

**Issue by atoxx** [swisspol/GCDWebServer#325]
I add nearly basic Sample Code from the Wiki, all the magic happens in the handler, but after launch, i come this far:

[DEBUG] Did open IPv4 listening socket 5
[DEBUG] Did open IPv6 listening socket 6
[INFO] GCDWebServer started on port 8080 and reachable at http://192.168.178.32:8080/

Than the App is stuck and does not respond anymore

**Comment by swisspol** [comment]
You should study the example Mac app included in the project.

**Comment by shixueqian** [comment]
I think I have the same issue as you.I am new for MacOS develop.
How to solve this problem？
Or it cannot work with Mac APP?
