### ISSUE TITLE
Use GCDWebServer to intercept http requests with relative URLs inside WKWebView on cellular network

### ISSUE THREAD

**Issue by jiakanwang** [swisspol/GCDWebServer#331]
I'm working on a platform that hosts many HTML5 apps and games. I'm trying to implement a resource disk caching solution for these apps/games. Because the apps/games are hosted inside a WKWebView, all the http requests besides the initial landing page happen inside the WKWebView with relative URLs cannot be intercepted because they are out of process.

So I'm using GCDWebServer to run a local web server, and change the initial web request's URL to http://<GCDWebServer's URL>/index.html. This way, all the subsequent http requests will come to the web server first, and it will then be able to cache and serves cached data back to the WKWebView.

It all worked well until I switched to cellular network, because apparently on cellular GCDWebServer's URL is nil. So basically the app/games won't be able to run when the user is
1) initially on WIFI but then switched to cellular, or
2) is on cellular to begin with

1) is a bigger problem because the app/game will suddenly stop running on switching network. For 2) I guess worst case I can just not use cache when on cellular, which is still not ideal but not the end of the world.

Is there any possible solution that I can give a try? Thanks a ton!

**Comment by swisspol** [comment]
Can't you just use http://localhost?

**Comment by jiakanwang** [comment]
@swisspol oh thanks a lot for the suggestion (and creating this awesome project). I just gave it a try and looks like it works! It may seem to be obvious but I'm super new to networking so I didn't even know this was an option, was trying to find out if there is an internal private IP address that doesn't change so that I can use it. Thanks so much again!!!
