### ISSUE TITLE
The memory is very high！！！

### ISSUE THREAD

**Issue by dluffymonkey** [swisspol/GCDWebServer#336]
When I used the songs in itunes, I opened the address in the browser and played the songs on itunes, and the memory was so high that I couldn't get it down。Each time i request a new song in the browser, memory increases about 10M，this is a serious problem，Please solve this problem。

Use GCDWebServer and GCDWebDAVServer。

    - (void)writeData:(NSData*)data withCompletionBlock:(WriteDataCompletionBlock)block {
         dispatch_data_t buffer = dispatch_data_create(data.bytes, data.length, dispatch_get_global_queue(_server.dispatchQueuePriority, 0), ^{
          [data self];  // Keeps ARC from releasing data too early
        });
  
    dispatch_write(_socket, buffer, dispatch_get_global_queue(_server.dispatchQueuePriority, 0), ^(dispatch_data_t remainingData, int error) {

    
    if (error == 0) {
      GWS_DCHECK(remainingData == NULL);
      [self didWriteBytes:data.bytes length:data.length];
      block(YES);
      
    } else {
      GWS_LOG_ERROR(@"Error while writing to socket %i: %s (%i)", _socket, strerror(error), error);
      block(NO);
    }

      });
  
    #if !OS_OBJECT_USE_OBJC_RETAIN_RELEASE
      dispatch_release(buffer);
    #endif
    }

**Comment by swisspol** [comment]
How do you even connect iTunes to gcdwebserver?

**Comment by dluffymonkey** [comment]
Read access files through GCDWebDAVServer. Memory is high and cannot be freed
