### ISSUE TITLE
How can I minimize the overhead when using GCDWebServer as a proxy server to serve cache for HTML5 games hosted inside WKWebView

### ISSUE THREAD

**Issue by jiakanwang** [swisspol/GCDWebServer#337]
I'm working on a platform that hosts HTML5 apps and games inside a WKWebView. I'm using GCDWebServer as a proxy server, so that http requests can be intercepted and disk cache of game resources can be served.

I did some performance profiling for game loading yesterday, and found that the overhead of having the proxy server respond back with either GCDWebServerFileResponse or GCDWebServerDataResponse seems to be too much, that even when all resources are cached on disk, loading time is still obviously longer than if I just let WKWebView ask the remote CDN for resources. If I still use GCDWebServer, but simply redirect all the requests to the CDN, the performance is about the same as if I don't use the proxy server. So I think the majority of the overhead is in using file response or data response. What are some ways to minimize the overhead? Here is some code snippet in case I did something wrong:

Here I add the handler:
```
  __weak typeof(self) weakSelf = self;
  [_webServer addDefaultHandlerForMethod:@"GET"
                            requestClass:[GCDWebServerRequest class]
                       asyncProcessBlock:^(GCDWebServerRequest *request, GCDWebServerCompletionBlock completionBlock) {
                         dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0), ^{
                           [weakSelf _processRequest:request completionBlock:completionBlock];
                         });
                       }];
```

Then find the cache and use cache if exists:
```
//! @abstract Process request by caching and serving caching when cache is already available.
- (void)_processRequest:(GCDWebServerRequest *)request completionBlock:(GCDWebServerCompletionBlock)completionBlock
{
  NSString *cacheKey = [self _cacheKeyForURL:request.URL];

  __weak typeof(self) weakSelf = self;
  [_gameCache fetchCachedResourceForKey:cacheKey
                           successBlock:^(NSString *_Nonnull cacheFilePath) {
                             // If cache exists, just serve the cached file.
                             completionBlock([GCDWebServerFileResponse responseWithFile:cacheFilePath]);
                           } failureBlock:^{
                             // If cache does not exist, get the original request URL, and get response from CDN.
                             // Then serves the response and cache it asynchronously.
                             [weakSelf _sendRequest:request cacheKey:cacheKey completionBlock:completionBlock];
                           }];
}
```

And here is the function that's called when there is a cache miss, basically it will get response from the CDN, and serve the data back, then cache it on the disk asynchronously:
```
- (void)_sendRequest:(GCDWebServerRequest *)request cacheKey:(NSString *)cacheKey completionBlock:(GCDWebServerCompletionBlock)completionBlock
{
  NSMutableURLRequest *originalRequest = [self _originalRequestForRequest:request];

  NSString *gameID = [_gameID copy];
  NSError *error = nil;
  NSHTTPURLResponse *response = nil;

  NSData *responseData = [NSURLConnection sendSynchronousRequest:originalRequest returningResponse:&response error:&error];
  completionBlock([GCDWebServerDataResponse responseWithData:responseData contentType:response.MIMEType]);

  // write to cache asynchorously in background thread
}
```

Initially I thought it was the cache seeking part that was slow, but even if I don't use the cache but only call `_sendRequest`, it's still slow. If I only do `responseWithRedirect` inside `_sendRequest`, then it's not slower, but obviously that's not what I want to do. Would really appreciate some suggestions on what I should do/try. Thanks a lot!

**Comment by swisspol** [comment]
I suggest you start by timing every step of your proxy architecture and log how long each step takes. Also compare speed for tiny requests, medium and large ones. Try changing the logic a bit and see how number evolves. Look for things that don’t make sense e.g. loading a 1mb file from disk taking longer than downloading it from the network. Also check timing WebKit side: maybe things get paused there for some reason. Good Luck!

**Comment by mcorner** [comment]
@jiakanwang Did you ever find anything here?  I have something similar going on.  In my case the embedded server is slightly faster than a CDN on a fast network, but even faster would be better.  GCD lacks keep-alive, which slows things down a bit.  Nanohttpd (we use this on Android) has keep-alive so it avoids connection overhead.
