### ISSUE TITLE
Revisit prototype declaration warning

### ISSUE THREAD

**Issue by joseph** [swisspol/GCDWebServer#342]
Xcode 9 is out of beta and the "This function declaration is not a prototype" warning still occurs. Should we revisit this PR?

https://github.com/swisspol/GCDWebServer/pull/311

**Comment by scottcarter** [comment]
I am also seeing this in GCDWebServerPrivate.h.  It is complaining about the line:

extern void GCDWebServerInitializeFunctions();

I'm using GCDWebServer release 3.4.1  with Xcode 9.0.
