### ISSUE TITLE
GCDWebServer does not consist with CocoaLumberjack in pod

### ISSUE THREAD

**Issue by linushao** [swisspol/GCDWebServer#347]
when pod GCDWebServer and CocoaLumberjack together
in GCDWebServerPrivate.h, line93. 
Building the project, it will occur an error show that 
> Cannot #include files inside '#pragma clang assume_nonnull'

**Comment by swisspol** [comment]
Use version 3.4.1 or later

**Comment by linushao** [comment]
thank you, it works, I just searched in pod and it show the newest version is 3.4 last week
