### ISSUE TITLE
xcode 9.1 show warning [UIApplication applicationState] must be used from main thread only

### ISSUE THREAD

**Issue by waidp521** [swisspol/GCDWebServer#349]
![2017-11-30 10 51 52](https://user-images.githubusercontent.com/12133969/33410722-8d77efd0-d5bc-11e7-9f82-5f32df0f3550.png)
How to resolve this warning?

**Comment by swisspol** [comment]
Don’t call gcdwebserver start method from elsewhere than the main thread I guess.
