### ISSUE TITLE
Error on Building Ambiguous use of 'init(HTML:)'

### ISSUE THREAD

**Issue by solancer** [swisspol/GCDWebServer#351]
Unable to find any documentation on how to use the HTML response method for swift. The current readme file seems to cover only objective-c based examples.

![screen shot 2017-12-07 at 7 09 34 am](https://user-images.githubusercontent.com/800668/33694514-98a2ec5e-db1e-11e7-89eb-2de73ba44f8d.png)

And upon changing to 

`return GCDWebServerDataResponse(text:"<html><body><p>Hello World</p></body></html>")`

the build runs but the server fails to start 

![screen shot 2017-12-07 at 7 27 35 am](https://user-images.githubusercontent.com/800668/33694812-24df8dc0-db20-11e7-9341-370984c8e386.png)

**Comment by blld** [comment]
`GCDWebServerDataResponse(html: "<html><body><p>Hello World</p></body></html>")`

does work (lowercase)
