### ISSUE TITLE
Crash when initWithJSONObject:  nil

### ISSUE THREAD

**Issue by waidp521** [swisspol/GCDWebServer#354]
GCDWebServerDataResponse.m     
![2017-12-21 10 12 05](https://user-images.githubusercontent.com/12133969/34237409-84c5979e-e637-11e7-8bb4-72f21609ac8d.png)
when the object = nil   in swift , [NSJSONSerialization dataWithJSONObject:object options:0 error:NULL];  will crash,  please fix it, thanks.

**Comment by swisspol** [comment]
Passing nil is not supported. The object argument is not nullable.
