### ISSUE TITLE
GCDWebUploader.serverURL return Wrong Ip address

### ISSUE THREAD

**Issue by moontecholabs** [swisspol/GCDWebServer#355]
we have implemented GCDWebuploader in our ios app.some time GCDWebUploader.serverURL
return ipaddress that does not work. for example 169.254.1.23

and when we try to upload file using above ip address it gives error 
![preview-full-screen shot 2017-12-20 at 3 39 40 pm](https://user-images.githubusercontent.com/18573842/34318855-5c77bef4-e7f7-11e7-96ab-acccce5daf64.png)

**Comment by swisspol** [comment]
The IP address is simply the one of your device, which you can verify. Make sure the app is running and in the foreground. Finally make sure your WiFi network doesn't block communications on port 80.

**Comment by moontecholabs** [comment]
Thanks for your help.

**Comment by moontecholabs** [comment]
@swisspol one more Question.is it work in cellular data rather than wifi?
