### ISSUE TITLE
GCDWeb Uploader not work on mobile data

### ISSUE THREAD

**Issue by moontecholabs** [swisspol/GCDWebServer#356]
When we try to upload file using GCDWebUploader Works fine.but when we try to do same thing using mobile or celluer data nothing is happen.

**Comment by tzahola** [comment]
Does your mobile service provider let through incoming TCP connections? You should try reaching the device through VPN. If it works on VPN, then it means that your provider blocks incoming connections to your phone. Service providers commonly to put you behind NAT if you're not subscribed to a more expensive "dedicated" package.

**Comment by moontecholabs** [comment]
thanks for your reply we will check and update soon.

**Comment by swisspol** [comment]
This is very unlikely to work as indeed carriers don’t let you run servers on your phones!
