### ISSUE TITLE
Can't change data of GCDWebServerDataResponse after first starting

### ISSUE THREAD

**Issue by AEiosApp** [swisspol/GCDWebServer#357]
I'm using GCDWebServer to serve vector map tiles from a localhost of my iOS app (mapGL library).
I'm using addDefaultHandlerForMethod to prepare response 

`- (void)myMapInit:(NSString *)mapFile {

    self.webServer = [[GCDWebServer alloc] init];

    if( [self.webServer isRunning] ) {
        [self.webServer removeAllHandlers];
    }

    // Add a handler to respond to PBF GET requests
    [self.webServer addDefaultHandlerForMethod:@"GET"
                                  requestClass:[GCDWebServerRequest class]
                                  processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {
                                      NSString *requestPath = [request.path substringFromIndex:1];
                                      
                                      NSString *zipPath = [[NSBundle mainBundle] pathForResource:mapFile ofType:@"zip"];
                                      
                                      
                                      OZZipFile *unzipFile= [[OZZipFile alloc] initWithFileName:zipPath
                                                                                           mode:OZZipFileModeUnzip];
                                      
                                      [unzipFile locateFileInZip:requestPath];
                                      
                                      OZFileInZipInfo *info= [unzipFile getCurrentFileInZipInfo];
 
                                      // Expand the file in memory
                                      OZZipReadStream *read= [unzipFile readCurrentFileInZip];
                                      NSMutableData *data= [[NSMutableData alloc] initWithLength:info.length];
                                      [read readDataWithBuffer:data];
                                      [read finishedReading];
                                      
                                      return [GCDWebServerDataResponse responseWithData:data contentType:@"application/x-protobuf"];
                                  }];
    
    // Start server on port 8080
    [self.webServer startWithPort:8080 bonjourName:nil];   
}`

I'm calling myMapInit function (name of *.zip file with tiles is an argument)  and after the start, everything working fine.

But after it, I need to change data source, so I'm calling this function again with a different argument. I'm removing all handlers and add a addDefaultHandlerForMethod once again, but the map still shows initial source.

Any ideas, what can be wrong and why I'm always getting the data that was loaded first time?

**Comment by swisspol** [comment]
Check the Xcode log for any errors. It’s possible the previous servers are still running since you never stop them. I would recommend against creating a new server each time. You can simply have the GET handler lookup the map file to serve from an instance variable or something.

**Comment by AEiosApp** [comment]
Hi, thanks for the suggestion.
Actually, this is how I've got to manage it.
For each map data source, I've launched separate web server (localhost:8080, localhost:8081 etc.)
