### ISSUE TITLE
Separate IPv4 socket is unnecessary

### ISSUE THREAD

**Issue by tzahola** [swisspol/GCDWebServer#358]
https://github.com/swisspol/GCDWebServer/blob/47ed2cc593ec1130fc7884464917756566d7ef86/GCDWebServer/Core/GCDWebServer.m#L550

It's redundant to create separate `PF_INET` and `PF_INET6` sockets. A single `PF_INET6` socket will listen on both IPv4 and IPv6 (unless you turn on the `IPV6_V6ONLY` option, which you don't). IPv4 clients will appear as [IPv4-mapped IPv6 addresses](https://www.ibm.com/support/knowledgecenter/en/SSLTBW_2.1.0/com.ibm.zos.v2r1.hale001/ipv6d0031001726.htm).

**Comment by swisspol** [comment]
Thanks for suggestion. I don’t changing this though since the current implementation works well.
