### ISSUE TITLE
Server stops loading assets when AutomaticallySuspendInBackground is set to false and sleeps

### ISSUE THREAD

**Issue by august25** [swisspol/GCDWebServer#359]
1. I set AutomaticallySuspendInBackground to false, I'm serving files from the app's documents folder
2. Launch the app
2. Put my device to sleep, wait 10 seconds 
3. Open the app and the original loaded assets are fine, but when I try to load new asset It returns 404

Server says it's running, and if I ran the same thing without the AutomaticallySuspendInBackground flag, it runs fine.

`self.webServer.start(options: ["Port": port, "BindToLocalhost": true, "AutomaticallySuspendInBackground" : false])`

**Comment by swisspol** [comment]
That’s correct, that’s the very definition of what this option does. See README.

**Comment by august25** [comment]
Sorry if I misunderstood and thanks for the quick response, but If I was to return to the app, shouldn't it continue to work and serve the files including new assets? Or how do I get it to behave as I'm expecting again? It just seems odd that the expected behaviour is that the server doesn't serve the files anymore once I return to the app.

**Comment by swisspol** [comment]
My bad, I thought you were attempting to read from the server after 10 seconds while still in background.

It returns 404 because the path doesn’t exist, so you either deleted the file or not setting up the handlers correctly maybe. Check for errors in the Xcode console and use the debugger to trace what happens inside your handler.

**Comment by august25** [comment]
OK thanks, I'll continue to do some more digging, the files are definitely still there, because when I set remove AutomaticallySuspendInBackground...essentially setting it to true, it works fine as expected.

**Comment by august25** [comment]
Apologies, it seems to not be able to connect to the server, not returning a 404.

<img width="1001" alt="screen shot 2018-01-23 at 12 02 23 am" src="https://user-images.githubusercontent.com/2336139/35258952-de380f66-ffd0-11e7-8af6-b391d0462eca.png">

**Comment by august25** [comment]
@swisspol is the above expected behaviour?

**Comment by tomtaylor** [comment]
I think I'm seeing the same behaviour here. I run my app, background it, resume after 60s, and navigate to a new URL. The server no longer responds, and I get the following error on navigation:

```
Provisional navigation error Error Domain=NSURLErrorDomain Code=-1004 "Could not connect to the server." UserInfo={NSUnderlyingError=0x280d18e70 {Error Domain=kCFErrorDomainCFNetwork Code=-1004 "(null)" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <134EE160-9D7C-42BA-BC40-23BE952197B5>.<18>, NSErrorFailingURLKey=http://localhost:1234/groups/*redacted*/topics/*redacted*, NSLocalizedDescription=Could not connect to the server., _WKRecoveryAttempterErrorKey=<WKReloadFrameErrorRecoveryAttempter: 0x28030cdc0>, NSErrorFailingURLStringKey=http://localhost:1234/groups/GPV7UKWSL/topics/TCQBVAAC7, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=61}
```

**Comment by gauravrane2212** [comment]
@swisspol I am seeing the same error messages `Failed to load resource: Could not connect to the server` too. Is there a way to detect when the server becomes unresponsive after coming from the background? 

As a workaround, for now, I am re-instantiating the gcdwebserver when I come from background to foreground manually. Not sure if that is the way to go about it
