### ISSUE TITLE
Can GCDWebServer return image on server?

### ISSUE THREAD

**Issue by hzhou81** [swisspol/GCDWebServer#361]
I'm using [GCDWebServerDataResponse responseWithHTML:@"<html><body>< img src='hello.jpg'/></body></html>"]; to response a html to http client, can GCDWebServer return img tag ?

**Comment by swisspol** [comment]
You can't return a "tag". You return content for URL paths e.g. `< img src='hello.jpg'/>` for `/test.html` path.

I advise you to simply use https://github.com/swisspol/GCDWebServer#serving-a-static-website if you're not familiar with how HTTP and HTTP servers work.
