### ISSUE TITLE
How to initialize GCDWebServer

### ISSUE THREAD

**Issue by rangav** [swisspol/GCDWebServer#362]
Hi

I am building a video streaming iOS app to TV, Its not clear what is best to initialize GCDWebServer. I also need to keep server alive for few minutes after the app is in background to continue streaming.

What is the best option:

1. Initialize in appdelegate once and how to get server url from view and when server url changes how to get new new url.
2. Should i use singleton to initialize gcdwebserver from static class.
3. OR initialize a new gcdwebserver in viewDidLoad every time the view is browsed? 

Note: i don't need multiple server instances, videos will streamed only from one view.

Appreciate your suggestions.

**Comment by swisspol** [comment]
Any option will work as long as the GCDWebServer instance is alive for the duration of the app lifecycle. Having it a member of the `AppDelegate` is usually the simplest.

You can fetch and display `-serverURL` property whenever the user comes back to your app.
