### ISSUE TITLE
Communication between a http server and https server will be secured?

### ISSUE THREAD

**Issue by Srinivasp** [swisspol/GCDWebServer#363]
I am trying to implement an HTTP server inside an iOS app. I could see similar apps in the app store. But in my case, embedded HTTP server has to communicate with external HTTPS Server. So now, 
is the communication secured? Or do I need to implement HTTPS server, instead?

Is it possible to implement an HTTPS server in iOS app? Will Apple reject this approach?

Thanks in Advance

**Comment by swisspol** [comment]
GCDWebServer is only to implement an HTTP web server, it’s not to talk to an HTTP web server. Use the URL APIs for that.

Gcdwebserver does not implement HTTPS.

**Comment by SmilerTom** [comment]
How do you deal with HTTPS?
Thanks in Advance
