### ISSUE TITLE
Failed Starting Bonjour resolution...

### ISSUE THREAD

**Issue by bharathreddy-97** [swisspol/GCDWebServer#364]
When i leave my app running for some time I get above mentioned crash while using GCDWebServer. I am getting crash in this method _NetServiceRegisterCallBack and following is the log 
```
[DEBUG] Did disconnect
[DEBUG] Did end background task
[VERBOSE] Bonjour registration complete for GCDWebServer
[INFO] GCDWebServer now locally reachable at http://<MySystem>.local:5555/
[VERBOSE] Bonjour registration complete for GCDWebServer
[ERROR] Failed starting Bonjour resolution
```
What might be the issue? version is 3.4.2

**Comment by swisspol** [comment]
Is there anything else in the Xcode log? What’s the exact Bonjour error? Which devices and OSes are affected?

**Comment by ahmedmukbil** [comment]
was anyone able to fix this ?

**Comment by alekop** [comment]
Just saw that on a iPhone 6 Plus, iOS 12.1.

**Comment by WangGuibin** [comment]
```objc
[VERBOSE] Bonjour registration complete for GCDWebDAVServer
[INFO] GCDWebDAVServer now locally reachable at http://iPhone-2.local:9966/
[VERBOSE] Bonjour registration complete for GCDWebDAVServer
[ERROR] Failed starting Bonjour resolution
(lldb) 
```
I also encountered this crash  problem.

**Comment by mingjunLi2009** [comment]
I found that this just appear for debug.
![image](https://user-images.githubusercontent.com/13762058/65405246-1e411180-de0e-11e9-9d46-3c22c949a740.png)
this use abort()

**Comment by mingjunLi2009** [comment]
> I found that this just appear for debug.
> ![image](https://user-images.githubusercontent.com/13762058/65405246-1e411180-de0e-11e9-9d46-3c22c949a740.png)
> this use abort()

comment this line,example:
![image](https://user-images.githubusercontent.com/13762058/65405644-58f77980-de0f-11e9-9401-95467ff28126.png)
