### ISSUE TITLE
Searching for default index.html file

### ISSUE THREAD

**Issue by dev-journey** [swisspol/GCDWebServer#365]
Using GCDWebServer to hold a static site in my app, I can open on a WKWebview instance the main html by:
```swift
let documentsUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
let htmlTmp = documentsUrl.appendingPathComponent("root/")
let server = GCDWebServer()
server.addGETHandler(forBasePath: "/", directoryPath: htmlTmp.path, indexFilename: "index.html", cacheAge: 0, allowRangeRequests: true)
server.start(withPort: 9990, bonjourName: nil)
webview.load(URLRequest(url: URL(string: "http://127.0.0.1:9990/")!))
```
But when inner web calls are to root/resources/content/  (without index.html after content/) nothing happens. It's possible to add handler that redirect all those "/" calls to "/index.html"?

**Comment by swisspol** [comment]
Yes, see README for examples.

**Comment by 18734791527** [comment]
<img width="1440" alt="屏幕快照 2019-06-02 20 32 46" src="https://user-images.githubusercontent.com/19185361/58761638-1caabf80-8579-11e9-8f39-440bbf4c91b8.png">
<img width="274" alt="屏幕快照 2019-06-02 20 33 28" src="https://user-images.githubusercontent.com/19185361/58761639-1f0d1980-8579-11e9-94f3-2a8748cf28fd.png">
<img width="1440" alt="屏幕快照 2019-06-02 20 53 22" src="https://user-images.githubusercontent.com/19185361/58761640-203e4680-8579-11e9-95e5-62c6d1e7adea.png">
Help！Do you have this problem.
