### ISSUE TITLE
Simulate server error

### ISSUE THREAD

**Issue by PhilCai1993** [swisspol/GCDWebServer#370]
I'm using CGDWebServer as a local http server for UI/WKWebView in my apps. But I have trouble simulating errors such as 404, 500 and other server errors. And take UIWebView for example, even if I 
return a response like `[GCDWebServerErrorResponse responseWithClientError:kGCDWebServerHTTPStatusCode_NotFound message:@"??"]`; The webview's delegate `- (void)webView:(UIWebView *)webView didFailLoadWithError:(NSError *)error` is not called, instead, `webViewDidFinishLoad:` is called.

**Comment by swisspol** [comment]
Check if a desktop web browser or with curl that your are getting a 4xx or 5xx. If you do then that’s a WebView API misuse. Otherwise your handler is not implemented correctly.

**Comment by PhilCai1993** [comment]
The weird thing is, if I make the request with NSURLSession and inspect the response, I could find the 4xx/5xx statusCode, but when using UI/WKWebView, not any error delegate method would get called.
