### ISSUE TITLE
Can I create several web servers in different private addresses?

### ISSUE THREAD

**Issue by Ricardo1980** [swisspol/GCDWebServer#383]
Hello,

I created an iOS network extension (VPN tunnel) that filters DNS and blocks several domains depending on categories.

Right now to block a website, I send a modified DNS answer (when I receive a DNS query) that points to a local web server with a web page that says  "Content blocked".

It works fine, surprisingly well.

But now I would like to have 4 or 5 categories, like "Adult content blocked", "Gambling", "Fake news"...

So, my idea is to have 4 or 5 web servers instead of one and run bind each one to a different private IP address. And when I block the domain, depending on the category, I point to the proper web server to inform about the proper category.

Reading GCDWebServer code I don't see how to bind to a specific private address. 
Can I do it?

Thanks a lot.

**Comment by swisspol** [comment]
There's no option to specify the IP address to bind, so you would need to
fork the project and add one. Then you can create as many servers as you
want.

See GCDWebServerOption_BindToLocalhost for a starting point.

**Comment by Ricardo1980** [comment]
Thanks!
I will check that!
