### ISSUE TITLE
Error when stop the server

### ISSUE THREAD

**Issue by prsolucoes** [swisspol/GCDWebServer#384]
Hi,

When my ViewController enter in background, i stop the server, but sometimes is crash because is going to abort method.

```
@objc override func handleAppWillResignActiveNotification(notification: Notification) {
    super.handleAppWillResignActiveNotification(notification: notification)        
    stopServer()
}

func stopServer() {
    webServer?.stop()
    EZRLogger.shared()?.d("Webserver stopped")
}
```

The error is caused when abort method is called:

![image](https://user-images.githubusercontent.com/395096/43905770-20898712-9bc8-11e8-97c0-0d5f38b39ded.png)

Can anyone help me with this?

**Comment by prsolucoes** [comment]
Hi,

I solve it checking if it is running before stop.

```
func stopServer() {
        if let webServer = webServer {
            if webServer.isRunning {
                webServer.stop()
            }
        }
        
        EZRLogger.shared()?.d("Web server stopped")
}
```

Reading the source i see that the code clean the options inside "stop" method. The second "stop" call will crash because "options" = nil. So checking if it is running, will prevent call stop if i dont cal start before.

**Comment by swisspol** [comment]
This crash will only happen when building your app in Debug mode. It’s a programmer error to call stop() if the server is not running,
