### ISSUE TITLE
Server to run in background

### ISSUE THREAD

**Issue by rlabr** [swisspol/GCDWebServer#386]
Hi I am trying to use the server and collect data from another device even in background. To achieve this I am using GCDWebServerOption_AutomaticallySuspendInBackground  = false

> While the app is in the background, as long as new HTTP connections keep being initiated, the background task will continue to exist and iOS will not suspend the app 
                                                                                          - I have a get request every 2 minutes to hit server. but still app gets closed. Guide me Please.

**Comment by swisspol** [comment]
iOS will always suspend the app after 10 minutes or so, sometimes earlier. There’s unfortunately no way around it (unless you try to cheat and for instance record audio and set the corresponding key in info.plist but it goes against the App Store rules).

**Comment by ComputerGuruInTraining** [comment]
I have found the background app crash to occur on a new android as well. I have found it doesn't definitely occur after 10 minutes on iPhone6s. It can be up to 45 minutes later.
