### ISSUE TITLE
Can the documentation add an example of authentications?

### ISSUE THREAD

**Issue by jiazen** [swisspol/GCDWebServer#388]
Best to have a swift version

**Comment by swisspol** [comment]
When creating the gcdwebserver instance, pass the option GCDWebServerOption_AuthenticationMethod set to GCDWebServerAuthenticationMethod_Basic or GCDWebServerAuthenticationMethod_DigestAccess and finally also pass the option GCDWebServerOption_AuthenticationAccounts set to a dictionary of accounts and passwords e.g. {@“myaccount”: @“mypassword”} in objc.

**Comment by jiazen** [comment]
thank you very much!
