### ISSUE TITLE
how to use for keyboard extension？

### ISSUE THREAD

**Issue by suwenclub** [swisspol/GCDWebServer#389]
keyboard extension can not use UIApplication class，can you support GCDWebServer for keyboard extension?

**Comment by swisspol** [comment]
You would need to modify the source code to remove dependencies on forbidden uikit classes.

**Comment by zhihuitang** [comment]
I have the same question. @suwenclub , have you figured out how to remove dependencies on forbidden uikit classes?

**Comment by zhihuitang** [comment]
OK, I figured it out. keyboard extension works if `AutomaticallySuspendInBackground` is disabled by start it in this way:

```
webServer.start(options: [GCDWebServerOption_AutomaticallySuspendInBackground: false])
```
