### ISSUE TITLE
Base URL is null with LTE / 3G / IPv6 Wifi network It says can’t connect to server

### ISSUE THREAD

**Issue by cisruchir** [swisspol/GCDWebServer#390]
Hello Team,

I am facing issue in GCD WebServer. It is working fine with our IPv4 network over Wifi. But it is creating issue with LTE/3G/IPv6 Wifi. On this network it shows base url as null. So we are not able to connect.

Here I am sharing logs.
```

> 2018-09-14 16:15:39.188140+0530 IOSwebServer[257:7162] Array Diff : (null)
> [DEBUG] Did open IPv4 listening socket 15
> [DEBUG] Did open IPv6 listening socket 16
> [INFO] GCDWebServer started on port 80 and reachable at (null)

```
Please suggest solution for the same.

Thank You :)

**Comment by swisspol** [comment]
GCDWebServer is not designed to work over cell networks since don’t let people run servers on their phones, so this function returns null in this case:
https://github.com/swisspol/GCDWebServer/blob/a5548938448c7a197996609c4b7d6592117b9d22/GCDWebServer/Core/GCDWebServerFunctions.m

**Comment by bao-lei** [comment]
Hi swisspol,

I am trying to get GCDWebServer work over a cellular network too. Can you point me to a workaround maybe?

Thanks!
