### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by epsilonxe** [swisspol/GCDWebServer#393]
I try with this

```
let webServer = GCDWebServer()
    
        webServer.addDefaultHandler(
            forMethod: "GET",
            request: GCDWebServerRequest.self,
            processBlock: { request in
                return GCDWebServerDataResponse(
                    html:"<html><body><p>Hello World</p></body></html>"
                )      
            }
        )
        
        webServer.run(withPort: 8080, bonjourName: "GCD Web Server")
        
        print("Visit \(String(describing: webServer.serverURL)) in your web browser")
    }
```
and get this error

> [ERROR] Failed binding IPv4 listening socket: Operation not permitted (1)

I found no clue to solve this.

**Comment by swisspol** [comment]
Is that on iOS device, iOS simulator, Apple TV, tvOS simulator or Mac?

**Comment by epsilonxe** [comment]
It is Mac. Thank you.

**Comment by swisspol** [comment]
What if you set the port to a different value like 8888 or even 0?

**Comment by victorgama** [comment]
@epsilonxe @swisspol Xcode enables sandboxing by default on new applications. Ensure your application's entitlements allows incoming and outgoing connections by marking the respective checkboxes in the **Network** section.

![image](https://user-images.githubusercontent.com/77198/46907708-0cac7580-ceed-11e8-8874-e42514800ef4.png)

**Comment by swisspol** [comment]
@victorgama thanks for help!
