### ISSUE TITLE
How can I check errors?

### ISSUE THREAD

**Issue by Nicejinux** [swisspol/GCDWebServer#397]
If I get some errors (like port bind error or not started server)
How can I check that errors? or how can I handle it?

Recently, I got port bind error in my apps.
but I don't know how to handle it so, I just turn off and turn on my phone.
and change the port number to 0.

Is there anyway to get errors and handle?

**Comment by swisspol** [comment]
What’s the error? On what OS and version?

**Comment by Nicejinux** [comment]
When I tested my app on my phone (iPhoneX 12.0) I got this error from console

### **[ERROR] Failed binding IPv4 listening socket: Address already in use (48)**

**Comment by swisspol** [comment]
What port are you trying to use?

**Comment by shirakaba** [comment]
@Nicejinux this is a port clash issue. If you're testing on iOS simulator, for the given port, run this command in your terminal (example is for port 8888):

```sh
lsof -i:8888
```

This will give you a list of processes already running on that port on your Mac (and their process ids, that is to say 'pids'), or simply a completely empty response if that port is free.

However, if you're running the app directly on your device, I don't know how to check processes in use; you'd have to search for that information yourself.

Provided you know what you're doing (i.e. what you're killing), you can kill those processes before running GCDWebServer on that port:

```sh
kill 12999 # Assuming that the process id (pid) was listed as 12999
```

... Or you should just pick another port to bind to! There's a bit of an art to finding a free port.

**Comment by khush004** [comment]
> ### **[ERROR] Failed binding IPv4 listening socket: Address already in use (48)**

Did any solution has been found? as I am running app in iPhone 6 and I am getting this error.

**Comment by mikeumus** [comment]
Me too. I need to handle the error to get the server running. 

Guess we could try to start the server on our desired port: `webServer.start(withPort: 34814)` 
and then check `webServer.isRunning` and if `false`, then increment the port number and `webServer.start()` again.

Here's a little example:
``` swift
  func retryGcdServer(webServer: GCDWebServer) {
    var limit = 0
    if webServer.isRunning == false && limit < 100 {
      let gcdServerPort = UserDefaults.standard.integer(forKey: "GCDWebServerPort")
      let newPort = gcdServerPort+1
      UserDefaults.standard.set(newPort, forKey: "GCDWebServerPort")
      webServer.start(withPort: UInt(newPort), bonjourName: "FileVacuum Localhost GCD Web Server")
      limit+=1
      retryGcdServer(webServer: webServer)
    }
    print("  🌐 webServer.isRunning: \(webServer.isRunning)")
  }
```
