### ISSUE TITLE
GCDWEBSERVER Help

### ISSUE THREAD

**Issue by dchau2401** [swisspol/GCDWebServer#399]
I am working with a development team and from my understanding they are using GCDWEBSERVER so that my IOS app can communicate with our web application. The connection currently works on my device, but my other users are having issues connecting. I have read that port forwarding may be needed does anybody have more information on this. I'm not a developer and i'm not sure where to reach out for this kind of support.

**Comment by swisspol** [comment]
Make sure the iOS app is running and in the foreground, gcdwebserver was successfully started and running, that you are connecting to the correct IP address and port and finally the WiFi network doesn’t block connections on this port.
