### ISSUE TITLE
Support data network access

### ISSUE THREAD

**Issue by CreatSuns** [swisspol/GCDWebServer#406]
You can add Support data network access？

**Comment by swisspol** [comment]
What do you mean?

**Comment by CreatSuns** [comment]
such as 3G、4G

**Comment by swisspol** [comment]
GCDWebServer itself is just a web server, it doesn’t care what type of network it runs on. If it doesn’t work on cellular networks, it’s most likely because the carrier prevents servers to run (I.e. blocks their port).

**Comment by CreatSuns** [comment]
However, I started the program on the 4G network, causing an unexpected crash, but it was ok to start in the WiFi environment. If it can be set, how do I set it

**Comment by swisspol** [comment]
What's the stack trace and reason in the console for the crash?

**Comment by CreatSuns** [comment]
Thank you for your reply. I just change the network support to local
