### ISSUE TITLE
About redirection

### ISSUE THREAD

**Issue by CreatSuns** [swisspol/GCDWebServer#410]
```
[self addHandlerForMethod:@"GET"
                     path:@"/"
             requestClass:[GCDWebServerRequest class]
             processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {
    
  return [GCDWebServerResponse responseWithRedirect:[NSURL URLWithString:@"index.html" relativeToURL:request.URL]
                                          permanent:NO];
    
}];
```
I redirected the '/' to '/index.html', but now the '/' is indeterminate, and I have no way to determine what the url was when it was passed, so I have no way to determine whether the url is valid or not. Please tell me how should I redirect the invalid url to index.html now

**Comment by CreatSuns** [comment]
I used GCDWebServer as the local server in the project. After the service was started successfully, the webview was loaded successfully. When I refresh the webview, the interface appears blank. How can I redisplay the original interface

**Comment by swisspol** [comment]
The easiest solution is not to do a redirect: simply use a handler to catch all paths then do something different if root path or not.

**Comment by 18734791527** [comment]
<img width="1440" alt="屏幕快照 2019-06-02 20 32 46" src="https://user-images.githubusercontent.com/19185361/58783522-aad38400-8613-11e9-9f47-ef342ed9686d.png">
<img width="274" alt="屏幕快照 2019-06-02 20 33 28" src="https://user-images.githubusercontent.com/19185361/58783524-aad38400-8613-11e9-8dd0-41696412776c.png">
<img width="1440" alt="屏幕快照 2019-06-02 20 53 22" src="https://user-images.githubusercontent.com/19185361/58783525-ab6c1a80-8613-11e9-9611-0e4442988078.png">
Hello.My web is a multilevel folder.How can I find them.
