### ISSUE TITLE
HTTPS requirement

### ISSUE THREAD

**Issue by sartrey** [swisspol/GCDWebServer#418]
Sorry to open a new issue for this requirement.
We are developing a hybrid application.
Web contents will be loaded from local server into WKWebView.
Since our application has opened ATS, we have to use HTTPS for local server.
How about providing support for HTTPS in GCDWebServer?
(I'm trying to use Security API, but it's really difficult for me ...)
We are always waiting for your help.

**Comment by swisspol** [comment]
Sorry, I have no intention to add support for HTTPS.

**Comment by warlockuk** [comment]
I too wondered if this were possible in some way - mainly because we have a requirement to access the navigator geolocation API, and Safari Point Blank refuses access (unless I'm missing an obvious webview setting to allow it)

**Comment by malhaar** [comment]
@swisspol Please reconsider this, iOS 14 on horizon, apple is very adamant on forcing SSL everywhere. Personally I would really hate to use another WebServer than this.

**Comment by sebastianludwig** [comment]
@swisspol purely hypothetical, would you be willing to accept a PR for HTTPS support? Or is your objection more against the added complexity and additional maintenance work than the initial implementation effort?
