### ISSUE TITLE
Debugger getting paused

### ISSUE THREAD

**Issue by bmueller** [swisspol/GCDWebServer#420]
I have GCDWebServer running 24/7 in a Mac app. Every couple days, the debugger gets paused and I'm not sure how to stop this from happening. The only thing that gets printed in the log is the following error messages:

[ERROR] Error while reading from socket 24: Connection reset by peer (54)
[ERROR] Error while writing to socket 24: Broken pipe (32)
[ERROR] Error while reading from socket 24: Connection reset by peer (54)
[ERROR] Error while writing to socket 24: Broken pipe (32)

Is there any way to disable whatever's causing Xcode to pause the debugger when these errors come in? I'd like to keep the server running even if there's an error.

**Comment by DD-P** [comment]
Assuming you want to run your Mac app from Xcode rather than standalone, you could detach the process from the debugger (Menu | Debug | Detach from X) or deactivate breakpoints in Xcode.

**Comment by bmueller** [comment]
Thanks @DD-P but I just got this again after detaching the debugger. The network code is stopping with SIGPIPE. I see that @swisspol already has code included to make sure a socket can't generate a SIG_PIPE, is there anywhere else this needs to be in the app to make sure this error code isn't generated?

**Comment by swisspol** [comment]
Feel free to continue the discussion here but this is not directly related to gcdwebserver
