### ISSUE TITLE
Abort all connections on `stop`

### ISSUE THREAD

**Issue by ravernkoh** [swisspol/GCDWebServer#421]
The following is mentioned in the docs [here](http://cocoadocs.org/docsets/GCDWebServer/2.5/Classes/GCDWebServer.html#//api/name/stop).
> Stopping the server does not abort `GCDWebServerConnection` instances currently handling already received HTTP requests. These connections will continue to execute normally until completion.

Is there a way to abort all the current connections when I stop the server?

**Comment by swisspol** [comment]
There is no API to abort connections IIRC. One way to work around this is to have your handlers check a global variable or equivalent to know if aborting is required and return an error.
