### ISSUE TITLE
Use Lan Interface (maybe en1) on iOS

### ISSUE THREAD

**Issue by boernei** [swisspol/GCDWebServer#423]
Hi,
is it possible to use the ethernet lan interface to serve the webserver?

Seems like in GCDWebServerFunctions.m , en0 for wifi is hardcoded?

**Comment by boernei** [comment]
Ah i remember that the interfaces just have different ip addresses. 
So if Wifi is off and the iOS device is just connected to the Lan Cable via Lighting, Ethernet Adapter the getter serverURL ist not working.

I added another getter serverSecondaryURL which gets the ethernet address on iOS. Seems like en3 is the right interface. Can anybody confirm this.

https://github.com/boernei/GCDWebServer/commit/3b4f83b2d8abf01df7f057fa1d20b1a6c589d34c

Is this interesting for you? Should i open a pull request?

**Comment by swisspol** [comment]
I’d say it’s too much of an edge case to be part of gcdwebserver. Thanks for reporting this issue though!
