### ISSUE TITLE
macOS binding to localhost repeatedly starts and stops

### ISSUE THREAD

**Issue by mikeKane** [swisspol/GCDWebServer#425]
I have a local web server running on localhost port 9330 which works fine. I am attempting to load a local html file with GCDWebserver. It looks like it starts serving the file but all of the resources are missing and the log prints show a constant stream of disconnects. 

```
GCDWebServer disconnected
GCDWebServer connected
GCDWebServer disconnected
GCDWebServer connected
GCDWebServer disconnected
GCDWebServer connected
```

They are both local host but bind to different ports. Here is my GCDServer setup. 
```
- (void)startGCDWebServer {
    
    [GCDWebServer setLogLevel:4];
    
    self._webServer = [[GCDWebServer alloc] init];
    self._webServer.delegate = self;
    [self._webServer addGETHandlerForBasePath:@"/"
                          directoryPath:[[[NSBundle mainBundle] resourcePath] stringByAppendingPathComponent:@"ui"]
                          indexFilename:@"index.html"
                               cacheAge:3600
                     allowRangeRequests:NO];
    NSError *error;
    [self._webServer startWithOptions:@{@"Port":@9331, @"BindToLocalhost":@true} error:&error];
    
    if (error != nil){
        NSLog(@"%@", error);
    }
}
```

I have setup app transport security to allow local networking and I've added localhost to the exception domains. 

Setting a more verbose log setting I see

```
2019-06-19 06:37:52.335520-0400 APP[4315:64284] GCDWebServer disconnected
2019-06-19 06:37:52.340788-0400 APP[4315:64284] GCDWebServer connected
[VERBOSE] [127.0.0.1:9331] 127.0.0.1:54351 404 "GET /xxx" (485 | 104)
2019-06-19 06:37:53.344414-0400 APP[4315:64284] GCDWebServer disconnected
2019-06-19 06:37:53.349533-0400 APP[4315:64284] GCDWebServer connected
[VERBOSE] [127.0.0.1:9331] 127.0.0.1:54354 404 "GET /xxx" (485 | 104)
```

This is running Mac 10.14.

Thanks

**Comment by swisspol** [comment]
What if you remove the bind to local Host Option? What if you remove
sandboxing?

**Comment by mikeKane** [comment]
@swisspol If I don't bind to local host, how do I know which address to load my web view?

Also how can I remove sandboxing?

**Comment by swisspol** [comment]
This is something with your setup not GCDWebServer I’m afraid.
