### ISSUE TITLE
CC_MD5 is deprecated on Catalina

### ISSUE THREAD

**Issue by rafalszastok** [swisspol/GCDWebServer#427]
I'm trying to migrate project to .xcframework on Xcode beta 2. I'm receiving compile errors while trying to build UIKit for macOS. I'm receiving following error in `CGDWebServerFunctions.m`:

> 'CC_MD5' is deprecated: first deprecated in UIKit for macOS 13.0 - This function is cryptographically broken and should not be used in security contexts. Clients should migrate to SHA256 (or stronger).

**Comment by swisspol** [comment]
MD5 is required for one of the authentication methods, it is not something that can be removed.

**Comment by swisspol** [comment]
Is it a warning or an actual build error? In any will deal with it once this new OS has been released.

**Comment by rafalszastok** [comment]
The message looks like a warning but a build error -> I can't prepare a build at all.

What I want to achieve is to port my iPad application to macOS. In recent WWDC gives that opportunity by launching UIKit framework (instead AppKit) on new macOS system. Since this project doesn't support Swift Package Manager the only possible way is build GCDWebServers(iOS) on My Mac with turned on Mac option in General tab.

Is there any other way? e.g. to port to different authentication method? In 2004 in the MD5 found weakness by colliding hash functions and it make sense to change it to more safe crypto hash function.

**Comment by JLehman17** [comment]
Has there been any update on this? I'm also trying to use this library in an application with Mac Catalyst and it's failing to build with the same error.
