### ISSUE TITLE
Expose Responses and Requests to public header  

### ISSUE THREAD

**Issue by adilusman1** [swisspol/GCDWebServer#428]
Hi,
Is there a possibility to expose classes in Responses and Requests directories(e.g.  `GCDWebServerDataResponse`) to public header files. This will make it easier to integrate with Swift Only module and there will be no need to create `WebServer-Bridging-Header.h`(as suggested in the getting started).

 What are your thoughts on it?

**Comment by swisspol** [comment]
I’d rather not do such changes as I suspect it may break existing users.
