### ISSUE TITLE
How do I make a custom GCDWebServer uploader?

### ISSUE THREAD

**Issue by WholeCheese** [swisspol/GCDWebServer#431]
I am looking for a way to create the necessary html, css, and js elements for a custom GCDWebServer uploader.

I have created an iOS test app that uses the GCDWebUploader.  While this uploader is pretty nice I would like to create a more specialized uploader for the app I have in mind.

The problem is I am a rank beginner when it comes to JavaScript, CSS, and HTML.

The GCDWebUploader sample has a very rich bundle of CSS, JS, and HTML resources.  Is there a user friendly desktop tool for creating these files?

**Comment by swisspol** [comment]
Other people may know, but I’m not aware of a tool that would work in such circumstances instead of editing by hand.
