### ISSUE TITLE
Send headers for GCDWebServerStreamedResponse (Server Side Events)

### ISSUE THREAD

**Issue by spearway** [swisspol/GCDWebServer#432]
I am using GCDWebServer to support a Server Side Event subscription. I is working well using and GCDWebServerStreamedResponse with an GCDWebServerAsyncStreamBlock.

The bock is call whenever there is new event to send and this works very well except for WKWebKit. The reason is that GCDWebServer only send the headers with the first event but WKWebKit will timeout within 60s if there is no answer. 

So my question is: is it possible to force GCDWebServer to send the headers immediately and not wait for the first event (data)?

I know I can hack it by sending a "fake" event but I was looking for a cleaner solution.

**Comment by swisspol** [comment]
There is no API you can use to do what you want (for various reasons).
