### ISSUE TITLE
Noob question: Can I change hostname alias?

### ISSUE THREAD

**Issue by Yuripetusko** [swisspol/GCDWebServer#438]
Sorry I am not Obj-c developer, I was wondering if I can set hostname alias using GCDWebServer to something other than localhost or 127.0.0.1. Like `my-custom-hostname` for example making full URL `http://my-custom-hostname:8080`

**Comment by Yuripetusko** [comment]
got my answer here

https://github.com/bykof/cordova-plugin-webserver

**Comment by zhihuitang** [comment]
How did you manage it? @Yuripetusko

**Comment by Yuripetusko** [comment]
> How did you manage it? @Yuripetusko

I didn't :(
