### ISSUE TITLE
how to send mp4 file with streaming response?

### ISSUE THREAD

**Issue by aybarsyalcin** [swisspol/GCDWebServer#44]
Hi, 
When server request is mp4 files, I want to response changed other mp4 from NSdata formatted. I research many times. But I haven't solve problem. How can I use GCDWebServerStreamedResponse class?. Please help me?

**Comment by daigewuwy** [comment]
> 嗨，我尝试了GCDWebServerStreamedResponse方法，您可以在下面看到，但是控制台
> 向套接字32写入时出错：
> [[ERROR]错误：管道损坏（32）[ERROR]向套接字28写入时出错：管道（32）损坏
> [ERROR] ]写入套接字31时出错：管道（32）损坏
> [错误]写入套接字54时出错：管道（32）损坏”。
> 
> 我不明白 怎么了？
> 
> ```
> [server addHandlerForMethod:@"GET"
>                       pathRegex:@"/.*.mp4"
>                    requestClass:[GCDWebServerRequest class]
>                    processBlock:^GCDWebServerResponse *(GCDWebServerRequest* request) {
> 
> 
>                        return [GCDWebServerStreamedResponse responseWithContentType:@"video/mp4" streamBlock:^NSData *(NSError** error) {
>                            NSData *decryptedData = [DecryptFile decrypt:@"decrypted path"];
> 
>                            return decryptedData;
> 
>                        }];
> 
> 
> 
>                    }];
> ```
Hello, I have encountered the same problem as you. I also tried the solution given by you and the author, but it still can't be done. Can you tell me how to solve it? About playing encrypted video
