### ISSUE TITLE
Connection is not reestablished once phone is locked

### ISSUE THREAD

**Issue by khush004** [swisspol/GCDWebServer#445]
Hello @swisspol, Thanks for this awesome library I am facing one issue,   
I have start playing video then I press home button (App is in Background now) and I have locked the phone now when I unlocked the phone and opening app again then video is not playing as Connection is not reestablished or reconnected.

Please help me with this 

Thanks :)

**Comment by swisspol** [comment]
Locking your phone suspends the foreground app if I recall correctly. See README for what happens in this case.
