### ISSUE TITLE
https

### ISSUE THREAD

**Issue by nbqiyue** [swisspol/GCDWebServer#453]
hello, When is **HTTPS** supported?

**Comment by swisspol** [comment]
There is no plan to add HTTPS support.

**Comment by malhaar** [comment]
@swisspol Please reconsider this, iOS 14 on horizon, apple is very adamant on forcing SSL everywhere. Personally I would really hate to use another WebServer than this.

**Comment by masture** [comment]
External LTE enabled devices, such as DashCams, Trackers, which are certified by network operators (e.g. AT&T) require that all outgoing calls be secured (HTTPS). If we cannot have HTTPS servers on iOS, then these devices wont be able to connect with iPhones and/or any Apps running on iOS. 
Please suggest possible alternatives to overcome this.
