### ISSUE TITLE
I can't import GCDWebServer core and uploader in different env.

### ISSUE THREAD

**Issue by yunluoxin** [swisspol/GCDWebServer#454]
In our app, we need import "GCDWebServer/Core in DEBUG and Release, cause /Uploader 's bundle is large, it will increase app package size, so we decide just import  /Uploader in DEBUG, and the problem happens. We can't build project! And last I found  GCDWebServer/Core and /Uploader just in one pod, it generates just one libxxx.a .     So we can't do what we want.

In Firebase lastest release, it packages Firebase/Core and Firebase/Analystic to FirebaseCore and FirebaseAnalystic, FirebaseCore and FirebaseAnalystic are different library actually.   I think it's a quite good method to solve this problem. 

Wait for your message. Thanks.

**Comment by swisspol** [comment]
Instead of using CocoaPods you can manually add the source code and resources to your app and then you can do exactly whatever you want.
