### ISSUE TITLE
Please add a delegate method to report errors

### ISSUE THREAD

**Issue by emadrazo** [swisspol/GCDWebServer#455]
Please add a delegate method to report any error or port changing when resuming suspension.

Example:
server is started on port 8080 (port is free and the server is started)
Then the app goes background and the server is suspended
When app is restarted 8080 port is occupied

A delegate method would give the opportunity to restart server in another port.
Thanks!

**Comment by swisspol** [comment]
No new work is happening on GCDWebServer.
