### ISSUE TITLE
Variable bitrate song streaming issue

### ISSUE THREAD

**Issue by prakhar181** [swisspol/GCDWebServer#459]
I have used updated GCDWebserver to stream songs from iPhone to other devices. For constant bitrate, songs streamed from a server, the song player of the client works fine and continues to play the songs present in the queue. 

A variable bit rate song doesn't stream properly from the server. A song with a variable bit rate continues to stream even though its elapsed time reaches zero.

Please guide me on how to resolve this issue.

**Comment by swisspol** [comment]
Check the application logs, they will tell you exactly what the server is doing and how the client is talking to the server.

**Comment by prakhar181** [comment]
Thanks a lot, I'll check the logs once again.
