### ISSUE TITLE
Push log data to our log system

### ISSUE THREAD

**Issue by dmac81** [swisspol/GCDWebServer#464]
Anyone have any guidance on Swizzling this method?

https://github.com/swisspol/GCDWebServer/blob/master/GCDWebServer/Core/GCDWebServer.m#L90

We want to push this log info into our logging system and not use `print`.  I have swizzled before but not with a method that sits outside of a class like this does.  Thoughts?

**Comment by swisspol** [comment]
You can’t swizzle a C function. Also to customize logging just use +setBuiltInLogger

**Comment by dmac81** [comment]
@swisspol thank you! Was on 3.5.2, should have upgraded before asking!
