### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by dmac81** [swisspol/GCDWebServer#470]
We have our app setup with one GET handler that is pointed at a directory in our app.  For most of our users this works and they don't see any issues.  For some of our users about 50% of the time they get back a blank html dom (<html><head></head><body></body></html) rather than our page that is in the app bundle.  Any ideas why this might occur?

**Comment by swisspol** [comment]
You would need the log from the server to understand what is happening. It’s unlikely to be a bug in gcdwebserver as nobody ever reported something like this in years of existence,
