### ISSUE TITLE
Need a excludeFolders propterty

### ISSUE THREAD

**Issue by dlpigpen** [swisspol/GCDWebServer#476]
In development, I found an issue. There is no property to hide any desired folders. 
For example, a realm database folder is generated automatically when using the realm. If we point the GCDWebserver at the same directory of the realm folder. 
The user can see it and delete it the app will be crashed then. This is only a simple case in many cases.

**Comment by swisspol** [comment]
Depending on the API, you can subclass or write custom handlers or use delegate methods.
