### ISSUE TITLE
MobileCoreServices Warning

### ISSUE THREAD

**Issue by HermanKayy** [swisspol/GCDWebServer#484]
Theres a warning in regards to MobileCoreServices being renamed to CoreServices. Any plans to fix this in an upcoming release?

**Comment by tinder-owenthomas** [comment]
Any update on this @swisspol? We are unable to complete the move to Xcode 11.4 because of this warning. I believe a PR was opened to fix the issue, but it was closed instead of merged.

**Comment by HermanKayy** [comment]
@swisspol any follow up on this issue?

**Comment by swisspol** [comment]
I merged the PR

**Comment by atom-wintermute** [comment]
will you release new version with these changes?

**Comment by robmaceachern** [comment]
@swisspol could you please release a new pod version to clear up this warning? Thank you 🙏
