### ISSUE TITLE
Use GCDWebServer as a API server

### ISSUE THREAD

**Issue by zrg-team** [swisspol/GCDWebServer#491]
Can i request to GCDWebServer from a website ? 
it worked when i request from localhost server ( localhost:3000 (webserver from my MAC) request to localhost:5669 (GCDWebServer))
But show below error when i deploy my website and request from domain:
![alt test](https://i.gyazo.com/85d2bfe9a45c5d16666abe4686e789d8.png)

**Comment by swisspol** [comment]
GCDWebServer is a regular HTTP server so you can call it from anything as it’s reachable over the network.
