### ISSUE TITLE
Playing mov type video not smooth stored GCDWebServer，other type video is normal.

### ISSUE THREAD

**Issue by PureCoderPan** [swisspol/GCDWebServer#492]
I get video url that stored in GCDWebServer, and transfer this url to PC. Playing video with url when 
PC end get url. Playing  with `mp3`  video is worked , but encounter problem when play `mov` type, video  playing not fluent. Following `weakSelf.filePath` is playing resource path in photoLibrary。

Have Anyone has suggestion to fixed this problem?

```
[self.webServer addDefaultHandlerForMethod:@"GET"
                                      requestClass:[GCDWebServerRequest class]
                                 asyncProcessBlock:^(GCDWebServerRequest* request, GCDWebServerCompletionBlock completionBlock) {
BOOL requestCheck = [request.URL.absoluteString isEqualToString:weakSelf.openFilePath];
GCDWebServerResponse *response;
BOOL suiteByteRange = requestCheck && request.hasByteRange;
if (requestCheck) {
      unsigned long long totalSize = [[weakSelf.manager attributesOfItemAtPath:weakSelf.filePath error:nil] fileSize];
      LOG(@"location:%zd----length:%zd----totalSize:%llu", request.byteRange.location, request.byteRange.length, totalSize);
      LOG(@"filePath:%@", weakSelf.openFilePath);
      response = [GCDWebServerFileResponse responseWithFile:weakSelf.filePath byteRange:request.byteRange];
      [response setValue:@"bytes" forAdditionalHeader:@"Accept-Ranges"];                
      LOG(@"response:%@", response);
  } else {
        response = [GCDWebServerResponse responseWithStatusCode:404];
  }
  if (completionBlock) {
        completionBlock(response);
   }
}];
```

**Comment by swisspol** [comment]
.mov is just a container type, what matters is the codecs used by the audio / video streams. I’d suggest trying different ones.

**Comment by PureCoderPan** [comment]
.mov type video using h264 coding video stream,&nbsp; i also using .mp4 video h264 coding serving by GCDWebServer，anything is ok，very&nbsp; fluency。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "swisspol/GCDWebServer"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月11日(星期六) 凌晨0:30
收件人:&nbsp;"swisspol/GCDWebServer"<GCDWebServer@noreply.github.com&gt;;
抄送:&nbsp;"心有所属"<1007877954@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [swisspol/GCDWebServer] Playing mov type video not smooth stored GCDWebServer，other type video is normal. (#492)





 
.mov is just a container type, what matters is the codecs used by the audio / video streams. I’d suggest trying different ones.
