### ISSUE TITLE
Is it possible to mock JSON API with GCDWebServer?

### ISSUE THREAD

**Issue by Haibo-Zhou** [swisspol/GCDWebServer#493]
I had used GCDWebUploader in my published music app for music uploading, and it is working perfectly.

Is it possible to mock some JSON API with GCDWebServer? I didn't see some example in the main page. If yes, some example of code would be highly appreciated!

**Comment by swisspol** [comment]
GCDWebServwr is a regular HTTP server so yes you can do that.
