### ISSUE TITLE
POST Request arguments empty when uploading file

### ISSUE THREAD

**Issue by iandwelker** [swisspol/GCDWebServer#495]
On my site, I'm able to send post requests with plain text <input> forms, and they're accepted correctly by the handler in my GCDWebUploader. However, whenever I upload a file, no matter what else is uploaded with it, the arguments variable of the GCDWebServerURLEncodedFormRequest is always empty. 

My HTML form:
```
<form action="/uploads" method="POST" enctype="multipart/form-data" id="sendform" class="textbox">
    <input value="" onclick="document.getElementById('attachmentbutton').click();" type="button" id="unhiddenbutton">
    <input type="file" name="attachments" id="attachmentbutton" style="display: none" multiple>
    <textarea name="text" id="sendbox" oninput="auto_grow(this)" form="sendform"></textarea>
    <input type="submit" value="" id="sendbutton">
</form>
```
&nbsp;
My server & post handler: 
```
let server = GCDWebUploader(uploadDirectory: NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0])

server.addHandler(forMethod: "POST", path: "/uploads", request: GCDWebServerURLEncodedFormRequest.self, processBlock: { request in
            
    let req = (request as! GCDWebServerURLEncodedFormRequest) 
    /// When a file is uploaded, req.arguments has 0 key/value pairs.
    /// When no file is uploaded, req.arguments has the expected key/value pairs.

    return GCDWebServerDataResponse(text: "true")
})
```
&nbsp;
Is there some crucial section of the handler that I'm failing to implement?

**Comment by swisspol** [comment]
I can’t say of the top of my head. You would need to put a breakpoint in parseData in GCDWebServerMIMEStreamParser and figure out what the code does.

**Comment by iandwelker** [comment]
Thanks for pointing out GCDWebServerMIMEStreamParser; I realized that's only available for GCDWebServerMultiPartFormRequest, so I switched my request type to GCDWebServerMultiPartFormRequest and it correctly returned my files and arguments.

 I appreciate the quick response on this issue! I'll mark it closed.
