### ISSUE TITLE
Supporting keep-alive connections

### ISSUE THREAD

**Issue by chaitanyabaranwal** [swisspol/GCDWebServer#498]
Hi there! I noticed that the socket connection does not get reused for different requests in GCDWebServer (in line with the documentation of this library not supporting keep-alive). However, the application I am using GCDWebServer for would work best if connections are reused.

Can I check if this functionality can be implemented, and if not, what part of the code would require a change so that I can try implementing it myself?

**Comment by swisspol** [comment]
There are no plans to implemented this. It would be quite complicated too.
