### ISSUE TITLE
Target Integrity: MobileCoreService

### ISSUE THREAD

**Issue by beat843796** [swisspol/GCDWebServer#506]
compiling brings up the following warning: 
Showing Recent Messages
...Pods/Pods.xcodeproj MobileCoreServices has been renamed. Use CoreServices instead.

Can this be changed to CoreServices?

**Comment by swisspol** [comment]
This has been fixed in f4cf591e50eb0c56ce64066b31fea6855ffb5bd2

**Comment by rnkyr** [comment]
still facing this issue. I see your podspec has correct names, but `GCDWebServer.debug.xcconfig` (probably generated by cocoapods) contains incorrect one:

```
OTHER_LDFLAGS = $(inherited) -l"z" -framework "CFNetwork" -framework "MobileCoreServices"
```

I'm using the latest stable version of Cocoapods, 1.9.3

UPD: looks like specs repo contains already incorrect names: https://github.com/CocoaPods/Specs/commit/18f6adf3e5303ceeed1e8e99a766e3c3dd2ca713

**Comment by rnkyr** [comment]
@swisspol, could you please take a look?
