### ISSUE TITLE
Bonjour not working in iOS 14

### ISSUE THREAD

**Issue by dcosel86** [swisspol/GCDWebServer#509]
Hello,

My app attempts to start a WebServer using `webServer?.start(withPort: 8080, bonjourName: "GCDWebServer")`
However, in iOS14 `webServerDidCompleteBonjourRegistration(_ server:)` is never called. I think that is due to the fact that new keys need to be added to the info.plist. 

I've added:
Privacy - Local Network Usage Description 
Bonjour Services

I'm not sure what to add for the services though? Please help?

Thanks!
David

**Comment by RichtFunk** [comment]
Hi David,

I had the same issue. Try the value 
_http._tcp
for Bonjour services Item 0. This worked for me.

Best regards,
Michael
