### ISSUE TITLE
Add support for "If-Range" header

### ISSUE THREAD

**Issue by swisspol** [swisspol/GCDWebServer#51]
This header can be either set to the "ETag" or "Last-Modified" value for the entity. If they don't match the current values, the "Range" header should be ignored and the entire resource returned with a 200 status, otherwise only the required byte range should be returned with a 206 status.

Currently GCDWebServer implements the latter but not the former.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.27

**Comment by Sopan** [comment]
How can we remove if-modified-since and if-none-match from request headers ?

**Comment by swisspol** [comment]
They come from the HTTP client like a web browser. What exactly are you trying to do?

**Comment by Sopan** [comment]
The problem is I want to remove caching as its displaying old content sometimes which I believe results from content caching. cacheControlMaxAge is set to no-cache but still at times I see old content.

**Comment by Sopan** [comment]
I receive 304 even if there is a fresh update in content and I refresh it.

**Comment by swisspol** [comment]
Try looking at the web inspector in your web browser and looking at the request headers and response headers to and from GCDWebServer. It will tell you exactly what is happening.

**Comment by swisspol** [comment]
What do you mean by "fresh update in content"? How are you serving the content with GCDWebServer?

**Comment by swisspol** [comment]
You can trace what is happening in `- (GCDWebServerResponse*)overrideResponse:(GCDWebServerResponse*)response forRequest:(GCDWebServerRequest*)request` to understand why  CGDWebServer returns a 304.

**Comment by Sopan** [comment]
:) Yep I checked that API, the flow of requests suggests that for a new content I am getting the old response which happens because request contains ifModifiedSince property (which gets set from the request header). I wonder shouldn't it just bypass the below condition if there is a change
if ((response.statusCode >= 200) && (response.statusCode < 300) && _CompareResources(response.eTag, request.ifNoneMatch, response.lastModifiedDate, request.ifModifiedSince))

**Comment by swisspol** [comment]
I don't know what you mean by "change". If you go inside `_CompareResources()` it will tell you why it thinks there is no change.

**Comment by Sopan** [comment]
I meant the html is modified, but overrideResponse returns me back the old one and it happens sometimes.

**Comment by swisspol** [comment]
Modified like on disk? In memory?

**Comment by Sopan** [comment]
Disk
