### ISSUE TITLE
Target Integrity: MobileCoreServices has been renamed. Use CoreServices instead.

### ISSUE THREAD

**Issue by raulferrerdev** [swisspol/GCDWebServer#510]
On intall GCDWebserver via pod and open project on XCode 12, this warning message appears:

'Target integitry'. MobileCoreServices has been renamed. Use CoreServices instead.

After that, I can't build project as 'No such module "GCDWebServers" message appears.

Are both warning related? Is there a solution?

**Comment by goktugaral** [comment]
Same situation here! Could you support new `CoreServices`. We dedicade our self for zero warnings! ;) Thanky you so much.

**Comment by swisspol** [comment]
This is fixed in f4cf591e50eb0c56ce64066b31fea6855ffb5bd2
