### ISSUE TITLE
Xcode 12, iOS 14

### ISSUE THREAD

**Issue by ghostcrying** [swisspol/GCDWebServer#513]
With Xcode 12 and iOS 14

- Now **_'func webServerDidCompleteBonjourRegistration(_ server: GCDWebServer) '** can't response the delegate.

- The '**_bonjourServerURL_**' can't reach:  that mean USB translate can't be used.

**Comment by alexandr-appslab** [comment]
+1

**Comment by swisspol** [comment]
See #525
