### ISSUE TITLE
Swift Package Manager?

### ISSUE THREAD

**Issue by trevor-sonic** [swisspol/GCDWebServer#515]
Hi I'm sorry if here is the right place to write this but I'm wondering if any consideration to make SPM version of this wonderful framework?
I have a big project divided in to different projects. I'd like to use GCDWebServer in a separated module but I have lot of compile errors. (Cocoa pods is not an option) 
With SPM, this framework will last forever, I'm sure.

**Comment by Haibo-Zhou** [comment]
I buy a Mac mini (Apple Silicon), and it has compatibility issue `pod install` with CocoaPod now. So could we get a SPM support now?

**Comment by swisspol** [comment]
See #499
