### ISSUE TITLE
Error on GCDWebServer when running carthage update

### ISSUE THREAD

**Issue by ppbachims** [swisspol/GCDWebServer#521]
I encountered the following error when running carthage update: 

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Intermediates.noindex/ArchiveIntermediates/GCDWebServers\ (tvOS)/IntermediateBuildFilesPath/UninstalledProducts/appletvos/GCDWebServers.framework/GCDWebServers /Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-appletvsimulator/GCDWebServers.framework/GCDWebServers -output /Projects/GamingWrapper/Carthage/Build/tvOS/GCDWebServers.framework/GCDWebServers

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/8y/xgmx629d05s0hv_bm2wzmjwd3vnylm/T/carthage-xcodebuild.0GLKsv.log

Anyone any idea what is happening ?

**Comment by armcknight** [comment]
I also hit this error. It happens because when carthage tries to `lipo` together the `iphoneos` and `iphonesimulator` builds of the framework, since they both contain `arm64`, it fails:
```
fatal error: /Applications/Xcode12.2/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Intermediates.noindex/ArchiveIntermediates/GCDWebServers (iOS)/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GCDWebServers.framework/GCDWebServers and /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-iphonesimulator/GCDWebServers.framework/GCDWebServers have the same architectures (arm64) and can't be in the same fat output file

❯ dwarfdump -uuid /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Intermediates.noindex/ArchiveIntermediates/GCDWebServers\ \(iOS\)/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GCDWebServers.framework/GCDWebServers
UUID: 0DAD4B77-3076-3A58-A064-322F61D587DD (armv7) /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Intermediates.noindex/ArchiveIntermediates/GCDWebServers (iOS)/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GCDWebServers.framework/GCDWebServers
UUID: B0F8F19C-A68D-32F8-ABDE-D42631619949 (arm64) /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Intermediates.noindex/ArchiveIntermediates/GCDWebServers (iOS)/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/GCDWebServers.framework/GCDWebServers

❯ dwarfdump -uuid /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-iphonesimulator/GCDWebServers.framework/GCDWebServers
UUID: 789AA418-385D-3AAB-8D0E-214E30A29F7E (x86_64) /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-iphonesimulator/GCDWebServers.framework/GCDWebServers
UUID: 6DD46798-095B-3E0A-A5EF-7A76ACC67393 (i386) /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-iphonesimulator/GCDWebServers.framework/GCDWebServers
UUID: 257F96DC-A8DF-3D84-83A0-3F661CD74150 (arm64) /Users/andrewmcknight/Library/Caches/org.carthage.CarthageKit/DerivedData/12.2_12B45b/GCDWebServer/3.5.4/Build/Products/Release-iphonesimulator/GCDWebServers.framework/GCDWebServers
```

I went into the project settings and overrode it to not include arm64 with simulator builds, and it worked for me afterwards: 
![image](https://user-images.githubusercontent.com/3241469/101436419-93d1ba00-38ba-11eb-9d98-00a79e476960.png)

I'm not sure if it's better to commit that change to this project or to use the workaround mentioned here: https://github.com/Carthage/Carthage/issues/3019#issuecomment-693381253

**Comment by swisspol** [comment]
Thanks!
