### ISSUE TITLE
Bonjour isn't working on iOS 14.x

### ISSUE THREAD

**Issue by sator69** [swisspol/GCDWebServer#525]
Bonjour isn't working on iOS 14.x in for iPhone. The service is working for simulator only. Framework should be revised.

**Comment by DD-P** [comment]
See https://stackoverflow.com/questions/65190065/nsnetservicebrowser-did-not-search-with-error-72008-on-ios-14/65190066

**Comment by swisspol** [comment]
Thanks!

**Comment by Haibo-Zhou** [comment]
> See https://stackoverflow.com/questions/65190065/nsnetservicebrowser-did-not-search-with-error-72008-on-ios-14/65190066

Thank you! Fix my issue too, I also comment something in this stackoverflow post.
