### ISSUE TITLE
Is it possible to use GCDWebServer when on LTE, or 3G networks?

### ISSUE THREAD

**Issue by emichaud** [swisspol/GCDWebServer#53]
Hi, thanks for the great work.  I tried using the web server when off wifi, however the ip address shows null after launch.  Is it possible to use it that way?

**Comment by ElliotCambo** [comment]
Hey @swisspol  would you be able to elaborate a little more on the following. 

>>The problem with running a server from your phone on 3G network is that in practice, they block such services and your phone might be on a local network (e.g. with an IP address like 10.0.1.10) which prevents it to be accessible from Internet anyway.<<

I work in the telecommunications industry, but would really like to understand why the carrier blocks These services. I'm trying to get myself up and running with GCDWebServer on 3G/4G , all works well on wifi but when i look up my phones public ip via google, and set that as the ip address of my GCDWebServer webserver , i cannot get the request to land on the phone. Any ideas?
