### ISSUE TITLE
How to use this package in iOS Swift 5 project in xcode 13.2 ?

### ISSUE THREAD

**Issue by Gelembjuk** [swisspol/GCDWebServer#578]
HI All,
I try to use GCDWebServer in my iOS app , but all attempts fail.
I include packages in my project using Swift Package Manager . This package can be found, but can not be imported.
I see it is known error , there is pull request but not accepted.
https://github.com/swisspol/GCDWebServer/pull/516 

I also tried to clone some copy of this project locally , which includes SPM change and imported it as local package. But it still doesn't work.

In all cases i see "No such module 'GCDWebServer'" when i try "import GCDWebServer"

Are there any workarounds to use this package today? 
My project is for iOS, target 15.0 . XCode 13.2 . Swift 5 .

What can i do to use this package in my app?

**Comment by nilsnilsnils** [comment]
I used this one https://github.com/SlaunchaMan/GCDWebServer.git
