### ISSUE TITLE
Invalid font

### ISSUE THREAD

**Issue by rastaman111** [swisspol/GCDWebServer#598]
ITMS-90853: Invalid font - There was an error validating the font at 'Test.app/Frameworks/GCDWebServer.framework/GCDWebUploader.bundle/Contents/Resources/fonts/glyphicons-halflings-regular.woff'. Font not supported by platform.

**Comment by lucaji** [comment]
G'day Alex, that is not really a problem of GCDWebServer IMHO. Just delete that file inside the bundle as it depends on Apple's framework not supporting WOFF fonts.

Pardon me if I looked up on your profile and inferred that you are becoming a new procifient software developer. If this is correct please allow me to give you this advice:

1. If you open an issue, you are supposed to give all information necessary to replicate your problem and not just the error message(s);
2. Before opening an issue on a GitHub Repo, please google up the information you are given by the compiler/IDE/debug in the error messages like: "ITMS-90853" and "WOFF Font not supported by platform" to find solutions (this is the longest part);
3. Opening an issue on a GitHub Repo is usually meant to improve the repository itself, not to help you out with your projects (unless you explicity specify what you are doing).

If you need help for your own project, you should use [StackOverflow](https://stackoverflow.com/questions/64348482/itms-90853-invalid-font-on-testflight-external-testing) as there in the past years it used to be lots of nice people wanting to help other people out, but beware: nowadays it's all about badges and scores and people might troll you if you don't follow the code of conduct and learn how to post questions (or better not post at all, just use google). Let me know if I can help and good luck with your passion and career into Software Development 👍

**Comment by lucaji** [comment]
https://github.com/swisspol/GCDWebServer/issues/594

Please do your research! :D
