### ISSUE TITLE
Access the webserver without WLAN locally on iPad

### ISSUE THREAD

**Issue by daisylassie** [swisspol/GCDWebServer#84]
Hi, is there a possibility to work with the gcdwebserver locally when there is no lan connection?

if yes, what is the serverurl instead of the ip?

thanks, daisylassie

**Comment by loretoparisi** [comment]
See PortMapper by Apple, 

https://developer.apple.com/legacy/library/samplecode/PortMapper/Listings/PortMapper_h.html

then on a iPhone app try

```objective-c
// Here's how to simply obtain your local and public address(es):
    NSString *addrStr = [PortMapper localAddress];
    NSLog(@"** Local address is %@", addrStr);
    if( [PortMapper localAddressIsPrivate] )
        NSLog(@"** ...that's a private address");
    addrStr = [PortMapper findPublicAddress];
    NSLog(@"** Public address is %@", addrStr);
```
